-- Sprint 100 PostgreSQL migration: production hardening operations runtime.
CREATE TABLE IF NOT EXISTS deployment_environments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, code text NOT NULL, name text NOT NULL, environment_type text NOT NULL DEFAULT 'staging', status text NOT NULL DEFAULT 'active', region text NOT NULL DEFAULT '', base_url text NOT NULL DEFAULT '', database_mode text NOT NULL DEFAULT 'json', owner_team text NOT NULL DEFAULT 'platform', deployment_strategy text NOT NULL DEFAULT 'rolling', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id, code));
CREATE TABLE IF NOT EXISTS release_manifests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, version text NOT NULL, environment_id uuid NOT NULL, status text NOT NULL DEFAULT 'draft', git_commit text NOT NULL DEFAULT '', git_branch text NOT NULL DEFAULT '', artifact_uri text NOT NULL DEFAULT '', migration_range text NOT NULL DEFAULT '', release_notes text NOT NULL DEFAULT '', approved_by text NOT NULL DEFAULT '', approved_at timestamptz, deployed_by text NOT NULL DEFAULT '', deployed_at timestamptz, rollback_version text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS operational_health_checks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, environment_id uuid NOT NULL, release_id uuid, check_key text NOT NULL, label text NOT NULL, status text NOT NULL DEFAULT 'unknown', message text NOT NULL DEFAULT '', observed_value text, expected_value text, checked_at timestamptz NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS operational_runbook_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, title text NOT NULL, category text NOT NULL, severity text NOT NULL DEFAULT 'medium', symptom text NOT NULL DEFAULT '', diagnosis_steps jsonb NOT NULL DEFAULT '[]'::jsonb, remediation_steps jsonb NOT NULL DEFAULT '[]'::jsonb, escalation_path text NOT NULL DEFAULT '', active boolean NOT NULL DEFAULT true, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_deployment_environments_tenant_type ON deployment_environments (tenant_id, environment_type, status);
CREATE INDEX IF NOT EXISTS idx_release_manifests_tenant_environment ON release_manifests (tenant_id, environment_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_release_manifests_tenant_status ON release_manifests (tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_operational_health_checks_tenant_environment ON operational_health_checks (tenant_id, environment_id, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_operational_health_checks_tenant_release ON operational_health_checks (tenant_id, release_id, check_key);
CREATE INDEX IF NOT EXISTS idx_operational_runbook_entries_tenant_category ON operational_runbook_entries (tenant_id, category, severity, active);
