-- Sprint 140 PostgreSQL migration: security incident response.
CREATE TABLE IF NOT EXISTS security_incidents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, incident_number text NOT NULL, title text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'reported', severity text NOT NULL DEFAULT 'medium', incident_type text NOT NULL DEFAULT 'other', source text NOT NULL DEFAULT '', reported_by text NOT NULL DEFAULT '', owner text NOT NULL DEFAULT '', reported_at timestamptz NOT NULL, detected_at timestamptz NOT NULL, contained_at timestamptz, resolved_at timestamptz, closed_at timestamptz, affected_asset_ids jsonb NOT NULL DEFAULT '[]'::jsonb, affected_user_ids jsonb NOT NULL DEFAULT '[]'::jsonb, related_alert_ids jsonb NOT NULL DEFAULT '[]'::jsonb, related_vulnerability_ids jsonb NOT NULL DEFAULT '[]'::jsonb, business_impact text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS security_incident_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), incident_id uuid NOT NULL, tenant_id text NOT NULL DEFAULT '', title text NOT NULL, description text NOT NULL DEFAULT '', task_type text NOT NULL DEFAULT 'other', status text NOT NULL DEFAULT 'open', owner text NOT NULL DEFAULT '', due_at timestamptz, completed_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS security_incident_evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), incident_id uuid NOT NULL, tenant_id text NOT NULL DEFAULT '', evidence_type text NOT NULL DEFAULT 'other', title text NOT NULL, description text NOT NULL DEFAULT '', file_url text NOT NULL DEFAULT '', hash text NOT NULL DEFAULT '', collected_by text NOT NULL DEFAULT '', collected_at timestamptz NOT NULL, chain_of_custody jsonb NOT NULL DEFAULT '[]'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS security_incident_communications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), incident_id uuid NOT NULL, tenant_id text NOT NULL DEFAULT '', audience text NOT NULL, channel text NOT NULL DEFAULT 'email', subject text NOT NULL DEFAULT '', body text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft', approved_by text NOT NULL DEFAULT '', approved_at timestamptz, sent_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS security_incident_reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), incident_id uuid NOT NULL, tenant_id text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'scheduled', facilitator text NOT NULL DEFAULT '', scheduled_at timestamptz NOT NULL, completed_at timestamptz, root_cause text NOT NULL DEFAULT '', lessons_learned text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS security_incident_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), incident_id uuid NOT NULL, review_id uuid, tenant_id text NOT NULL DEFAULT '', title text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'open', severity text NOT NULL DEFAULT 'medium', owner text NOT NULL DEFAULT '', due_at timestamptz, completed_at timestamptz, accepted_reason text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_security_incidents_tenant_status ON security_incidents (tenant_id, status, severity, reported_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_incident_tasks_incident_status ON security_incident_tasks (incident_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_security_incident_evidence_incident ON security_incident_evidence (incident_id, evidence_type);
CREATE INDEX IF NOT EXISTS idx_security_incident_comms_incident_status ON security_incident_communications (incident_id, status);
CREATE INDEX IF NOT EXISTS idx_security_incident_reviews_incident_status ON security_incident_reviews (incident_id, status);
CREATE INDEX IF NOT EXISTS idx_security_incident_actions_incident_status ON security_incident_actions (incident_id, status, severity, due_at);
