-- Sprint 141 PostgreSQL migration: threat intelligence.
CREATE TABLE IF NOT EXISTS threat_feeds (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, code text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'active', source_url text NOT NULL DEFAULT '', owner text NOT NULL DEFAULT '', trust_level text NOT NULL DEFAULT 'medium', last_ingested_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS threat_indicators (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, feed_id uuid, value text NOT NULL, normalized_value text NOT NULL, indicator_type text NOT NULL DEFAULT 'other', confidence text NOT NULL DEFAULT 'medium', severity text NOT NULL DEFAULT 'medium', first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL, expires_at timestamptz, tags jsonb NOT NULL DEFAULT '[]'::jsonb, description text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS threat_actors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, name text NOT NULL, aliases jsonb NOT NULL DEFAULT '[]'::jsonb, status text NOT NULL DEFAULT 'tracked', motivation text NOT NULL DEFAULT '', regions jsonb NOT NULL DEFAULT '[]'::jsonb, sectors jsonb NOT NULL DEFAULT '[]'::jsonb, description text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS threat_campaigns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, actor_id uuid, name text NOT NULL, status text NOT NULL DEFAULT 'watching', severity text NOT NULL DEFAULT 'medium', started_at timestamptz NOT NULL, ended_at timestamptz, objective text NOT NULL DEFAULT '', techniques jsonb NOT NULL DEFAULT '[]'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS threat_sightings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, indicator_id uuid NOT NULL, asset_id text NOT NULL DEFAULT '', user_id text NOT NULL DEFAULT '', source text NOT NULL DEFAULT 'manual', observed_at timestamptz NOT NULL, raw_event_id text NOT NULL DEFAULT '', count integer NOT NULL DEFAULT 1, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS threat_enrichments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, indicator_id uuid NOT NULL, provider text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'queued', requested_at timestamptz NOT NULL, completed_at timestamptz, score numeric(8,2), result jsonb NOT NULL DEFAULT '{}'::jsonb, error_message text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS threat_watchlists (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'active', indicator_ids jsonb NOT NULL DEFAULT '[]'::jsonb, owner text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_threat_feeds_tenant_status ON threat_feeds (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_threat_indicators_lookup ON threat_indicators (tenant_id, indicator_type, normalized_value, severity);
CREATE INDEX IF NOT EXISTS idx_threat_actors_tenant_status ON threat_actors (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_threat_campaigns_tenant_status ON threat_campaigns (tenant_id, status, severity);
CREATE INDEX IF NOT EXISTS idx_threat_sightings_indicator ON threat_sightings (indicator_id, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_threat_enrichments_indicator_status ON threat_enrichments (indicator_id, status);
CREATE INDEX IF NOT EXISTS idx_threat_watchlists_tenant_status ON threat_watchlists (tenant_id, status);
