-- Sprint 142 PostgreSQL migration: SIEM and detection engineering.
CREATE TABLE IF NOT EXISTS siem_log_sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, code text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', source_type text NOT NULL DEFAULT 'other', status text NOT NULL DEFAULT 'planned', owner text NOT NULL DEFAULT '', ingest_method text NOT NULL DEFAULT '', parser_name text NOT NULL DEFAULT '', last_event_at timestamptz, expected_events_per_hour integer NOT NULL DEFAULT 0, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS siem_detection_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, code text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', rule_type text NOT NULL DEFAULT 'custom', status text NOT NULL DEFAULT 'draft', severity text NOT NULL DEFAULT 'medium', query text NOT NULL, source_ids jsonb NOT NULL DEFAULT '[]'::jsonb, tactic text NOT NULL DEFAULT '', technique text NOT NULL DEFAULT '', enabled_at timestamptz, owner text NOT NULL DEFAULT '', run_frequency_minutes integer NOT NULL DEFAULT 15, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS siem_rule_tests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL DEFAULT '', rule_id uuid NOT NULL, test_name text NOT NULL DEFAULT 'Detection test', sample_event jsonb NOT NULL DEFAULT '{}'::jsonb, expected_match boolean NOT NULL DEFAULT true, actual_match boolean, status text NOT NULL DEFAULT 'pending', tested_at timestamptz, failure_reason text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS siem_alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, rule_id uuid NOT NULL, source_id uuid, title text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'new', severity text NOT NULL DEFAULT 'medium', observed_at timestamptz NOT NULL, entity_type text NOT NULL DEFAULT '', entity_value text NOT NULL DEFAULT '', event_count integer NOT NULL DEFAULT 1, raw_event_ids jsonb NOT NULL DEFAULT '[]'::jsonb, assigned_to text NOT NULL DEFAULT '', closed_at timestamptz, close_reason text NOT NULL DEFAULT '', incident_id text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS siem_suppressions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, rule_id uuid NOT NULL, entity_type text NOT NULL DEFAULT '', entity_value text NOT NULL DEFAULT '', reason text NOT NULL, status text NOT NULL DEFAULT 'active', created_by text NOT NULL DEFAULT '', starts_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS siem_tunings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, rule_id uuid NOT NULL, summary text NOT NULL, before_query text NOT NULL DEFAULT '', after_query text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'proposed', proposed_by text NOT NULL DEFAULT '', approved_by text NOT NULL DEFAULT '', approved_at timestamptz, applied_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_siem_sources_tenant_status ON siem_log_sources (tenant_id, status, source_type);
CREATE INDEX IF NOT EXISTS idx_siem_rules_tenant_status ON siem_detection_rules (tenant_id, status, severity);
CREATE INDEX IF NOT EXISTS idx_siem_tests_rule_status ON siem_rule_tests (rule_id, status);
CREATE INDEX IF NOT EXISTS idx_siem_alerts_tenant_status ON siem_alerts (tenant_id, status, severity, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_siem_suppressions_rule_status ON siem_suppressions (rule_id, status, expires_at);
CREATE INDEX IF NOT EXISTS idx_siem_tunings_rule_status ON siem_tunings (rule_id, status);
