-- Sprint 143 PostgreSQL migration: SOAR automation.
CREATE TABLE IF NOT EXISTS soar_playbooks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, code text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft', trigger_type text NOT NULL DEFAULT 'manual', owner text NOT NULL DEFAULT '', version text NOT NULL DEFAULT '1.0', max_runtime_seconds integer NOT NULL DEFAULT 900, requires_approval boolean NOT NULL DEFAULT false, tags jsonb NOT NULL DEFAULT '[]'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS soar_steps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL DEFAULT '', playbook_id uuid NOT NULL, name text NOT NULL, step_type text NOT NULL DEFAULT 'action', sequence integer NOT NULL DEFAULT 1, connector_id uuid, action_name text NOT NULL DEFAULT '', condition jsonb NOT NULL DEFAULT '{}'::jsonb, parameters jsonb NOT NULL DEFAULT '{}'::jsonb, rollback_step_id uuid, stop_on_failure boolean NOT NULL DEFAULT true, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS soar_connectors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, code text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'active', connector_type text NOT NULL DEFAULT 'custom', base_url text NOT NULL DEFAULT '', auth_mode text NOT NULL DEFAULT 'none', allowed_actions jsonb NOT NULL DEFAULT '[]'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS soar_cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, case_number text NOT NULL, title text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'open', severity text NOT NULL DEFAULT 'medium', source_type text NOT NULL DEFAULT '', source_id text NOT NULL DEFAULT '', owner text NOT NULL DEFAULT '', opened_at timestamptz NOT NULL, closed_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS soar_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, playbook_id uuid NOT NULL, case_id uuid, status text NOT NULL DEFAULT 'queued', requested_by text NOT NULL DEFAULT '', input jsonb NOT NULL DEFAULT '{}'::jsonb, output jsonb NOT NULL DEFAULT '{}'::jsonb, queued_at timestamptz NOT NULL, started_at timestamptz, completed_at timestamptz, failed_at timestamptz, failure_reason text NOT NULL DEFAULT '', current_step_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS soar_approvals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL DEFAULT '', run_id uuid NOT NULL, step_id uuid, approver_id text NOT NULL, approver_name text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'pending', requested_at timestamptz NOT NULL, responded_at timestamptz, comments text NOT NULL DEFAULT '', expires_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS soar_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL DEFAULT '', run_id uuid NOT NULL, step_id uuid, level text NOT NULL DEFAULT 'info', message text NOT NULL DEFAULT '', payload jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX IF NOT EXISTS idx_soar_playbooks_tenant_status ON soar_playbooks (tenant_id, status, trigger_type);CREATE INDEX IF NOT EXISTS idx_soar_steps_playbook_sequence ON soar_steps (playbook_id, sequence);CREATE INDEX IF NOT EXISTS idx_soar_connectors_tenant_status ON soar_connectors (tenant_id, status);CREATE INDEX IF NOT EXISTS idx_soar_cases_tenant_status ON soar_cases (tenant_id, status, severity);CREATE INDEX IF NOT EXISTS idx_soar_runs_tenant_status ON soar_runs (tenant_id, status, queued_at DESC);CREATE INDEX IF NOT EXISTS idx_soar_approvals_run_status ON soar_approvals (run_id, status, expires_at);CREATE INDEX IF NOT EXISTS idx_soar_logs_run_created ON soar_logs (run_id, created_at);
