-- Sprint 144 PostgreSQL migration: governance dashboards and executive reporting.
CREATE TABLE IF NOT EXISTS reporting_kpis (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, code text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft', domain text NOT NULL DEFAULT 'governance', direction text NOT NULL DEFAULT 'lower_is_better', target_value numeric(18,4), warning_value numeric(18,4), critical_value numeric(18,4), unit text NOT NULL DEFAULT 'count', query_key text NOT NULL DEFAULT '', owner text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reporting_dashboards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, code text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft', audience text NOT NULL DEFAULT 'executive', owner text NOT NULL DEFAULT '', published_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reporting_widgets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL DEFAULT '', dashboard_id uuid NOT NULL, kpi_id uuid, title text NOT NULL, widget_type text NOT NULL DEFAULT 'number', position jsonb NOT NULL DEFAULT '{}'::jsonb, config jsonb NOT NULL DEFAULT '{}'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reporting_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, code text NOT NULL, name text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft', audience text NOT NULL DEFAULT 'executive', sections jsonb NOT NULL DEFAULT '[]'::jsonb, owner text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reporting_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, template_id uuid NOT NULL, status text NOT NULL DEFAULT 'queued', period_start text NOT NULL DEFAULT '', period_end text NOT NULL DEFAULT '', generated_at timestamptz, generated_by text NOT NULL DEFAULT '', data jsonb NOT NULL DEFAULT '{}'::jsonb, summary text NOT NULL DEFAULT '', failure_reason text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reporting_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, template_id uuid NOT NULL, snapshot_id uuid, status text NOT NULL DEFAULT 'scheduled', recipients jsonb NOT NULL DEFAULT '[]'::jsonb, channel text NOT NULL DEFAULT 'email', scheduled_at timestamptz NOT NULL, sent_at timestamptz, failure_reason text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reporting_exports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id text NOT NULL, dashboard_id uuid, template_id uuid, snapshot_id uuid, status text NOT NULL DEFAULT 'queued', format text NOT NULL DEFAULT 'csv', requested_by text NOT NULL DEFAULT '', requested_at timestamptz NOT NULL, started_at timestamptz, completed_at timestamptz, file_url text NOT NULL DEFAULT '', failure_reason text NOT NULL DEFAULT '', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_reporting_kpis_tenant_status ON reporting_kpis (tenant_id, status, domain);
CREATE INDEX IF NOT EXISTS idx_reporting_dashboards_tenant_status ON reporting_dashboards (tenant_id, status, audience);
CREATE INDEX IF NOT EXISTS idx_reporting_widgets_dashboard ON reporting_widgets (dashboard_id, widget_type);
CREATE INDEX IF NOT EXISTS idx_reporting_templates_tenant_status ON reporting_templates (tenant_id, status, audience);
CREATE INDEX IF NOT EXISTS idx_reporting_snapshots_template_status ON reporting_snapshots (template_id, status, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_reporting_deliveries_template_status ON reporting_deliveries (template_id, status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_reporting_exports_tenant_status ON reporting_exports (tenant_id, status, requested_at DESC);
