CREATE TABLE IF NOT EXISTS service_marketplace_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text NOT NULL UNIQUE,name text NOT NULL,item_type text NOT NULL CHECK(item_type IN('service_pack','connector','theme','extension')),category text NOT NULL,description text NOT NULL DEFAULT '',provider text NOT NULL DEFAULT 'ServicePro',industries jsonb NOT NULL DEFAULT '["all"]'::jsonb,features jsonb NOT NULL DEFAULT '[]'::jsonb,accent_color text NOT NULL DEFAULT '#1c7c68',status text NOT NULL DEFAULT 'published',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS service_marketplace_installations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id text NOT NULL,item_id uuid NOT NULL REFERENCES service_marketplace_items(id) ON DELETE CASCADE,status text NOT NULL DEFAULT 'active',configuration jsonb NOT NULL DEFAULT '{}'::jsonb,installed_by text NOT NULL DEFAULT '',installed_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,item_id));
CREATE INDEX IF NOT EXISTS idx_service_marketplace_installations_tenant ON service_marketplace_installations(tenant_id,status,installed_at DESC);
INSERT INTO service_marketplace_items(code,name,item_type,category,description,industries,features,accent_color) VALUES
('pack-plumbing','Plumbing Operations Pack','service_pack','industry','Pricebook categories, equipment types, checklists, and job templates for residential and commercial plumbing.','["plumbing"]','["Drain and sewer","Water heaters","Fixture service"]','#247d70'),
('pack-hvac','HVAC Service Pack','service_pack','industry','Maintenance plans, diagnostic checklists, equipment lifecycle fields, and seasonal service templates.','["hvac"]','["Heating and cooling","Maintenance agreements","Equipment commissioning"]','#3c7ec4'),
('pack-carpet','Carpet & Upholstery Pack','service_pack','industry','Room measurements, treatment notes, material tracking, and repeat-cleaning workflows.','["carpet_cleaning"]','["Room-based estimates","Treatment tracking","Recurring service"]','#9b6f4f'),
('pack-landscape','Landscaping Operations Pack','service_pack','industry','Property zones, crew visits, seasonal services, and material usage for lawn and landscape teams.','["landscaping"]','["Property zones","Crew routing","Seasonal work"]','#56843f'),
('connector-accounting','Accounting Connector','connector','finance','Synchronize customers, invoices, payments, and tax-ready summaries with your accounting platform.','["all"]','["Invoice sync","Payment matching","Customer sync"]','#7256a1'),
('connector-payments','Payments Connector','connector','payments','Accept cards and bank payments while keeping ServicePro invoice balances current.','["all"]','["Card payments","Bank payments","Automatic reconciliation"]','#315ea8'),
('theme-evergreen','Evergreen Workspace Theme','theme','appearance','A calm, high-contrast workspace theme designed for field-service offices and mobile crews.','["all"]','["Accessible contrast","Office and field views","Light and dark modes"]','#1c7c68'),
('extension-communications','Customer Communications','extension','customer_experience','Reusable appointment, arrival, estimate, invoice, and follow-up messages for any service business.','["all"]','["Appointment reminders","On-my-way alerts","Review requests"]','#c77a2e') ON CONFLICT(code) DO NOTHING;
