const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const required = ['apps/web/package.json','apps/web/next.config.mjs','apps/web/src/app/layout.tsx','apps/web/src/app/page.tsx','apps/web/src/app/login/page.tsx','apps/web/src/app/dashboard/page.tsx','apps/web/src/components/AppShell.tsx','apps/web/src/app/globals.css','apps/web/render.yaml','apps/web/public/_headers'];
for (const relativePath of required) assert.ok(fs.existsSync(path.join(root, relativePath)), `missing ${relativePath}`);
const webPackage = JSON.parse(fs.readFileSync(path.join(root, 'apps/web/package.json'), 'utf8'));
assert.match(webPackage.dependencies.next, /^15\./, 'Sprint 716 must remain on Next.js 15');
assert.ok(webPackage.scripts['build:pages'], 'Cloudflare Pages build is required');
const home = fs.readFileSync(path.join(root, 'apps/web/src/app/page.tsx'), 'utf8');
const dashboard = fs.readFileSync(path.join(root, 'apps/web/src/app/dashboard/page.tsx'), 'utf8');
const appShell = fs.readFileSync(path.join(root, 'apps/web/src/components/AppShell.tsx'), 'utf8');
assert.match(home, /Field operations, finally in sync/);
assert.match(dashboard, /Operations overview/);
assert.match(appShell, /ThemeToggle/);
const config = fs.readFileSync(path.join(root, 'apps/web/next.config.mjs'), 'utf8');
assert.match(config, /standalone/);
assert.match(config, /export/);
console.log('Sprint 716 frontend foundation contract passed.');
