const fs = require('fs');
const required = ['apps/api/src/services/privacyCaseOrchestrationService.js','apps/api/src/repositories/privacyCaseOrchestrationRepository.js','apps/api/src/routes/privacyCaseOrchestration.js','packages/database/postgres/152_privacy_case_orchestration.sql','docs/sprint152-privacy-case-orchestration.md'];
for (const file of required) if (!fs.existsSync(file)) throw new Error(`Missing Sprint 152 file: ${file}`);
const svc = require('../apps/api/src/services/privacyCaseOrchestrationService');
let record = svc.normalizeCaseInput({ tenantId: 'tenant_demo', dsarId: 'dsar-1', jurisdiction: 'CCPA', receivedAt: '2026-01-01T00:00:00.000Z' });
if (record.dueAt !== '2026-02-15T00:00:00.000Z') process.exit(1);
record = svc.recordVerification(record, { method: 'email' }, '2026-01-02T00:00:00.000Z');
if (record.verificationStatus !== 'verified' || record.status !== 'in_progress') process.exit(1);
record = svc.extendDeadline(record, 15, 'complex request', '2026-01-03T00:00:00.000Z');
if (record.extensionDays !== 15 || record.dueAt !== '2026-03-02T00:00:00.000Z') process.exit(1);
const task = svc.completeTask(svc.normalizeTaskInput({ tenantId: 'tenant_demo', caseId: 'case-1', name: 'Export records' }), { files: 3 });
if (task.status !== 'completed' || task.evidence.files !== 3) process.exit(1);
const communication = svc.normalizeCommunicationInput({ tenantId: 'tenant_demo', caseId: 'case-1', type: 'extension_notice' });
const overdue = svc.normalizeCaseInput({ tenantId: 'tenant_demo', dsarId: 'dsar-2', dueAt: '2025-01-01T00:00:00.000Z' });
if (svc.escalationFor(overdue, '2026-01-01T00:00:00.000Z').level !== 'breach') process.exit(1);
const metrics = svc.orchestrationMetrics({ cases: [record, overdue], tasks: [task], communications: [communication] }, '2026-01-01T00:00:00.000Z');
if (metrics.openCases !== 2 || metrics.overdueCases !== 1 || metrics.completedTasks !== 1 || metrics.verifiedCases !== 1) process.exit(1);
if (svc.closeCase(record, 'fulfilled').status !== 'fulfilled') process.exit(1);
console.log('Sprint 152 privacy case orchestration test passed.');
