const assert=require('assert');const fs=require('fs');const http=require('http');const {runDeployedSmoke}=require('../scripts/smoke-deployed-app');
function start(handler){return new Promise(resolve=>{const server=http.createServer(handler);server.listen(0,'127.0.0.1',()=>resolve(server));});}
function send(res,status,body,headers={}){res.writeHead(status,{'content-type':'application/json',...headers});res.end(status===204?'':JSON.stringify(body));}
(async()=>{
  const web=await start((req,res)=>{res.writeHead(200,{'content-type':'text/html'});res.end(`<h1>${req.url}</h1>`);});const webUrl=`http://127.0.0.1:${web.address().port}`;
  const api=await start((req,res)=>{const cors={'access-control-allow-origin':webUrl};if(req.url==='/healthz')return send(res,200,{ok:true},cors);if(req.url==='/readyz')return send(res,200,{ready:true,checks:{configuration:true,runtime:true,dataStore:true}},cors);if(req.url==='/auth/login')return send(res,200,{data:{accessToken:'secret-test-token',user:{tenantId:'tenant_demo'}}},cors);if(req.url==='/api/v1/dashboard/summary')return send(res,200,{data:{kpis:{openWork:1}}},cors);if(req.url==='/auth/logout')return send(res,204,{},cors);send(res,404,{error:{message:'missing'}},cors);});const apiUrl=`http://127.0.0.1:${api.address().port}`;
  try{const result=await runDeployedSmoke({webUrl,apiUrl,email:'owner@example.com',password:'not-logged',requireAuth:true});assert.strictEqual(result.ok,true);assert.strictEqual(result.authenticated,true);assert.deepStrictEqual(result.checks,['website:/','website:/login','website:/system-status','api:health','api:cors','api:readiness','auth:login','auth:dashboard','auth:logout']);assert.ok(!JSON.stringify(result).includes('secret-test-token'));}
  finally{await Promise.all([new Promise(resolve=>web.close(resolve)),new Promise(resolve=>api.close(resolve))]);}
  const workflow=fs.readFileSync('.github/workflows/online-smoke.yml','utf8');assert.match(workflow,/workflow_dispatch/);assert.match(workflow,/secrets\.ONLINE_SMOKE_EMAIL/);assert.match(workflow,/secrets\.ONLINE_SMOKE_PASSWORD/);assert.ok(!fs.readFileSync('scripts/smoke-deployed-app.js','utf8').includes('ChangeMe123!'));
  console.log('Sprint 734 deployed smoke test passed.');
})().catch(error=>{console.error(error);process.exit(1);});
