const assert=require('assert');
const crypto=require('crypto');
process.env.DATA_STORE='json';
process.env.DATA_FILE='./data/test-subscriber-commerce-p0.json';
process.env.FEATURE_PAYMENTS_ENABLED='true';
process.env.STRIPE_SECRET_KEY='sk_test_subscriber_commerce';
const {resetRepositoriesForTest,getRepositories}=require('../apps/api/src/repositories/repositoryFactory');
const {createInvoicePayment,refundInvoicePayment}=require('../apps/api/src/services/customerPaymentService');
const {verifyWebhookSignature}=require('../apps/api/src/services/paymentService');
const {sendPaymentReceipt}=require('../apps/api/src/services/paymentReceiptService');
const { _test:paymentLinkTest }=require('../apps/api/src/routes/paymentLinks');
const {calculateSubscriberCommerceReadiness}=require('../apps/api/src/services/subscriberCommerceReadinessService');

(async()=>{
 resetRepositoriesForTest();const repos=getRepositories();repos.store.reset();
 assert.ok(repos.subscriberStripeAccounts&&repos.subscriberPaymentSettings&&repos.customerPaymentEvents,'commerce repositories must be registered');
 const defaults=await repos.subscriberPaymentSettings.get('tenant_demo');
 assert.strictEqual(defaults.acceptCustomerPayments,false,'existing subscribers default OFF');
 await repos.subscriberStripeAccounts.upsert('tenant_demo',{stripeAccountId:'acct_tenant_demo',status:'active',chargesEnabled:true,payoutsEnabled:true,detailsSubmitted:true});
 await repos.subscriberPaymentSettings.upsert('tenant_demo',{acceptCustomerPayments:true,partialPaymentsEnabled:true});
 const calls=[];global.fetch=async(url,options={})=>{calls.push({url,options});const path=String(url);if(path.includes('/payment_intents/pi_'))return{ok:true,status:200,json:async()=>({id:'pi_connected_1',client_secret:'secret_1'})};return{ok:true,status:200,json:async()=>({id:'pi_connected_1',client_secret:'secret_1'})};};
 const invoice=repos.invoices.findById('tenant_demo','inv_demo_1');
 const result=await createInvoicePayment(repos,'tenant_demo',{invoiceId:invoice.id,amountCents:Math.round(invoice.balanceDue*100),currency:'usd',idempotencyKey:'invoice-inv_demo_1-attempt-1'});
 assert.strictEqual(result.stripePaymentIntentId,'pi_connected_1');
 assert.strictEqual(calls[0].options.headers['Stripe-Account'],'acct_tenant_demo','subscriber funds must use connected account');
 assert.strictEqual(new URLSearchParams(calls[0].options.body).get('amount'),String(Math.round(invoice.balanceDue*100)),'server invoice balance is authoritative');
 const count=(await repos.payments.list('tenant_demo')).length;
 const duplicate=await createInvoicePayment(repos,'tenant_demo',{invoiceId:invoice.id,amountCents:Math.round(invoice.balanceDue*100),idempotencyKey:'invoice-inv_demo_1-attempt-1'});
 assert.strictEqual(duplicate.idempotent,true);assert.strictEqual((await repos.payments.list('tenant_demo')).length,count,'retry must not create another payment');
 const completed=repos.payments.completeStripePayment('tenant_demo',{eventId:'evt_connected_success',eventType:'payment_intent.succeeded',paymentIntentId:'pi_connected_1',connectedAccountId:'acct_tenant_demo',stripeChargeId:'ch_connected_1',amountReceived:Math.round(invoice.balanceDue*100),currency:'usd'});
 assert.strictEqual(completed.invoice.balanceDue,0);
 const receipt=await sendPaymentReceipt(repos,'tenant_demo',completed);
 assert.ok(['sent','skipped'].includes(receipt.status),'receipt delivery outcome is recorded independently');
 assert.strictEqual((await sendPaymentReceipt(repos,'tenant_demo',completed)).id,receipt.id,'duplicate success does not duplicate receipt delivery');
 global.fetch=async(url,options={})=>{calls.push({url,options});return{ok:true,status:200,json:async()=>({id:'re_connected_1',status:'succeeded'})};};
 const refunded=await refundInvoicePayment(repos,'tenant_demo',result.paymentId,{amountCents:100,idempotencyKey:'refund-connected-1',reason:'requested_by_customer'});
 assert.strictEqual(refunded.amountCents,100);assert.strictEqual(refunded.reconciliation,'webhook_pending');assert.strictEqual(calls.at(-1).options.headers['Stripe-Account'],'acct_tenant_demo');
 assert.strictEqual(repos.invoices.findById('tenant_demo',invoice.id).balanceDue,0,'refund request must not change invoice before webhook');
 const refundApplied=repos.payments.applyRefund('tenant_demo',result.paymentId,{eventId:'evt_connected_refund',paymentIntentId:'pi_connected_1',amountCents:100,stripeRefundId:'re_connected_1',reason:'requested_by_customer'});
 assert.strictEqual(refundApplied.invoice.balanceDue,1,'signed refund reconciliation changes the invoice once');
 assert.strictEqual(repos.payments.applyRefund('tenant_demo',result.paymentId,{eventId:'evt_connected_refund',paymentIntentId:'pi_connected_1',amountCents:100,stripeRefundId:'re_connected_1'}).duplicate,true,'duplicate refund event is harmless');
 const failedPayment=repos.payments.create('tenant_demo',{invoiceId:invoice.id,customerId:invoice.customerId,amount:1,amountCents:100,currency:'usd',status:'pending',stripePaymentIntentId:'pi_failed_1',stripeConnectedAccountId:'acct_tenant_demo'});
 assert.strictEqual(repos.payments.failStripePayment('tenant_demo',{eventId:'evt_failed_1',eventType:'payment_intent.payment_failed',paymentIntentId:'pi_failed_1',failureReason:'declined'}).payment.status,'failed');
 assert.strictEqual(repos.payments.failStripePayment('tenant_demo',{eventId:'evt_failed_1',eventType:'payment_intent.payment_failed',paymentIntentId:'pi_failed_1'}).duplicate,true);
 assert.ok(failedPayment.id);
 const linkToken='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-';
 repos.invoices.setPaymentLink('tenant_demo',invoice.id,paymentLinkTest.hash(linkToken),new Date(Date.now()+60000).toISOString());
 assert.strictEqual((await paymentLinkTest.resolve(linkToken)).id,invoice.id,'opaque payment link resolves only to its bound invoice');
 assert.strictEqual(await paymentLinkTest.resolve(`${linkToken}tampered`),null,'tampered payment link is rejected');
 repos.invoices.setPaymentLink('tenant_demo',invoice.id,paymentLinkTest.hash(linkToken),new Date(Date.now()-1000).toISOString());
 assert.strictEqual(await paymentLinkTest.resolve(linkToken),null,'expired payment link is rejected');
 assert.strictEqual((await repos.expressService.getSettings('tenant_demo')).enabled,false,'Express Service defaults OFF');
 const service=(await repos.services.list('tenant_demo'))[0];assert.ok(service,'fixture must include a service');
 await repos.expressService.saveSettings('tenant_demo',{enabled:true,eligibleServiceIds:[service.id],serviceAreaIds:['area_demo'],requirePhotos:false,requireDescription:true,depositRequired:false,depositAmountCents:0,paymentRequired:false,emergencyEnabled:false,afterHoursEnabled:false,notificationsEnabled:true,autoAssign:false});
 const expressRequest=await repos.expressService.createRequest('tenant_demo',{customerId:invoice.customerId,serviceId:service.id,description:'No cooling',urgency:'urgent'}),conversion=await repos.expressService.convertRequest('tenant_demo',expressRequest.id),conversionRetry=await repos.expressService.convertRequest('tenant_demo',expressRequest.id);
 assert.ok(conversion.job.id&&conversion.invoice.id,'Express request converts to traceable job and invoice');assert.strictEqual(conversionRetry.idempotent,true);assert.strictEqual(conversionRetry.job.id,conversion.job.id,'conversion retry cannot duplicate job');assert.strictEqual(await repos.expressService.convertRequest('tenant_other',expressRequest.id),null,'cross-tenant Express conversion is rejected');
 const readiness=await calculateSubscriberCommerceReadiness(repos,'tenant_demo');assert.ok(Array.isArray(readiness.items));assert.strictEqual(readiness.blockers.some(x=>x.key==='express_services'),false);
 await assert.rejects(()=>refundInvoicePayment(repos,'tenant_demo',result.paymentId,{amountCents:Math.round(invoice.total*100)+1,idempotencyKey:'refund-too-large'}),e=>e.code==='invalid_refund_amount');
 await assert.rejects(()=>createInvoicePayment(repos,'tenant_demo',{invoiceId:invoice.id,amountCents:Math.round(invoice.balanceDue*100)+1,idempotencyKey:'invoice-inv_demo_1-attempt-2'}),e=>e.code==='invalid_payment_amount');
 await repos.subscriberPaymentSettings.upsert('tenant_demo',{acceptCustomerPayments:false});
 await assert.rejects(()=>createInvoicePayment(repos,'tenant_demo',{invoiceId:invoice.id,idempotencyKey:'invoice-inv_demo_1-attempt-3'}),e=>e.code==='customer_payments_disabled');
 const timestamp=1800000000,payload=JSON.stringify({id:'evt_connect',account:'acct_tenant_demo'}),secret='whsec_connect';
 const one=crypto.createHmac('sha256',secret).update(`${timestamp}.${payload}`).digest('hex');
 assert.deepStrictEqual(verifyWebhookSignature(payload,`t=${timestamp},v1=bad,v1=${one}`,timestamp,secret),JSON.parse(payload),'any valid v1 signature is accepted');
 assert.strictEqual(verifyWebhookSignature(payload,`t=${timestamp},v1=${one}`,timestamp+301,secret),null,'old webhook rejected');
 console.log('Subscriber commerce P0 tests passed.');
})().catch(error=>{console.error(error);process.exit(1);});
