'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
type Settings={acceptCustomerPayments:boolean;defaultCurrency:string;acceptedMethods:string[];depositsEnabled:boolean;partialPaymentsEnabled:boolean;automaticReceipts:boolean;paymentReminders:boolean;stripeAccount:null|{status:string;chargesEnabled:boolean;payoutsEnabled:boolean;detailsSubmitted:boolean;defaultCurrency:string}};
const empty:Settings={acceptCustomerPayments:false,defaultCurrency:'usd',acceptedMethods:['card'],depositsEnabled:false,partialPaymentsEnabled:true,automaticReceipts:true,paymentReminders:false,stripeAccount:null};
export function CustomerPaymentsSettings(){const[settings,setSettings]=useState<Settings>(empty),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{api<Settings>('GET','/api/v1/settings/billing/customer-payments').then(r=>{if(r.data)setSettings(r.data);else setMessage(r.error?.message||'Unable to load payment settings.');});},[]);
 const save=async()=>{setBusy('save');setMessage('');const r=await api<Settings>('PATCH','/api/v1/settings/billing/customer-payments',settings);if(r.data){setSettings(r.data);setMessage('Customer payment settings saved.');}else setMessage(r.error?.message||'Unable to save settings.');setBusy('');};
 const connect=async()=>{setBusy('connect');const origin=window.location.origin,returnUrl=`${origin}/settings/customer-payments?stripe=returned`,refreshUrl=`${origin}/settings/customer-payments?stripe=refresh`;const path=settings.stripeAccount?'/api/v1/stripe/connect/refresh-link':'/api/v1/stripe/connect/onboard';const r=await api<{accountLinkUrl:string}>('POST',path,{returnUrl,refreshUrl});if(r.data?.accountLinkUrl)window.location.assign(r.data.accountLinkUrl);else{setMessage(r.error?.message||'Unable to start Stripe onboarding.');setBusy('');}};
 const active=Boolean(settings.stripeAccount?.chargesEnabled&&settings.stripeAccount.status==='active');
 return <div className="settings-payment-layout"><section className="panel"><h2>Stripe account</h2><p>Payments from your customers are processed through your connected Stripe account and paid to your business. ServicePRO subscription fees are paid separately to Aardvark Enterprises.</p><dl><div><dt>Status</dt><dd>{settings.stripeAccount?.status||'Not connected'}</dd></div><div><dt>Charges</dt><dd>{settings.stripeAccount?.chargesEnabled?'Enabled':'Unavailable'}</dd></div><div><dt>Payouts</dt><dd>{settings.stripeAccount?.payoutsEnabled?'Enabled':'Unavailable'}</dd></div></dl><button className="button" type="button" onClick={connect} disabled={Boolean(busy)}>{busy==='connect'?'Opening Stripe…':settings.stripeAccount?'Continue Stripe setup':'Connect Stripe'}</button></section><section className="panel"><h2>Customer payment options</h2>{message&&<p role="status">{message}</p>}<label><input type="checkbox" checked={settings.acceptCustomerPayments} disabled={!active} onChange={e=>setSettings({...settings,acceptCustomerPayments:e.target.checked})}/> Accept Customer Payments</label>{!active&&<p>Complete Stripe onboarding and enable charges before turning on customer payments.</p>}<label>Default currency <select value={settings.defaultCurrency} onChange={e=>setSettings({...settings,defaultCurrency:e.target.value})}><option value="usd">USD</option><option value="cad">CAD</option></select></label><label><input type="checkbox" checked={settings.partialPaymentsEnabled} onChange={e=>setSettings({...settings,partialPaymentsEnabled:e.target.checked})}/> Allow partial payments</label><label><input type="checkbox" checked={settings.depositsEnabled} onChange={e=>setSettings({...settings,depositsEnabled:e.target.checked})}/> Allow deposits</label><label><input type="checkbox" checked={settings.automaticReceipts} onChange={e=>setSettings({...settings,automaticReceipts:e.target.checked})}/> Send automatic receipts after verified payment</label><p><strong>Payment method:</strong> Cards. Bank payments, wallets, saved methods, tips, convenience fees, progress payments, and automated reminders are not yet available.</p><label><input type="checkbox" checked={false} disabled/> Payment reminders (not available)</label><button className="button" type="button" onClick={save} disabled={Boolean(busy)}>{busy==='save'?'Saving…':'Save payment settings'}</button></section></div>}
