'use client';
import {useMemo,useState} from 'react';
type Kind='guide'|'tutorial'|'api'|'release';type Department='platform'|'ownership'|'operations'|'dispatch'|'customer_service'|'finance'|'inventory_assets'|'people'|'engineering'|'product';type Entry={id:string;department:Department;kind:Kind;category:string;title:string;summary:string;minutes:number;sections:{heading:string;body:string;steps?:string[];code?:string}[]};
const departmentLabels:Record<Department|string,string>={all:'All departments',platform:'Platform administration',ownership:'Business ownership',operations:'Operations',dispatch:'Dispatch & scheduling',customer_service:'Customer service',finance:'Billing & finance',inventory_assets:'Inventory & assets',people:'People & teams',engineering:'API & engineering',product:'Product updates'};const kindLabels:Record<Kind|string,string>={all:'All content',guide:'Guides',tutorial:'Tutorials',api:'API reference',release:'Release notes'};
const docs:Entry[]=[
{id:'platform-control',department:'platform',kind:'guide',category:'Control plane',title:'Provision a service-company tenant',summary:'Create an owner, choose the company site type, enable modules, and control timed access.',minutes:8,sections:[{heading:'Administrator workflow',body:'Only allowlisted platform administrators can perform these actions.',steps:['Open Platform admin.','Create the business owner and temporary login.','Select one Marketplace service-company site type.','Enable the purchased business modules.','Issue the owner activation token and choose its lifetime.','Extend, suspend, or revoke access when required.']}]},
{id:'owner-start',department:'ownership',kind:'guide',category:'Workspace setup',title:'Start operating your business workspace',summary:'Configure the tenant without changing platform-controlled entitlements.',minutes:6,sections:[{heading:'Owner boundary',body:'Owners manage their company, locations, workflows, and employees. Marketplace site type, available modules, owner accounts, and subscription access remain controlled by platform administrators.'}]},
{id:'daily-work',department:'operations',kind:'guide',category:'Daily operations',title:'Run the daily service board',summary:'Review open work, priorities, exceptions, and completion status.',minutes:6,sections:[{heading:'Daily rhythm',body:'Start with Overview, review unassigned and urgent work, confirm resources, and close completed work with materials and notes recorded.'}]},
{id:'dispatch-work',department:'dispatch',kind:'tutorial',category:'Scheduling',title:'Create and dispatch a work order',summary:'Move a customer request into a conflict-free technician appointment.',minutes:9,sections:[{heading:'Dispatch steps',body:'Complete these steps in order.',steps:['Select the customer and service location.','Create the work order and priority.','Choose an appointment window.','Assign a qualified technician.','Check the schedule for conflicts.','Send confirmation to the customer.']}]},
{id:'customer-care',department:'customer_service',kind:'guide',category:'Customer lifecycle',title:'Manage customer communication',summary:'Keep contact records, service history, reminders, and follow-up accurate.',minutes:5,sections:[{heading:'Customer care',body:'Use Customers as the system of record and Notifications for approved appointment, estimate, invoice, and follow-up communication.'}]},
{id:'finance-reporting',department:'finance',kind:'tutorial',category:'Reporting',title:'Invoice, collect, and schedule reports',summary:'Maintain financial visibility without exposing unrelated administration.',minutes:7,sections:[{heading:'Finance workflow',body:'Verify approved work, issue the invoice, record payments, review balances, and schedule recurring reports for approved recipients.'}]},
{id:'asset-stock',department:'inventory_assets',kind:'guide',category:'Resources',title:'Manage assets, parts, and materials',summary:'Track customer equipment and the materials used to service it.',minutes:6,sections:[{heading:'Accurate records',body:'Record model and serial details, service history, stock adjustments, material usage, and reorder thresholds in the appropriate module.'}]},
{id:'team-access',department:'people',kind:'guide',category:'Access delegation',title:'Manage the owner team',summary:'Create employee accounts and delegate only platform-enabled modules.',minutes:7,sections:[{heading:'Least-privilege setup',body:'Owners use Team management to add staff and assign tenant roles.',steps:['Create the employee with a temporary password.','Choose admin, manager, technician, billing, or read-only.','Select only the modules required for the job.','Review access when responsibilities change.','Never share owner or platform-administrator credentials.']}]},
{id:'api-basics',department:'engineering',kind:'api',category:'Authentication',title:'Call the ServicePro API',summary:'Use tenant-aware bearer authentication and JSON response envelopes.',minutes:7,sections:[{heading:'Authenticated request',body:'The server enforces identity, tenant, module, and role boundaries.',code:'GET /api/v1/dashboard/summary\nAuthorization: Bearer <access-token>\nX-Tenant-Id: tenant_demo'}]},
{id:'release-control-plane',department:'product',kind:'release',category:'Version 8',title:'Administration and RBAC release',summary:'Platform-controlled tenants, site types, modules, timed owner access, and owner-managed teams.',minutes:3,sections:[{heading:'Highlights',body:'Introduced permanent platform administration with tenant-scoped owner and employee access controls.'}]}
];
export function DocumentationWorkspace(){const[department,setDepartment]=useState<Department|'all'>('all'),[kind,setKind]=useState<Kind|'all'>('all'),[query,setQuery]=useState(''),[selectedId,setSelectedId]=useState('platform-control'),[copied,setCopied]=useState('');const visible=useMemo(()=>docs.filter(doc=>(department==='all'||doc.department===department)&&(kind==='all'||doc.kind===kind)&&JSON.stringify(doc).toLowerCase().includes(query.toLowerCase())),[department,kind,query]);const selected=visible.find(doc=>doc.id===selectedId)||visible[0];async function copy(value:string,key:string){await navigator.clipboard.writeText(value);setCopied(key);setTimeout(()=>setCopied(''),1500)}return <section className="docs-workspace"><div className="docs-hero"><div><span>Departmental knowledge center</span><h2>Guidance for every ServicePro responsibility.</h2><p>Choose a department, then narrow by guide, tutorial, API reference, or release note.</p></div><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search departmental documentation"/></label></div><div className="docs-departments">{Object.entries(departmentLabels).map(([value,label])=><button key={value} className={department===value?'active':''} onClick={()=>setDepartment(value as Department|'all')}>{label}<span>{value==='all'?docs.length:docs.filter(doc=>doc.department===value).length}</span></button>)}</div><div className="docs-tabs">{Object.entries(kindLabels).map(([value,label])=><button key={value} className={kind===value?'active':''} onClick={()=>setKind(value as Kind|'all')}>{label}</button>)}</div><div className="docs-layout"><aside className="docs-index"><p>{visible.length} articles</p>{visible.map(doc=><button key={doc.id} className={selected?.id===doc.id?'active':''} onClick={()=>setSelectedId(doc.id)}><span>{departmentLabels[doc.department]}</span><strong>{doc.title}</strong><small>{kindLabels[doc.kind]} · {doc.minutes} min</small></button>)}</aside><article className="docs-article">{selected&&<><header><span>{departmentLabels[selected.department]} · {selected.category}</span><h2>{selected.title}</h2><p>{selected.summary}</p></header>{selected.sections.map((section,index)=><section key={section.heading}><h3>{section.heading}</h3><p>{section.body}</p>{section.steps&&<ol>{section.steps.map(step=><li key={step}>{step}</li>)}</ol>}{section.code&&<div className="docs-code"><button onClick={()=>void copy(section.code!,`${selected.id}-${index}`)}>{copied===`${selected.id}-${index}`?'Copied':'Copy'}</button><pre><code>{section.code}</code></pre></div>}</section>)}</>}</article></div></section>}
