'use client';

import { type FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { authFetch, clearSession, updateSessionUser } from '@/auth/session';

type Preferences = { email:boolean;push:boolean;dispatch:boolean;billing:boolean;product:boolean };
type Profile = { id:string;tenantId:string;email:string;name:string;avatarUrl:string;timezone:string;locale:string;roles:string[];mfaEnabled:boolean;notificationPreferences:Preferences };
type ApiToken = { id:string;name:string;lastFour:string;createdAt:string;lastUsedAt?:string|null;expiresAt?:string|null };

async function jsonRequest(path:string,init:RequestInit={}) { const response=await authFetch(path,init); const body=response.status===204?{}:await response.json(); if(!response.ok) throw new Error(body.error?.message || 'Request failed'); return body.data; }

export function ProfileWorkspace() {
  const router=useRouter(); const [profile,setProfile]=useState<Profile|null>(null); const [tokens,setTokens]=useState<ApiToken[]>([]); const [busy,setBusy]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [createdToken,setCreatedToken]=useState('');
  useEffect(()=>{ Promise.all([jsonRequest('/api/v1/profile'),jsonRequest('/api/v1/profile/tokens')]).then(([user,rows])=>{setProfile(user);setTokens(rows);}).catch(problem=>setError(problem instanceof Error?problem.message:'Profile unavailable')); },[]);
  function start(action:string){setBusy(action);setMessage('');setError('');}
  function failed(problem:unknown){setError(problem instanceof Error?problem.message:'Request failed');setBusy('');}
  async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!profile)return;start('profile');try{const updated=await jsonRequest('/api/v1/profile',{method:'PATCH',body:JSON.stringify({name:profile.name,avatarUrl:profile.avatarUrl,timezone:profile.timezone,locale:profile.locale,notificationPreferences:profile.notificationPreferences})});setProfile(updated);updateSessionUser({name:updated.name});setMessage('Profile preferences saved.');setBusy('');}catch(problem){failed(problem);}}
  async function toggleMfa(){if(!profile)return;start('mfa');try{const data=await jsonRequest('/api/v1/profile/mfa',{method:'PATCH',body:JSON.stringify({enabled:!profile.mfaEnabled})});setProfile({...profile,mfaEnabled:data.mfaEnabled});setMessage(data.mfaEnabled?'Email verification is required at your next sign-in.':'Multi-factor verification disabled.');setBusy('');}catch(problem){failed(problem);}}
  async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);start('password');try{await jsonRequest('/api/v1/profile/password',{method:'POST',body:JSON.stringify({currentPassword:form.get('currentPassword'),newPassword:form.get('newPassword')})});clearSession();router.replace('/login');}catch(problem){failed(problem);}}
  async function createToken(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);start('token');try{const data=await jsonRequest('/api/v1/profile/tokens',{method:'POST',body:JSON.stringify({name:form.get('name')})});setCreatedToken(data.token);setTokens([{id:data.id,name:data.name,lastFour:data.lastFour,createdAt:data.createdAt,lastUsedAt:data.lastUsedAt,expiresAt:data.expiresAt},...tokens]);event.currentTarget.reset();setMessage('API token created. Copy it now; it will not be shown again.');setBusy('');}catch(problem){failed(problem);}}
  async function revokeToken(id:string){start(`revoke-${id}`);try{await jsonRequest(`/api/v1/profile/tokens/${id}`,{method:'DELETE'});setTokens(tokens.filter(row=>row.id!==id));setMessage('API token revoked.');setBusy('');}catch(problem){failed(problem);}}
  if(!profile)return <section className="dashboard-loading" aria-live="polite">{error||'Loading your profile…'}</section>;
  const initial=(profile.name||profile.email).split(/\s|@/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join('');
  return <div className="profile-grid">{error&&<p className="form-error profile-notice" role="alert">{error}</p>}{message&&<p className="form-success profile-notice" role="status">{message}</p>}
    <section className="panel profile-main"><div className="panel-heading"><div><h2>Personal details</h2><p>Shown across your ServicePro workspace.</p></div></div><form onSubmit={saveProfile}><div className="avatar-editor"><span style={profile.avatarUrl?{backgroundImage:`url(${profile.avatarUrl})`}:undefined}>{profile.avatarUrl?'':initial}</span><div><strong>{profile.name||'Your profile'}</strong><small>{profile.email}</small></div></div><label>Full name<input value={profile.name} onChange={event=>setProfile({...profile,name:event.target.value})} required /></label><label>Avatar image URL<input value={profile.avatarUrl} onChange={event=>setProfile({...profile,avatarUrl:event.target.value})} placeholder="https://…" type="url" /></label><div className="form-columns"><label>Timezone<select value={profile.timezone} onChange={event=>setProfile({...profile,timezone:event.target.value})}><option value="America/Indiana/Indianapolis">Eastern — Indianapolis</option><option value="America/Chicago">Central</option><option value="America/Denver">Mountain</option><option value="America/Los_Angeles">Pacific</option><option value="UTC">UTC</option></select></label><label>Language<select value={profile.locale} onChange={event=>setProfile({...profile,locale:event.target.value})}><option value="en-US">English (US)</option><option value="en-CA">English (Canada)</option><option value="es-US">Spanish (US)</option></select></label></div><button className="button button-small" disabled={busy==='profile'} type="submit">{busy==='profile'?'Saving…':'Save profile'}</button></form></section>
    <aside className="profile-side"><section className="panel"><div className="panel-heading"><div><h2>Multi-factor authentication</h2><p>Email verification challenges at sign-in.</p></div></div><div className="security-setting"><span><strong>{profile.mfaEnabled?'Enabled':'Not enabled'}</strong><small>{profile.mfaEnabled?'Your account has an extra verification step.':'Add protection beyond your password.'}</small></span><button className="button button-small" disabled={busy==='mfa'} type="button" onClick={toggleMfa}>{profile.mfaEnabled?'Disable':'Enable MFA'}</button></div></section>
    <section className="panel"><div className="panel-heading"><div><h2>Notifications</h2><p>Choose what reaches you.</p></div></div><div className="preference-list">{([['email','Email notifications'],['push','Browser notifications'],['dispatch','Dispatch changes'],['billing','Billing activity'],['product','Product updates']] as [keyof Preferences,string][]).map(([key,label])=><label key={key}><span>{label}</span><input type="checkbox" checked={profile.notificationPreferences[key]} onChange={event=>setProfile({...profile,notificationPreferences:{...profile.notificationPreferences,[key]:event.target.checked}})} /></label>)}</div><button className="button button-small" disabled={busy==='profile'} type="button" onClick={()=>document.querySelector<HTMLFormElement>('.profile-main form')?.requestSubmit()}>Save preferences</button></section></aside>
    <section className="panel profile-wide"><div className="panel-heading"><div><h2>Change password</h2><p>Changing your password signs out every active session.</p></div></div><form className="inline-security-form" onSubmit={changePassword}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required /></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={12} required /><small>12+ characters with uppercase, lowercase, number, and symbol.</small></label><button className="button button-small" disabled={busy==='password'} type="submit">Update password</button></form></section>
    <section className="panel profile-wide"><div className="panel-heading"><div><h2>API tokens</h2><p>Use scoped personal credentials for scripts and integrations.</p></div></div><form className="token-form" onSubmit={createToken}><label>Token name<input name="name" placeholder="Reporting integration" required /></label><button className="button button-small" disabled={busy==='token'} type="submit">Create token</button></form>{createdToken&&<div className="token-reveal"><code>{createdToken}</code><button type="button" onClick={()=>navigator.clipboard.writeText(createdToken)}>Copy</button></div>}<div className="token-list">{tokens.length?tokens.map(token=><article key={token.id}><span><strong>{token.name}</strong><small>Ends in {token.lastFour} · Created {new Date(token.createdAt).toLocaleDateString()}</small></span><button type="button" disabled={busy===`revoke-${token.id}`} onClick={()=>revokeToken(token.id)}>Revoke</button></article>):<p className="empty-state">No active API tokens.</p>}</div></section>
  </div>;
}
