"""Service categories and their OSM tag mappings."""

from typing import NamedTuple


class ServiceCategory(NamedTuple):
    name: str
    osm_tags: list[tuple[str, str]]  # (key, value) pairs for Overpass


CATEGORIES: dict[str, ServiceCategory] = {
    # === All 30 Marketplace Industry Packs ===
    "plumbing": ServiceCategory("Plumbing", [("craft", "plumber"), ("shop", "plumber"), ("office", "plumber"), ("service", "plumbing"), ("shop", "plumbing")]),
    "hvac": ServiceCategory("HVAC", [("craft", "hvac"), ("shop", "hvac"), ("craft", "heating_engineer"), ("office", "hvac"), ("service", "hvac"), ("service", "air_conditioning"), ("service", "heating"), ("shop", "heating")]),
    "electrical": ServiceCategory("Electrical", [("craft", "electrician"), ("shop", "electrical"), ("office", "electrician")]),
    "landscaping": ServiceCategory("Landscaping", [("craft", "gardener"), ("shop", "garden_centre"), ("office", "landscaping"), ("service", "landscaping")]),
    "carpet_cleaning": ServiceCategory("Carpet & Upholstery", [("craft", "carpet_cleaning"), ("shop", "carpet"), ("service", "carpet_cleaning")]),
    "residential_cleaning": ServiceCategory("Residential Cleaning", [("craft", "cleaning"), ("shop", "cleaning"), ("service", "cleaning"), ("office", "cleaning")]),
    "commercial_cleaning": ServiceCategory("Commercial Janitorial", [("office", "cleaning"), ("craft", "cleaning"), ("service", "janitorial")]),
    "pest_control": ServiceCategory("Pest Control", [("craft", "pest_control"), ("shop", "pest_control"), ("office", "pest_control")]),
    "roofing": ServiceCategory("Roofing", [("craft", "roofer"), ("shop", "roofing"), ("office", "roofing")]),
    "garage_door": ServiceCategory("Garage Door Service", [("craft", "garage_door"), ("shop", "garage"), ("service", "garage_door")]),
    "appliance_repair": ServiceCategory("Appliance Repair", [("craft", "appliance_repair"), ("shop", "appliance"), ("service", "appliance_repair")]),
    "handyman": ServiceCategory("Handyman", [("craft", "handyman"), ("service", "handyman")]),
    "painting": ServiceCategory("Painting", [("craft", "painter"), ("shop", "paint"), ("service", "painting")]),
    "pressure_washing": ServiceCategory("Pressure Washing", [("craft", "pressure_washing"), ("service", "pressure_washing")]),
    "pool_spa": ServiceCategory("Pool & Spa", [("craft", "pool_service"), ("shop", "pool"), ("service", "pool"), ("leisure", "swimming_pool")]),
    "locksmith_security": ServiceCategory("Locksmith & Security", [("craft", "locksmith"), ("shop", "locksmith"), ("office", "security")]),
    "tree_care": ServiceCategory("Tree Care", [("craft", "tree_service"), ("service", "tree_care"), ("shop", "tree")]),
    "snow_removal": ServiceCategory("Snow & Ice Management", [("craft", "snow_removal"), ("service", "snow_removal"), ("service", "winter_service")]),
    "irrigation": ServiceCategory("Irrigation", [("craft", "irrigation"), ("service", "irrigation"), ("shop", "irrigation")]),
    "septic": ServiceCategory("Septic & Wastewater", [("craft", "septic"), ("service", "septic"), ("office", "septic")]),
    "chimney_fireplace": ServiceCategory("Chimney & Fireplace", [("craft", "chimney_sweep"), ("service", "chimney"), ("shop", "fireplace")]),
    "solar": ServiceCategory("Solar", [("craft", "solar"), ("shop", "solar"), ("office", "solar"), ("service", "solar")]),
    "home_inspection": ServiceCategory("Home Inspection", [("office", "home_inspection"), ("service", "inspection"), ("craft", "inspector")]),
    "restoration": ServiceCategory("Restoration & Remediation", [("craft", "restoration"), ("service", "restoration"), ("office", "restoration")]),
    "moving": ServiceCategory("Moving Services", [("office", "moving_company"), ("craft", "mover"), ("service", "moving")]),
    "junk_removal": ServiceCategory("Junk Removal", [("craft", "junk_removal"), ("service", "junk_removal"), ("shop", "second_hand")]),
    "window_gutter": ServiceCategory("Window & Gutter Cleaning", [("craft", "window_cleaning"), ("service", "gutter_cleaning"), ("craft", "gutter")]),
    "flooring": ServiceCategory("Flooring", [("craft", "floorer"), ("shop", "flooring"), ("service", "flooring")]),
    "property_maintenance": ServiceCategory("Property Maintenance", [("craft", "property_maintenance"), ("office", "property_management"), ("service", "maintenance")]),
    "fencing": ServiceCategory("Fence & Gate", [("craft", "fencing"), ("shop", "fence"), ("service", "fencing")]),
    # === Additional common categories not in marketplace ===
    "auto_repair": ServiceCategory("Auto Repair", [("shop", "car_repair"), ("craft", "auto_repair"), ("service", "auto_repair")]),
    "oil_lube": ServiceCategory("Oil Change & Lube", [("shop", "car_repair"), ("shop", "oil_change"), ("service", "oil_change")]),
    "tire_service": ServiceCategory("Tire & Alignment", [("shop", "tyres"), ("shop", "car_repair"), ("service", "tire")]),
    "transmission": ServiceCategory("Transmission & Drivetrain", [("shop", "car_repair"), ("craft", "auto_repair"), ("service", "transmission")]),
    "auto_body": ServiceCategory("Auto Body & Collision", [("shop", "car_repair"), ("craft", "auto_body"), ("service", "collision")]),
    "auto_electrical": ServiceCategory("Auto Electrical & Diagnostics", [("shop", "car_repair"), ("craft", "auto_repair"), ("service", "diagnostics")]),
    "brake_suspension": ServiceCategory("Brake & Suspension", [("shop", "car_repair"), ("service", "brake"), ("service", "suspension")]),
    "exhaust_emissions": ServiceCategory("Exhaust & Emissions", [("shop", "car_repair"), ("service", "exhaust"), ("service", "emissions")]),
    "auto_detailing": ServiceCategory("Auto Detailing", [("shop", "car_wash"), ("craft", "auto_detailing"), ("service", "detailing")]),
    "mobile_mechanic": ServiceCategory("Mobile Mechanic", [("craft", "mechanic"), ("service", "mobile_mechanic"), ("craft", "auto_repair")]),
    "towing": ServiceCategory("Towing", [("craft", "towing"), ("shop", "towing"), ("service", "towing")]),
    "concrete": ServiceCategory("Concrete", [("craft", "concrete"), ("service", "concrete")]),
    "remodeling": ServiceCategory("Remodeling", [("craft", "carpenter"), ("craft", "builder"), ("office", "construction")]),
    # === 10 New Marketplace Industries (total 40) ===
    "concrete_masonry": ServiceCategory("Concrete & Masonry", [("craft", "concrete"), ("craft", "mason"), ("craft", "bricklayer"), ("service", "concrete"), ("shop", "masonry")]),
    "insulation": ServiceCategory("Insulation & Weatherization", [("craft", "insulation"), ("craft", "insulator"), ("service", "insulation"), ("service", "weatherization")]),
    "glass_mirror": ServiceCategory("Glass & Mirror", [("craft", "glazier"), ("shop", "glass"), ("service", "glazing"), ("craft", "glass")]),
    "elevator": ServiceCategory("Elevator & Escalator", [("craft", "elevator"), ("service", "elevator"), ("office", "elevator"), ("shop", "elevator")]),
    "fire_protection": ServiceCategory("Fire Protection", [("craft", "fire_protection"), ("service", "fire_protection"), ("shop", "fire_safety"), ("office", "fire_protection")]),
    "generator": ServiceCategory("Generator & Backup Power", [("craft", "generator"), ("service", "generator"), ("shop", "generator"), ("craft", "electrician")]),
    "well_water": ServiceCategory("Well & Water Treatment", [("craft", "well_drilling"), ("service", "water_treatment"), ("shop", "water_softener"), ("craft", "water_treatment")]),
    "paving": ServiceCategory("Paving & Sealcoating", [("craft", "paving"), ("service", "paving"), ("craft", "asphalt"), ("service", "sealcoating")]),
    "demolition": ServiceCategory("Demolition & Hauling", [("craft", "demolition"), ("service", "demolition"), ("office", "demolition"), ("service", "hauling")]),
    "dock_marine": ServiceCategory("Dock & Marine", [("craft", "dock_builder"), ("service", "marine"), ("shop", "boat_repair"), ("craft", "marine")]),
}

ALL_CATEGORY_NAMES = sorted(CATEGORIES.keys())

# U.S. state bounding boxes (approximate) for Overpass queries
US_STATE_BOUNDS: dict[str, tuple[float, float, float, float]] = {
    "AL": (30.22, -88.47, 35.01, -84.89),
    "AK": (51.21, -179.15, 71.39, -129.98),
    "AZ": (31.33, -114.82, 37.00, -109.04),
    "AR": (33.00, -94.62, 36.50, -89.64),
    "CA": (32.53, -124.48, 42.01, -114.13),
    "CO": (36.99, -109.06, 41.00, -102.04),
    "CT": (40.98, -73.73, 42.05, -71.79),
    "DE": (38.45, -75.79, 39.84, -75.05),
    "FL": (24.40, -87.63, 31.00, -80.03),
    "GA": (30.36, -85.61, 35.00, -80.84),
    "HI": (18.91, -160.24, 22.24, -154.81),
    "ID": (41.99, -117.24, 49.00, -111.04),
    "IL": (36.97, -91.51, 42.51, -87.02),
    "IN": (37.77, -88.10, 41.76, -84.78),
    "IA": (40.38, -96.64, 43.50, -90.14),
    "KS": (36.99, -102.05, 40.00, -94.59),
    "KY": (36.50, -89.57, 39.15, -81.96),
    "LA": (28.93, -94.04, 33.02, -89.00),
    "ME": (43.06, -71.08, 47.46, -66.95),
    "MD": (37.91, -79.49, 39.72, -75.05),
    "MA": (41.24, -73.50, 42.89, -69.93),
    "MI": (41.70, -90.42, 48.19, -82.12),
    "MN": (43.50, -97.24, 49.38, -89.49),
    "MS": (30.17, -91.66, 34.99, -88.10),
    "MO": (35.99, -95.77, 40.61, -89.10),
    "MT": (44.36, -116.05, 49.00, -104.04),
    "NE": (39.99, -104.05, 43.00, -95.31),
    "NV": (35.00, -120.01, 42.00, -114.04),
    "NH": (42.70, -72.56, 45.31, -70.70),
    "NJ": (38.93, -75.56, 41.36, -73.89),
    "NM": (31.33, -109.05, 37.00, -103.00),
    "NY": (40.50, -79.76, 45.02, -71.86),
    "NC": (33.84, -84.32, 36.59, -75.46),
    "ND": (45.93, -104.05, 49.00, -96.55),
    "OH": (38.40, -84.82, 42.33, -80.52),
    "OK": (33.62, -103.00, 37.00, -94.43),
    "OR": (41.99, -124.57, 46.29, -116.46),
    "PA": (39.72, -80.52, 42.27, -74.69),
    "RI": (41.15, -71.86, 42.02, -71.12),
    "SC": (32.05, -83.35, 35.22, -78.54),
    "SD": (42.48, -104.06, 45.95, -96.44),
    "TN": (34.98, -90.31, 36.68, -81.65),
    "TX": (25.84, -106.65, 36.50, -93.51),
    "UT": (36.99, -114.05, 42.00, -109.04),
    "VT": (42.73, -73.44, 45.02, -71.47),
    "VA": (36.54, -83.68, 39.47, -75.24),
    "WA": (45.54, -124.85, 49.00, -116.92),
    "WV": (37.20, -82.64, 40.64, -77.72),
    "WI": (42.49, -92.89, 47.31, -86.25),
    "WY": (40.99, -111.06, 45.01, -104.05),
    "DC": (38.79, -77.12, 38.99, -76.91),
}

ALL_STATES = sorted(US_STATE_BOUNDS.keys())
