const { validationError } = require('../errors/domainError');

const CLASSIFICATION_LEVELS = ['public', 'internal', 'confidential', 'restricted'];
const POLICY_STATUSES = ['draft', 'active', 'retired'];
const RETENTION_ACTIONS = ['retain', 'archive', 'delete', 'anonymize'];
const HOLD_STATUSES = ['active', 'released'];
const PURGE_JOB_STATUSES = ['planned', 'approved', 'running', 'completed', 'failed', 'cancelled'];
const GOVERNANCE_DECISIONS = ['allow', 'deny', 'hold', 'review_required'];
function addDays(dateText, days){const d=new Date(`${String(dateText).slice(0,10)}T00:00:00.000Z`); if(Number.isNaN(d.getTime())) return ''; d.setUTCDate(d.getUTCDate()+Number(days||0)); return d.toISOString().slice(0,10);}
function daysBetween(start,end){const a=new Date(`${String(start).slice(0,10)}T00:00:00.000Z`); const b=new Date(`${String(end).slice(0,10)}T00:00:00.000Z`); if(Number.isNaN(a.getTime())||Number.isNaN(b.getTime())) return null; return Math.floor((b-a)/86400000);}
function slugCode(value=''){return String(value).toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-|-$/g,'');}
function normalizeClassificationPolicyInput(input={}){if(!input.name) throw validationError('name is required'); if(!input.entityType) throw validationError('entityType is required'); const classificationLevel=input.classificationLevel||'internal'; const status=input.status||'active'; if(!CLASSIFICATION_LEVELS.includes(classificationLevel)) throw validationError(`Unsupported classification level: ${classificationLevel}`); if(!POLICY_STATUSES.includes(status)) throw validationError(`Unsupported classification policy status: ${status}`); return {code:input.code||slugCode(`${input.entityType}-${input.name}`),name:input.name,description:input.description||'',entityType:input.entityType,classificationLevel,pii:input.pii===true,financialData:input.financialData===true,healthData:input.healthData===true,status,metadata:input.metadata||{}};}
function normalizeRetentionPolicyInput(input={}){if(!input.name) throw validationError('name is required'); if(!input.entityType) throw validationError('entityType is required'); const status=input.status||'active'; const action=input.action||'archive'; if(!POLICY_STATUSES.includes(status)) throw validationError(`Unsupported retention policy status: ${status}`); if(!RETENTION_ACTIONS.includes(action)) throw validationError(`Unsupported retention action: ${action}`); return {code:input.code||slugCode(`${input.entityType}-${input.name}`),name:input.name,description:input.description||'',entityType:input.entityType,retentionDays:Number(input.retentionDays||2555),action,status,requiresApproval:input.requiresApproval!==false,metadata:input.metadata||{}};}
function normalizeLegalHoldInput(input={}){if(!input.name) throw validationError('name is required'); if(!input.entityType) throw validationError('entityType is required'); const status=input.status||'active'; if(!HOLD_STATUSES.includes(status)) throw validationError(`Unsupported legal hold status: ${status}`); return {name:input.name,description:input.description||'',entityType:input.entityType,entityId:input.entityId||'',status,reason:input.reason||'',createdBy:input.createdBy||'',releasedBy:input.releasedBy||'',releasedAt:input.releasedAt||'',metadata:input.metadata||{}};}
function normalizePurgeJobInput(input={}){if(!input.entityType) throw validationError('entityType is required'); const status=input.status||'planned'; const action=input.action||'archive'; if(!PURGE_JOB_STATUSES.includes(status)) throw validationError(`Unsupported purge job status: ${status}`); if(!RETENTION_ACTIONS.includes(action)) throw validationError(`Unsupported purge job action: ${action}`); return {entityType:input.entityType,retentionPolicyId:input.retentionPolicyId||'',action,status,plannedBy:input.plannedBy||'',approvedBy:input.approvedBy||'',approvedAt:input.approvedAt||'',startedAt:input.startedAt||'',completedAt:input.completedAt||'',candidateCount:Number(input.candidateCount||0),processedCount:Number(input.processedCount||0),failedCount:Number(input.failedCount||0),cutoffDate:input.cutoffDate||'',failureReason:input.failureReason||'',metadata:input.metadata||{}};}
function normalizeGovernanceDecisionInput(input={}){if(!input.entityType) throw validationError('entityType is required'); if(!input.action) throw validationError('action is required'); const result=input.result||'review_required'; if(!GOVERNANCE_DECISIONS.includes(result)) throw validationError(`Unsupported governance decision: ${result}`); return {entityType:input.entityType,entityId:input.entityId||'',action:input.action,result,reason:input.reason||'',policyId:input.policyId||'',decidedBy:input.decidedBy||'',decidedAt:input.decidedAt||new Date().toISOString(),metadata:input.metadata||{}};}
function findActiveHold({holds=[],entityType,entityId=''}){return (holds||[]).find(h=>h.status==='active'&&h.entityType===entityType&&(!h.entityId||h.entityId===entityId))||null;}
function evaluateRetentionEligibility({record={},policy,holds=[],asOfDate=new Date().toISOString().slice(0,10)}){if(!policy||policy.status!=='active') return {eligible:false,result:'review_required',reason:'No active retention policy applies',cutoffDate:'',ageDays:null}; const hold=findActiveHold({holds,entityType:policy.entityType,entityId:record.id||record.entityId||''}); if(hold) return {eligible:false,result:'hold',reason:`Legal hold applies: ${hold.name}`,cutoffDate:'',ageDays:null,holdId:hold.id||''}; const recordDate=record.completedAt||record.closedAt||record.updatedAt||record.createdAt||''; const ageDays=daysBetween(recordDate,asOfDate); const cutoffDate=addDays(asOfDate,-Number(policy.retentionDays||0)); if(ageDays===null) return {eligible:false,result:'review_required',reason:'Record date is invalid or missing',cutoffDate,ageDays:null}; if(ageDays>=Number(policy.retentionDays||0)) return {eligible:true,result:'allow',reason:`Record exceeds retention threshold for ${policy.action}`,cutoffDate,ageDays,action:policy.action}; return {eligible:false,result:'deny',reason:'Record has not reached retention threshold',cutoffDate,ageDays};}
function planPurgeJob({policy,records=[],holds=[],asOfDate=new Date().toISOString().slice(0,10),plannedBy=''}){if(!policy) throw validationError('policy is required'); const candidates=[]; const blocked=[]; for(const record of records){const evaluation=evaluateRetentionEligibility({record,policy,holds,asOfDate}); if(evaluation.eligible) candidates.push({record,evaluation}); else blocked.push({record,evaluation});} return {entityType:policy.entityType,retentionPolicyId:policy.id||'',action:policy.action,status:'planned',plannedBy,candidateCount:candidates.length,processedCount:0,failedCount:0,cutoffDate:addDays(asOfDate,-Number(policy.retentionDays||0)),candidates,blocked};}
function approvePurgeJob(job,approvedBy,approvedAt=new Date().toISOString()){if(!approvedBy) throw validationError('approvedBy is required'); return {...job,status:'approved',approvedBy,approvedAt,updatedAt:approvedAt};}
function completePurgeJob(job,processedCount,failedCount=0,completedAt=new Date().toISOString()){return {...job,status:failedCount>0?'failed':'completed',processedCount:Number(processedCount||0),failedCount:Number(failedCount||0),completedAt,updatedAt:completedAt};}
module.exports={CLASSIFICATION_LEVELS,POLICY_STATUSES,RETENTION_ACTIONS,HOLD_STATUSES,PURGE_JOB_STATUSES,GOVERNANCE_DECISIONS,addDays,daysBetween,slugCode,normalizeClassificationPolicyInput,normalizeRetentionPolicyInput,normalizeLegalHoldInput,normalizePurgeJobInput,normalizeGovernanceDecisionInput,findActiveHold,evaluateRetentionEligibility,planPurgeJob,approvePurgeJob,completePurgeJob};
