const{validationError}=require('../errors/domainError');const STATUSES=['identified','assessed','treating','accepted','closed'];const RESPONSES=['mitigate','accept','avoid','transfer'];
function score(l,i){l=Number(l);i=Number(i);if(!Number.isInteger(l)||!Number.isInteger(i)||l<1||l>5||i<1||i>5)throw validationError('likelihood and impact must be integers from 1 to 5');return l*i}function band(n){return n>=20?'critical':n>=12?'high':n>=6?'medium':'low'}
function normalizeRisk(x={}){if(!x.tenantId||!x.code||!x.title||!x.category||!x.owner)throw validationError('tenantId, code, title, category, and owner are required');const inherentScore=score(x.inherentLikelihood||1,x.inherentImpact||1),residualScore=score(x.residualLikelihood||x.inherentLikelihood||1,x.residualImpact||x.inherentImpact||1);return{tenantId:x.tenantId,code:x.code,title:x.title,description:x.description||'',category:x.category,owner:x.owner,status:x.status||'identified',inherentLikelihood:x.inherentLikelihood||1,inherentImpact:x.inherentImpact||1,inherentScore,inherentBand:band(inherentScore),residualLikelihood:x.residualLikelihood||x.inherentLikelihood||1,residualImpact:x.residualImpact||x.inherentImpact||1,residualScore,residualBand:band(residualScore),reviewAt:x.reviewAt||'',metadata:x.metadata||{}}}
function assess(r,l,i,at=new Date().toISOString()){const residualScore=score(l,i);return{...r,status:'assessed',residualLikelihood:Number(l),residualImpact:Number(i),residualScore,residualBand:band(residualScore),assessedAt:at,updatedAt:at}}
function normalizeKri(x={}){if(!x.tenantId||!x.riskId||!x.name||x.threshold==null)throw validationError('tenantId, riskId, name, and threshold are required');return{tenantId:x.tenantId,riskId:x.riskId,name:x.name,unit:x.unit||'count',threshold:Number(x.threshold),currentValue:Number(x.currentValue||0),status:Number(x.currentValue||0)>Number(x.threshold)?'breached':'normal',measuredAt:x.measuredAt||new Date().toISOString()}}
function measureKri(r,v,at=new Date().toISOString()){v=Number(v);return{...r,currentValue:v,status:v>r.threshold?'breached':'normal',measuredAt:at,updatedAt:at}}
function normalizeTreatment(x={}){if(!x.tenantId||!x.riskId||!x.owner||!x.response||!x.plan)throw validationError('tenantId, riskId, owner, response, and plan are required');if(!RESPONSES.includes(x.response))throw validationError('invalid risk response');return{tenantId:x.tenantId,riskId:x.riskId,owner:x.owner,response:x.response,plan:x.plan,status:'planned',dueAt:x.dueAt||'',completedAt:'',evidence:x.evidence||[]}}
function completeTreatment(r,evidence=[],at=new Date().toISOString()){return{...r,status:'completed',evidence,completedAt:at,updatedAt:at}}
function heatMap(risks=[]){const cells={};for(const r of risks){const k=`${r.residualLikelihood}x${r.residualImpact}`;cells[k]=(cells[k]||0)+1}return cells}function metrics({risks=[],kris=[],treatments=[]}){return{openRisks:risks.filter(x=>x.status!=='closed').length,criticalRisks:risks.filter(x=>x.residualBand==='critical'&&x.status!=='closed').length,highRisks:risks.filter(x=>x.residualBand==='high'&&x.status!=='closed').length,breachedKris:kris.filter(x=>x.status==='breached').length,overdueTreatments:treatments.filter(x=>x.status!=='completed'&&x.dueAt&&new Date()>new Date(x.dueAt)).length,heatMap:heatMap(risks)}}
module.exports={STATUSES,RESPONSES,score,band,normalizeRisk,assess,normalizeKri,measureKri,normalizeTreatment,completeTreatment,heatMap,metrics};
