const { validationError } = require('../errors/domainError');
const ENVIRONMENT_TYPES = ['development', 'test', 'staging', 'production', 'disaster_recovery'];
const ENVIRONMENT_STATUSES = ['active', 'maintenance', 'disabled'];
const RELEASE_STATUSES = ['draft', 'approved', 'deployed', 'rolled_back', 'failed'];
const CHECK_STATUSES = ['passing', 'warning', 'failing', 'unknown'];
const RUNBOOK_SEVERITIES = ['info', 'low', 'medium', 'high', 'critical'];
function normalizeDeploymentEnvironmentInput(input = {}) { if (!input.name) throw validationError('name is required'); const environmentType = input.environmentType || 'staging'; const status = input.status || 'active'; if (!ENVIRONMENT_TYPES.includes(environmentType)) throw validationError(`Unsupported environment type: ${environmentType}`); if (!ENVIRONMENT_STATUSES.includes(status)) throw validationError(`Unsupported environment status: ${status}`); return { code: input.code || String(input.name).toUpperCase().replace(/[^A-Z0-9]+/g, '-').replace(/^-|-$/g, ''), name: input.name, environmentType, status, region: input.region || '', baseUrl: input.baseUrl || '', databaseMode: input.databaseMode || 'json', ownerTeam: input.ownerTeam || 'platform', deploymentStrategy: input.deploymentStrategy || 'rolling', metadata: input.metadata || {} }; }
function normalizeReleaseManifestInput(input = {}) { if (!input.version) throw validationError('version is required'); if (!input.environmentId) throw validationError('environmentId is required'); const status = input.status || 'draft'; if (!RELEASE_STATUSES.includes(status)) throw validationError(`Unsupported release status: ${status}`); return { version: input.version, environmentId: input.environmentId, status, gitCommit: input.gitCommit || '', gitBranch: input.gitBranch || '', artifactUri: input.artifactUri || '', migrationRange: input.migrationRange || '', releaseNotes: input.releaseNotes || '', approvedBy: input.approvedBy || '', approvedAt: input.approvedAt || '', deployedBy: input.deployedBy || '', deployedAt: input.deployedAt || '', rollbackVersion: input.rollbackVersion || '', metadata: input.metadata || {} }; }
function normalizeHealthCheckInput(input = {}) { if (!input.environmentId) throw validationError('environmentId is required'); if (!input.checkKey) throw validationError('checkKey is required'); const status = input.status || 'unknown'; if (!CHECK_STATUSES.includes(status)) throw validationError(`Unsupported check status: ${status}`); return { environmentId: input.environmentId, releaseId: input.releaseId || '', checkKey: input.checkKey, label: input.label || input.checkKey, status, message: input.message || '', observedValue: input.observedValue === undefined ? null : input.observedValue, expectedValue: input.expectedValue === undefined ? null : input.expectedValue, checkedAt: input.checkedAt || new Date().toISOString(), metadata: input.metadata || {} }; }
function normalizeRunbookEntryInput(input = {}) { if (!input.title) throw validationError('title is required'); if (!input.category) throw validationError('category is required'); const severity = input.severity || 'medium'; if (!RUNBOOK_SEVERITIES.includes(severity)) throw validationError(`Unsupported runbook severity: ${severity}`); return { title: input.title, category: input.category, severity, symptom: input.symptom || '', diagnosisSteps: Array.isArray(input.diagnosisSteps) ? input.diagnosisSteps : [], remediationSteps: Array.isArray(input.remediationSteps) ? input.remediationSteps : [], escalationPath: input.escalationPath || '', active: input.active !== false, metadata: input.metadata || {} }; }
function approveRelease(release, approvedBy, approvedAt = new Date().toISOString()) { if (!approvedBy) throw validationError('approvedBy is required'); return { ...release, status: 'approved', approvedBy, approvedAt, updatedAt: approvedAt }; }
function markReleaseDeployed(release, deployedBy, deployedAt = new Date().toISOString()) { if (!deployedBy) throw validationError('deployedBy is required'); return { ...release, status: 'deployed', deployedBy, deployedAt, updatedAt: deployedAt }; }
function markReleaseRolledBack(release, rollbackVersion, actor = '', at = new Date().toISOString()) { if (!rollbackVersion) throw validationError('rollbackVersion is required'); return { ...release, status: 'rolled_back', rollbackVersion, deployedBy: actor || release.deployedBy || '', deployedAt: at, updatedAt: at }; }
function calculateReadiness(checks = []) { const total = checks.length; const failing = checks.filter(x => x.status === 'failing').length; const warning = checks.filter(x => x.status === 'warning').length; const passing = checks.filter(x => x.status === 'passing').length; const unknown = checks.filter(x => x.status === 'unknown').length; const ready = total > 0 && failing === 0 && unknown === 0; let readinessStatus = ready ? 'ready' : 'not_ready'; if (ready && warning > 0) readinessStatus = 'ready_with_warnings'; return { ready, readinessStatus, total, passing, warning, failing, unknown }; }
function buildReadinessReport({ environment, release, checks = [] }) { if (!environment) throw validationError('environment is required'); return { environmentId: environment.id || '', environmentName: environment.name, environmentType: environment.environmentType, releaseId: release ? release.id || '' : '', version: release ? release.version || '' : '', summary: calculateReadiness(checks), checks: checks.slice().sort((a,b)=>String(a.checkKey).localeCompare(String(b.checkKey))), generatedAt: new Date().toISOString() }; }
function defaultProductionChecks(environmentId, releaseId = '') { return [ { environmentId, releaseId, checkKey:'database_connectivity', label:'Database connectivity', status:'unknown', message:'Database connectivity has not been checked.' }, { environmentId, releaseId, checkKey:'migrations_current', label:'Migrations current', status:'unknown', message:'Migration status has not been checked.' }, { environmentId, releaseId, checkKey:'backup_available', label:'Backup available', status:'unknown', message:'Backup availability has not been checked.' }, { environmentId, releaseId, checkKey:'configuration_valid', label:'Configuration valid', status:'unknown', message:'Configuration validation has not been checked.' }, { environmentId, releaseId, checkKey:'external_services_reachable', label:'External services reachable', status:'unknown', message:'External services have not been checked.' } ]; }
module.exports = { ENVIRONMENT_TYPES, ENVIRONMENT_STATUSES, RELEASE_STATUSES, CHECK_STATUSES, RUNBOOK_SEVERITIES, normalizeDeploymentEnvironmentInput, normalizeReleaseManifestInput, normalizeHealthCheckInput, normalizeRunbookEntryInput, approveRelease, markReleaseDeployed, markReleaseRolledBack, calculateReadiness, buildReadinessReport, defaultProductionChecks };
