const {validationError}=require('../errors/domainError');
const POLICY_STATUSES=['draft','in_review','approved','published','retired'];const DECISIONS=['approved','rejected'];
function addDays(v,n){const d=new Date(v||new Date().toISOString());d.setUTCDate(d.getUTCDate()+Number(n));return d.toISOString()}
function normalizePolicy(i={}){if(!i.tenantId||!i.code||!i.title||!i.owner)throw validationError('tenantId, code, title, and owner are required');return{tenantId:i.tenantId,code:i.code,title:i.title,category:i.category||'corporate',owner:i.owner,status:'draft',currentVersionId:'',publishedAt:'',expiresAt:i.expiresAt||'',reviewAt:i.reviewAt||addDays(null,365),metadata:i.metadata||{}}}
function normalizeVersion(i={}){if(!i.tenantId||!i.policyId||!i.content)throw validationError('tenantId, policyId, and content are required');return{tenantId:i.tenantId,policyId:i.policyId,version:i.version||'1.0',content:i.content,summary:i.summary||'',status:'draft',createdBy:i.createdBy||'',submittedAt:'',approvedAt:'',publishedAt:'',supersedesVersionId:i.supersedesVersionId||'',metadata:i.metadata||{}}}
function submitVersion(r,at=new Date().toISOString()){return{...r,status:'in_review',submittedAt:at,updatedAt:at}}
function decideVersion(r,decision,approver,comments='',at=new Date().toISOString()){if(!DECISIONS.includes(decision)||!approver)throw validationError('valid decision and approver are required');return{...r,status:decision,approver,approvalComments:comments,approvedAt:decision==='approved'?at:'',updatedAt:at}}
function publishVersion(r,at=new Date().toISOString()){if(r.status!=='approved')throw validationError('version must be approved before publication');return{...r,status:'published',publishedAt:at,updatedAt:at}}
function normalizeAcknowledgement(i={}){if(!i.tenantId||!i.policyId||!i.versionId||!i.subjectId)throw validationError('tenantId, policyId, versionId, and subjectId are required');return{tenantId:i.tenantId,policyId:i.policyId,versionId:i.versionId,subjectId:i.subjectId,status:'pending',dueAt:i.dueAt||addDays(null,30),acknowledgedAt:'',attestation:i.attestation||'',metadata:i.metadata||{}}}
function acknowledge(r,attestation,at=new Date().toISOString()){if(!attestation)throw validationError('attestation is required');return{...r,status:'acknowledged',attestation,acknowledgedAt:at,updatedAt:at}}
function normalizeException(i={}){if(!i.tenantId||!i.policyId||!i.requestor||!i.reason)throw validationError('tenantId, policyId, requestor, and reason are required');return{tenantId:i.tenantId,policyId:i.policyId,requestor:i.requestor,reason:i.reason,status:'pending',expiresAt:i.expiresAt||addDays(null,90),decidedBy:'',decidedAt:'',comments:'',metadata:i.metadata||{}}}
function decideException(r,decision,by,comments='',at=new Date().toISOString()){if(!DECISIONS.includes(decision)||!by)throw validationError('valid decision and decision maker are required');return{...r,status:decision,decidedBy:by,decidedAt:at,comments,updatedAt:at}}
function isOverdue(r,asOf=new Date().toISOString()){return r.status==='pending'&&new Date(asOf)>new Date(r.dueAt)}function isExpiring(r,asOf=new Date().toISOString(),days=30){return!!r.expiresAt&&new Date(r.expiresAt)>=new Date(asOf)&&new Date(r.expiresAt)<=new Date(addDays(asOf,days))}
function metrics({policies=[],acknowledgements=[],exceptions=[]},asOf){return{publishedPolicies:policies.filter(x=>x.status==='published').length,pendingAcknowledgements:acknowledgements.filter(x=>x.status==='pending').length,overdueAcknowledgements:acknowledgements.filter(x=>isOverdue(x,asOf)).length,pendingExceptions:exceptions.filter(x=>x.status==='pending').length,expiringPolicies:policies.filter(x=>isExpiring(x,asOf)).length,expiringExceptions:exceptions.filter(x=>x.status==='approved'&&isExpiring(x,asOf)).length}}
module.exports={POLICY_STATUSES,DECISIONS,normalizePolicy,normalizeVersion,submitVersion,decideVersion,publishVersion,normalizeAcknowledgement,acknowledge,normalizeException,decideException,isOverdue,isExpiring,metrics};
