const { validationError } = require('../errors/domainError');
const APPEAL_STATUSES = ['received','review','upheld','overturned','withdrawn'];
const INQUIRY_STATUSES = ['received','investigating','response_due','submitted','closed'];
function addDays(value, days){const d=new Date(value||new Date().toISOString());d.setUTCDate(d.getUTCDate()+Number(days||0));return d.toISOString();}
function normalizeAppealInput(input={}){if(!input.tenantId||!input.caseId||!input.reason)throw validationError('tenantId, caseId, and reason are required');return{tenantId:input.tenantId,caseId:input.caseId,reason:input.reason,status:'received',receivedAt:input.receivedAt||new Date().toISOString(),dueAt:input.dueAt||addDays(input.receivedAt,45),reviewer:'',decisionReason:'',decidedAt:'',metadata:input.metadata||{}};}
function startReview(row,reviewer,at=new Date().toISOString()){if(!reviewer)throw validationError('reviewer is required');return{...row,status:'review',reviewer,updatedAt:at};}
function decideAppeal(row,outcome,reason,at=new Date().toISOString()){if(!['upheld','overturned'].includes(outcome))throw validationError('invalid appeal outcome');if(!reason)throw validationError('decision reason is required');return{...row,status:outcome,decisionReason:reason,decidedAt:at,updatedAt:at};}
function normalizeInquiryInput(input={}){if(!input.tenantId||!input.authority||!input.reference)throw validationError('tenantId, authority, and reference are required');const receivedAt=input.receivedAt||new Date().toISOString();return{tenantId:input.tenantId,authority:input.authority,reference:input.reference,subject:input.subject||'',status:'received',receivedAt,dueAt:input.dueAt||addDays(receivedAt,30),owner:input.owner||'',response:'',submittedAt:'',closedAt:'',metadata:input.metadata||{}};}
function submitInquiry(row,response,at=new Date().toISOString()){if(!response)throw validationError('response is required');return{...row,status:'submitted',response,submittedAt:at,updatedAt:at};}
function closeInquiry(row,at=new Date().toISOString()){return{...row,status:'closed',closedAt:at,updatedAt:at};}
function isOverdue(row,asOf=new Date().toISOString()){return !['upheld','overturned','withdrawn','submitted','closed'].includes(row.status)&&new Date(asOf)>new Date(row.dueAt);}
function metrics({appeals=[],inquiries=[]},asOf=new Date().toISOString()){return{openAppeals:appeals.filter(x=>['received','review'].includes(x.status)).length,overdueAppeals:appeals.filter(x=>isOverdue(x,asOf)).length,overturnedAppeals:appeals.filter(x=>x.status==='overturned').length,openInquiries:inquiries.filter(x=>!['submitted','closed'].includes(x.status)).length,overdueInquiries:inquiries.filter(x=>isOverdue(x,asOf)).length,submittedInquiries:inquiries.filter(x=>x.status==='submitted').length};}
module.exports={APPEAL_STATUSES,INQUIRY_STATUSES,addDays,normalizeAppealInput,startReview,decideAppeal,normalizeInquiryInput,submitInquiry,closeInquiry,isOverdue,metrics};
