const { validationError } = require('../errors/domainError');
const FINDING_STATUSES = ['open','remediation','exception_requested','exception_approved','resolved'];
const SEVERITIES = ['low','medium','high','critical'];
function normalizeFindingInput(input={}){if(!input.tenantId||!input.title||!input.control||!input.severity)throw validationError('tenantId, title, control, and severity are required');if(!SEVERITIES.includes(input.severity))throw validationError('invalid severity');return{tenantId:input.tenantId,title:input.title,control:input.control,severity:input.severity,status:'open',owner:input.owner||'',dueAt:input.dueAt||'',remediationPlan:'',exceptionReason:'',exceptionExpiresAt:'',approvedBy:'',resolvedAt:'',metadata:input.metadata||{}};}
function planRemediation(row,owner,plan,dueAt,at=new Date().toISOString()){if(!owner||!plan||!dueAt)throw validationError('owner, plan, and dueAt are required');return{...row,status:'remediation',owner,remediationPlan:plan,dueAt,updatedAt:at};}
function requestException(row,reason,expiresAt,at=new Date().toISOString()){if(!reason||!expiresAt)throw validationError('reason and expiresAt are required');return{...row,status:'exception_requested',exceptionReason:reason,exceptionExpiresAt:expiresAt,updatedAt:at};}
function approveException(row,approver,at=new Date().toISOString()){if(row.status!=='exception_requested')throw validationError('exception must be requested before approval');if(!approver)throw validationError('approver is required');return{...row,status:'exception_approved',approvedBy:approver,updatedAt:at};}
function resolveFinding(row,note,at=new Date().toISOString()){if(!note)throw validationError('resolution note is required');return{...row,status:'resolved',resolutionNote:note,resolvedAt:at,updatedAt:at};}
function isOverdue(row,asOf=new Date().toISOString()){return !['resolved','exception_approved'].includes(row.status)&&!!row.dueAt&&new Date(asOf)>new Date(row.dueAt);}
function metrics(findings=[],asOf=new Date().toISOString()){return{openFindings:findings.filter(x=>x.status!=='resolved').length,criticalFindings:findings.filter(x=>x.severity==='critical'&&x.status!=='resolved').length,overdueFindings:findings.filter(x=>isOverdue(x,asOf)).length,approvedExceptions:findings.filter(x=>x.status==='exception_approved').length,resolvedFindings:findings.filter(x=>x.status==='resolved').length};}
module.exports={FINDING_STATUSES,SEVERITIES,normalizeFindingInput,planRemediation,requestException,approveException,resolveFinding,isOverdue,metrics};
