const {validationError}=require('../errors/domainError');
function normalizeControl(input={}){if(!input.tenantId||!input.key||!input.name||!input.frequency)throw validationError('tenantId, key, name, and frequency are required');return{tenantId:input.tenantId,key:input.key,name:input.name,frequency:input.frequency,owner:input.owner||'',enabled:input.enabled!==false,lastRunAt:'',nextRunAt:input.nextRunAt||'',metadata:input.metadata||{}};}
function normalizeRun(input={}){if(!input.tenantId||!input.controlId)throw validationError('tenantId and controlId are required');return{tenantId:input.tenantId,controlId:input.controlId,status:'running',startedAt:input.startedAt||new Date().toISOString(),completedAt:'',result:{},failureReason:''};}
function completeRun(row,passed,details={},at=new Date().toISOString()){return{...row,status:passed?'passed':'failed',completedAt:at,result:details,failureReason:passed?'':(details.reason||'control check failed'),updatedAt:at};}
function normalizeAlert(input={}){if(!input.tenantId||!input.controlId||!input.runId||!input.message)throw validationError('tenantId, controlId, runId, and message are required');return{tenantId:input.tenantId,controlId:input.controlId,runId:input.runId,message:input.message,severity:input.severity||'high',status:'open',assignee:input.assignee||'',acknowledgedAt:'',resolvedAt:'',resolution:''};}
function acknowledgeAlert(row,assignee,at=new Date().toISOString()){if(!assignee)throw validationError('assignee is required');return{...row,status:'acknowledged',assignee,acknowledgedAt:at,updatedAt:at};}
function resolveAlert(row,resolution,at=new Date().toISOString()){if(!resolution)throw validationError('resolution is required');return{...row,status:'resolved',resolution,resolvedAt:at,updatedAt:at};}
function metrics({controls=[],runs=[],alerts=[]}){return{enabledControls:controls.filter(x=>x.enabled).length,passedRuns:runs.filter(x=>x.status==='passed').length,failedRuns:runs.filter(x=>x.status==='failed').length,openAlerts:alerts.filter(x=>x.status!=='resolved').length,resolvedAlerts:alerts.filter(x=>x.status==='resolved').length};}
module.exports={normalizeControl,normalizeRun,completeRun,normalizeAlert,acknowledgeAlert,resolveAlert,metrics};
