const { validationError } = require('../errors/domainError');
const PLAYBOOK_STATUSES=['draft','active','disabled','retired'];
const TRIGGER_TYPES=['manual','alert','incident','indicator','scheduled'];
const STEP_TYPES=['condition','action','approval','notification','delay','rollback'];
const CONNECTOR_STATUSES=['active','disabled','retired'];
const CASE_STATUSES=['open','running','waiting_approval','completed','failed','cancelled'];
const RUN_STATUSES=['queued','running','waiting_approval','completed','failed','cancelled','rolled_back'];
const APPROVAL_STATUSES=['pending','approved','rejected','expired'];
const LOG_LEVELS=['debug','info','warn','error'];
function assertAllowed(v,a,l){if(!a.includes(v))throw validationError(`Unsupported ${l}: ${v}`)}
function slugCode(v=''){return String(v).toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-|-$/g,'')}
function addDays(d,days){const b=new Date(d||new Date().toISOString());b.setUTCDate(b.getUTCDate()+Number(days||0));return b.toISOString()}
function normalizePlaybookInput(i={}){if(!i.tenantId)throw validationError('tenantId is required');if(!i.name)throw validationError('name is required');const status=i.status||'draft',triggerType=i.triggerType||'manual';assertAllowed(status,PLAYBOOK_STATUSES,'playbook status');assertAllowed(triggerType,TRIGGER_TYPES,'trigger type');return{tenantId:i.tenantId,code:i.code||slugCode(i.name),name:i.name,description:i.description||'',status,triggerType,owner:i.owner||'',version:i.version||'1.0',maxRuntimeSeconds:Number(i.maxRuntimeSeconds||900),requiresApproval:i.requiresApproval===true,tags:Array.isArray(i.tags)?i.tags:[],metadata:i.metadata||{}}}
function normalizeStepInput(i={}){if(!i.playbookId)throw validationError('playbookId is required');if(!i.name)throw validationError('name is required');const stepType=i.stepType||'action';assertAllowed(stepType,STEP_TYPES,'step type');return{tenantId:i.tenantId||'',playbookId:i.playbookId,name:i.name,stepType,sequence:Number(i.sequence||1),connectorId:i.connectorId||'',actionName:i.actionName||'',condition:i.condition||{},parameters:i.parameters||{},rollbackStepId:i.rollbackStepId||'',stopOnFailure:i.stopOnFailure!==false,metadata:i.metadata||{}}}
function normalizeConnectorInput(i={}){if(!i.tenantId)throw validationError('tenantId is required');if(!i.name)throw validationError('name is required');const status=i.status||'active';assertAllowed(status,CONNECTOR_STATUSES,'connector status');return{tenantId:i.tenantId,code:i.code||slugCode(i.name),name:i.name,description:i.description||'',status,connectorType:i.connectorType||'custom',baseUrl:i.baseUrl||'',authMode:i.authMode||'none',allowedActions:Array.isArray(i.allowedActions)?i.allowedActions:[],metadata:i.metadata||{}}}
function normalizeCaseInput(i={}){if(!i.tenantId)throw validationError('tenantId is required');if(!i.title)throw validationError('title is required');const status=i.status||'open';assertAllowed(status,CASE_STATUSES,'case status');return{tenantId:i.tenantId,caseNumber:i.caseNumber||'',title:i.title,description:i.description||'',status,severity:i.severity||'medium',sourceType:i.sourceType||'',sourceId:i.sourceId||'',owner:i.owner||'',openedAt:i.openedAt||new Date().toISOString(),closedAt:i.closedAt||'',metadata:i.metadata||{}}}
function normalizeRunInput(i={}){if(!i.tenantId)throw validationError('tenantId is required');if(!i.playbookId)throw validationError('playbookId is required');const status=i.status||'queued';assertAllowed(status,RUN_STATUSES,'run status');return{tenantId:i.tenantId,playbookId:i.playbookId,caseId:i.caseId||'',status,requestedBy:i.requestedBy||'',input:i.input||{},output:i.output||{},queuedAt:i.queuedAt||new Date().toISOString(),startedAt:i.startedAt||'',completedAt:i.completedAt||'',failedAt:i.failedAt||'',failureReason:i.failureReason||'',currentStepId:i.currentStepId||'',metadata:i.metadata||{}}}
function normalizeApprovalInput(i={}){if(!i.runId)throw validationError('runId is required');if(!i.approverId)throw validationError('approverId is required');const status=i.status||'pending';assertAllowed(status,APPROVAL_STATUSES,'approval status');return{tenantId:i.tenantId||'',runId:i.runId,stepId:i.stepId||'',approverId:i.approverId,approverName:i.approverName||'',status,requestedAt:i.requestedAt||new Date().toISOString(),respondedAt:i.respondedAt||'',comments:i.comments||'',expiresAt:i.expiresAt||addDays(new Date().toISOString(),1),metadata:i.metadata||{}}}
function normalizeLogInput(i={}){if(!i.runId)throw validationError('runId is required');const level=i.level||'info';assertAllowed(level,LOG_LEVELS,'log level');return{tenantId:i.tenantId||'',runId:i.runId,stepId:i.stepId||'',level,message:i.message||'',payload:i.payload||{},createdAt:i.createdAt||new Date().toISOString(),metadata:i.metadata||{}}}
function activatePlaybook(x,at=new Date().toISOString()){return{...x,status:'active',updatedAt:at}};function disablePlaybook(x,at=new Date().toISOString()){return{...x,status:'disabled',updatedAt:at}}
function startCase(x,at=new Date().toISOString()){return{...x,status:'running',updatedAt:at}};function closeCase(x,at=new Date().toISOString()){return{...x,status:'completed',closedAt:at,updatedAt:at}}
function startRun(x,step='',at=new Date().toISOString()){return{...x,status:'running',startedAt:at,currentStepId:step||x.currentStepId,updatedAt:at}};function waitApproval(x,step='',at=new Date().toISOString()){return{...x,status:'waiting_approval',currentStepId:step||x.currentStepId,updatedAt:at}}
function completeRun(x,out={},at=new Date().toISOString()){return{...x,status:'completed',output:out,completedAt:at,updatedAt:at}};function failRun(x,reason,at=new Date().toISOString()){if(!reason)throw validationError('reason is required');return{...x,status:'failed',failureReason:reason,failedAt:at,updatedAt:at}}
function rollbackRun(x,reason='',at=new Date().toISOString()){return{...x,status:'rolled_back',failureReason:reason||x.failureReason,completedAt:at,updatedAt:at}}
function approveRunApproval(x,comments='',at=new Date().toISOString()){return{...x,status:'approved',comments,respondedAt:at,updatedAt:at}};function rejectRunApproval(x,comments='',at=new Date().toISOString()){return{...x,status:'rejected',comments,respondedAt:at,updatedAt:at}}
function stepSort(a,b){return Number(a.sequence||0)-Number(b.sequence||0)};function canExecuteConnectorAction(c,a){return c.status==='active'&&(!c.allowedActions.length||c.allowedActions.includes(a))}
function soarMetrics({playbooks=[],connectors=[],cases=[],runs=[],approvals=[],logs=[]}){return{activePlaybooks:playbooks.filter(x=>x.status==='active').length,activeConnectors:connectors.filter(x=>x.status==='active').length,openCases:cases.filter(x=>['open','running','waiting_approval'].includes(x.status)).length,runningRuns:runs.filter(x=>['queued','running','waiting_approval'].includes(x.status)).length,completedRuns:runs.filter(x=>x.status==='completed').length,failedRuns:runs.filter(x=>x.status==='failed').length,pendingApprovals:approvals.filter(x=>x.status==='pending').length,errorLogs:logs.filter(x=>x.level==='error').length}}
module.exports={PLAYBOOK_STATUSES,TRIGGER_TYPES,STEP_TYPES,CONNECTOR_STATUSES,CASE_STATUSES,RUN_STATUSES,APPROVAL_STATUSES,LOG_LEVELS,assertAllowed,slugCode,addDays,normalizePlaybookInput,normalizeStepInput,normalizeConnectorInput,normalizeCaseInput,normalizeRunInput,normalizeApprovalInput,normalizeLogInput,activatePlaybook,disablePlaybook,startCase,closeCase,startRun,waitApproval,completeRun,failRun,rollbackRun,approveRunApproval,rejectRunApproval,stepSort,canExecuteConnectorAction,soarMetrics};
