const {sendJson}=require('../utils/http');const {operationalTenant}=require('../services/tenantResolver');
function done(res,p,status=200){return Promise.resolve(p).then(data=>sendJson(res,status,{data})).catch(e=>sendJson(res,e.status||500,{error:{code:e.code||'express_service_failed',message:e.message}}));}
function getSettings(req,res){return done(res,req.context.repositories.expressService.getSettings(operationalTenant(req)));}
function saveSettings(req,res){return done(res,(async()=>{const tenantId=operationalTenant(req),input=req.body||{};if(input.requirePhotos)throw Object.assign(new Error('Photo uploads are unavailable until secure upload storage is configured.'),{code:'feature_not_available',status:409});if(input.depositRequired||input.paymentRequired)throw Object.assign(new Error('Express Service deposits and prepayment are not operational yet. Keep these options disabled.'),{code:'feature_not_available',status:409});if(input.enabled&&(!Array.isArray(input.eligibleServiceIds)||!input.eligibleServiceIds.length))throw Object.assign(new Error('Select at least one eligible service before enabling Express Service.'),{code:'validation_failed',status:400});if(input.enabled&&(!Array.isArray(input.serviceAreaIds)||!input.serviceAreaIds.length))throw Object.assign(new Error('Configure at least one service area before enabling Express Service.'),{code:'validation_failed',status:400});return req.context.repositories.expressService.saveSettings(tenantId,{...input,requirePhotos:false,depositRequired:false,paymentRequired:false,depositAmountCents:0});})());}
function createPortalRequest(req,res){return done(res,(async()=>{const tenantId=req.context.tenantId,s=await req.context.repositories.expressService.getSettings(tenantId),b=req.body||{};if(!s.enabled)throw Object.assign(new Error('Express Service is not available.'),{code:'express_service_disabled',status:404});if(!s.eligibleServiceIds.includes(b.serviceId))throw Object.assign(new Error('Selected service is not eligible for Express Service.'),{code:'service_not_eligible',status:400});if(s.requireDescription&&!String(b.description||'').trim())throw Object.assign(new Error('A description is required.'),{code:'validation_failed',status:400});if(s.requirePhotos&&(!Array.isArray(b.photos)||!b.photos.length))throw Object.assign(new Error('At least one photo is required.'),{code:'validation_failed',status:400});if(b.urgency==='emergency'&&!s.emergencyEnabled)throw Object.assign(new Error('Emergency requests are not enabled.'),{code:'urgency_not_available',status:400});return req.context.repositories.expressService.createRequest(tenantId,{...b,customerId:req.context.portalCustomerId,portalAccountId:req.context.portalAccountId});})(),201);}
function list(req,res){return done(res,req.context.repositories.expressService.listRequests(operationalTenant(req)));}
function portalSettings(req,res){return done(res,(async()=>{const tenantId=req.context.tenantId,settings=await req.context.repositories.expressService.getSettings(tenantId),catalog=await req.context.repositories.services.list(tenantId),eligible=catalog.filter(x=>settings.eligibleServiceIds.includes(x.id)).map(x=>({id:x.id,name:x.name,description:x.description||'',basePrice:x.basePrice}));return{enabled:settings.enabled,requireDescription:settings.requireDescription,emergencyEnabled:settings.emergencyEnabled,afterHoursEnabled:settings.afterHoursEnabled,eligibleServices:eligible};})());}
function portalList(req,res){return done(res,req.context.repositories.expressService.listRequests(req.context.tenantId,{customerId:req.context.portalCustomerId}));}
function update(req,res,id){return done(res,(async()=>{const allowed=['acknowledged','assigned','scheduled','in_progress','completed','invoiced','paid','cancelled'];if(req.body?.status&&!allowed.includes(req.body.status))throw Object.assign(new Error('Invalid Express Service status.'),{code:'validation_failed',status:400});const row=await req.context.repositories.expressService.updateRequest(operationalTenant(req),id,req.body||{});if(!row)throw Object.assign(new Error('Express Service request not found.'),{code:'not_found',status:404});return row;})());}
function convert(req,res,id){return done(res,(async()=>{const result=await req.context.repositories.expressService.convertRequest(operationalTenant(req),id);if(!result)throw Object.assign(new Error('Express Service request not found.'),{code:'not_found',status:404});return result;})());}
module.exports={getSettings,saveSettings,createPortalRequest,list,update,convert,portalSettings,portalList};
