const {sendJson}=require('../utils/http');const {MODULES,normalizeModules}=require('../services/moduleAccessService');const {isPlatformAdmin}=require('../services/platformAdminService');
const denied=res=>sendJson(res,403,{error:{code:'forbidden',message:'Access denied'}});
const teamRoles=values=>(Array.isArray(values)?values:[]).filter(x=>['admin','manager','technician','billing','read_only'].includes(x));
async function mine(req,res){const enabled=await req.context.repositories.moduleAccess.tenantModules(req.context.tenantId);const modules=(req.context.roles||[]).includes('owner')||isPlatformAdmin(req)?enabled:(await req.context.repositories.moduleAccess.userAccess(req.context.tenantId,req.context.userId))?.modules||[];return sendJson(res,200,{data:{available:MODULES,enabled,modules:modules.filter(x=>enabled.includes(x)),platformAdmin:isPlatformAdmin(req)}})}
async function platformGet(req,res,tenant){if(!isPlatformAdmin(req))return denied(res);return sendJson(res,200,{data:{tenantId:tenant,modules:await req.context.repositories.moduleAccess.tenantModules(tenant),available:MODULES}})}
async function platformSet(req,res,tenant){if(!isPlatformAdmin(req))return denied(res);return sendJson(res,200,{data:{tenantId:tenant,modules:await req.context.repositories.moduleAccess.setTenantModules(tenant,req.body.modules,req.context.userId)}})}
async function teamList(req,res){if(!(req.context.roles||[]).includes('owner'))return denied(res);const users=await req.context.repositories.moduleAccess.listUsers(req.context.tenantId);return sendJson(res,200,{data:{enabledModules:await req.context.repositories.moduleAccess.tenantModules(req.context.tenantId),users:users.filter(user=>!(user.roles||[]).includes('owner'))}})}
async function teamCreate(req,res){if(!(req.context.roles||[]).includes('owner'))return denied(res);const {email,name,password}=req.body||{},roles=teamRoles(req.body.roles),enabled=await req.context.repositories.moduleAccess.tenantModules(req.context.tenantId),modules=normalizeModules(req.body.modules);if(!email||!name||!password||password.length<12||!roles.length)return sendJson(res,400,{error:{code:'validation_failed',message:'Name, email, a 12-character temporary password, and a valid role are required'}});if(modules.some(x=>!enabled.includes(x)))return sendJson(res,400,{error:{code:'module_boundary_violation',message:'Cannot grant a module not enabled for this tenant'}});const user=await req.context.repositories.users.create({tenantId:req.context.tenantId,email:String(email).trim().toLowerCase(),name,password,roles});if(!user)return sendJson(res,409,{error:{code:'account_exists',message:'A team member with this email already exists'}});const updated=await req.context.repositories.moduleAccess.updateUser(req.context.tenantId,user.id,{roles,modules});return sendJson(res,201,{data:updated||user});}
async function teamUpdate(req,res,userId){if(!(req.context.roles||[]).includes('owner'))return denied(res);if(userId===req.context.userId)return sendJson(res,400,{error:{code:'owner_self_update_denied',message:'Use your profile settings to update your own account'}});const enabled=await req.context.repositories.moduleAccess.tenantModules(req.context.tenantId),modules=normalizeModules(req.body.modules);if(modules.some(x=>!enabled.includes(x)))return sendJson(res,400,{error:{code:'module_boundary_violation',message:'Cannot grant a module not enabled for this tenant'}});const roles=teamRoles(req.body.roles);return sendJson(res,200,{data:await req.context.repositories.moduleAccess.updateUser(req.context.tenantId,userId,{roles,modules})})}
module.exports={mine,platformGet,platformSet,teamList,teamCreate,teamUpdate};
