const { sendJson } = require('../utils/http');
function tenant(req){return req.context.tenantId;} function repo(req){return req.context.repositories.operations;}
function filters(req){return {environmentType:req.body.environmentType||'',environmentId:req.body.environmentId||'',releaseId:req.body.releaseId||'',status:req.body.status||'',category:req.body.category||'',severity:req.body.severity||'',active:req.body.active};}
function listEnvironments(req,res){Promise.resolve(repo(req).listEnvironments(tenant(req),filters(req))).then(data=>sendJson(res,200,{data}));}
function createEnvironment(req,res){Promise.resolve(repo(req).createEnvironment(tenant(req),req.body)).then(data=>sendJson(res,201,{data})).catch(err=>sendJson(res,err.status||500,{error:{code:err.code||'error',message:err.message,details:err.details||{}}}));}
function listReleases(req,res){Promise.resolve(repo(req).listReleases(tenant(req),filters(req))).then(data=>sendJson(res,200,{data}));}
function createRelease(req,res){Promise.resolve(repo(req).createRelease(tenant(req),req.body)).then(data=>sendJson(res,201,{data})).catch(err=>sendJson(res,err.status||500,{error:{code:err.code||'error',message:err.message,details:err.details||{}}}));}
function approveRelease(req,res,id){Promise.resolve(repo(req).approveRelease(tenant(req),id,req.body.approvedBy||req.context.userId||'')).then(data=>data?sendJson(res,200,{data}):sendJson(res,404,{error:{code:'not_found',message:'Release not found'}})).catch(err=>sendJson(res,err.status||500,{error:{code:err.code||'error',message:err.message,details:err.details||{}}}));}
function deployRelease(req,res,id){Promise.resolve(repo(req).deployRelease(tenant(req),id,req.body.deployedBy||req.context.userId||'')).then(data=>data?sendJson(res,200,{data}):sendJson(res,404,{error:{code:'not_found',message:'Release not found'}})).catch(err=>sendJson(res,err.status||500,{error:{code:err.code||'error',message:err.message,details:err.details||{}}}));}
function rollbackRelease(req,res,id){Promise.resolve(repo(req).rollbackRelease(tenant(req),id,req.body)).then(data=>data?sendJson(res,200,{data}):sendJson(res,404,{error:{code:'not_found',message:'Release not found'}})).catch(err=>sendJson(res,err.status||500,{error:{code:err.code||'error',message:err.message,details:err.details||{}}}));}
function listHealthChecks(req,res){Promise.resolve(repo(req).listHealthChecks(tenant(req),filters(req))).then(data=>sendJson(res,200,{data}));}
function recordHealthCheck(req,res){Promise.resolve(repo(req).recordHealthCheck(tenant(req),req.body)).then(data=>sendJson(res,201,{data})).catch(err=>sendJson(res,err.status||500,{error:{code:err.code||'error',message:err.message,details:err.details||{}}}));}
function seedDefaultChecks(req,res){Promise.resolve(repo(req).seedDefaultChecks(tenant(req),req.body.environmentId,req.body.releaseId||'')).then(data=>sendJson(res,201,{data})).catch(err=>sendJson(res,err.status||500,{error:{code:err.code||'error',message:err.message,details:err.details||{}}}));}
function readiness(req,res){Promise.resolve(repo(req).readiness(tenant(req),req.body.environmentId,req.body.releaseId||'')).then(data=>data?sendJson(res,200,{data}):sendJson(res,404,{error:{code:'not_found',message:'Environment not found'}}));}
function listRunbookEntries(req,res){Promise.resolve(repo(req).listRunbookEntries(tenant(req),filters(req))).then(data=>sendJson(res,200,{data}));}
function createRunbookEntry(req,res){Promise.resolve(repo(req).createRunbookEntry(tenant(req),req.body)).then(data=>sendJson(res,201,{data})).catch(err=>sendJson(res,err.status||500,{error:{code:err.code||'error',message:err.message,details:err.details||{}}}));}
module.exports={listEnvironments,createEnvironment,listReleases,createRelease,approveRelease,deployRelease,rollbackRelease,listHealthChecks,recordHealthCheck,seedDefaultChecks,readiness,listRunbookEntries,createRunbookEntry};
