const crypto=require('crypto');
const {sendJson}=require('../utils/http');
const {operationalTenant}=require('../services/tenantResolver');
const {getRepositories,getRepositoriesForTenant}=require('../repositories/repositoryFactory');
const {createInvoicePayment}=require('../services/customerPaymentService');

const hash=token=>crypto.createHash('sha256').update(String(token)).digest('hex');
function tokenFromUrl(url){const match=String(url||'').match(/^\/api\/public\/payment-links\/([^/?]+)/);return match?decodeURIComponent(match[1]):'';}
async function resolve(token){if(!/^[A-Za-z0-9_-]{40,}$/.test(token))return null;const invoice=await getRepositories().invoices.findByPaymentLinkHash(hash(token));if(!invoice||!invoice.paymentLinkExpiresAt||new Date(invoice.paymentLinkExpiresAt)<=new Date())return null;return invoice;}

function create(req,res,id){Promise.resolve().then(async()=>{const tenantId=operationalTenant(req),invoice=await req.context.repositories.invoices.findById(tenantId,id);if(!invoice)return sendJson(res,404,{error:{code:'not_found',message:'Invoice not found.'}});if(Number(invoice.balanceDue||0)<=0)return sendJson(res,409,{error:{code:'invoice_already_paid',message:'Invoice is already paid.'}});const settings=await req.context.repositories.subscriberPaymentSettings.get(tenantId),account=await req.context.repositories.subscriberStripeAccounts.get(tenantId);if(!settings.acceptCustomerPayments||!account?.chargesEnabled)return sendJson(res,409,{error:{code:'payments_unavailable',message:'Enable customer payments and complete Stripe onboarding first.'}});const token=crypto.randomBytes(32).toString('base64url'),days=Math.min(Math.max(Number(req.body?.expiresInDays)||14,1),90),expiresAt=new Date(Date.now()+days*86400000).toISOString();await req.context.repositories.invoices.setPaymentLink(tenantId,id,hash(token),expiresAt);const base=String(process.env.CUSTOMER_PORTAL_URL||'').replace(/\/$/,'');return sendJson(res,201,{data:{url:`${base}/pay?token=${encodeURIComponent(token)}`,expiresAt}});}).catch(error=>sendJson(res,error.status||500,{error:{code:error.code||'payment_link_failed',message:error.message}}));}
function inspect(req,res){Promise.resolve().then(async()=>{const invoice=await resolve(tokenFromUrl(req.url));if(!invoice)return sendJson(res,404,{error:{code:'invalid_payment_link',message:'Payment link is invalid or expired.'}});const repos=getRepositoriesForTenant(invoice.tenantId),settings=await repos.subscriberPaymentSettings.get(invoice.tenantId),account=await repos.subscriberStripeAccounts.get(invoice.tenantId);if(!settings.acceptCustomerPayments||!account?.chargesEnabled)return sendJson(res,409,{error:{code:'payments_unavailable',message:'Online payments are unavailable.'}});if(Number(invoice.balanceDue||0)<=0)return sendJson(res,409,{error:{code:'invoice_already_paid',message:'Invoice is already paid.'}});return sendJson(res,200,{data:{invoiceId:invoice.id,invoiceNumber:invoice.invoiceNumber||invoice.id,balanceDue:invoice.balanceDue,currency:invoice.currency||settings.defaultCurrency,acceptedMethods:['card'],stripeConnectedAccountId:account.stripeAccountId}});}).catch(error=>sendJson(res,error.status||500,{error:{code:error.code||'payment_link_failed',message:error.message}}));}
function pay(req,res){Promise.resolve().then(async()=>{const invoice=await resolve(tokenFromUrl(req.url));if(!invoice)return sendJson(res,404,{error:{code:'invalid_payment_link',message:'Payment link is invalid or expired.'}});const repos=getRepositoriesForTenant(invoice.tenantId),data=await createInvoicePayment(repos,invoice.tenantId,{invoiceId:invoice.id,amountCents:req.body?.amountCents,idempotencyKey:req.body?.idempotencyKey});return sendJson(res,data.idempotent?200:201,{data});}).catch(error=>sendJson(res,error.status||500,{error:{code:error.code||'payment_link_failed',message:error.message}}));}
module.exports={create,inspect,pay,_test:{hash,resolve}};
