const { sendJson } = require('../utils/http');
function repo(req) { return req.context.repositories.siemDetectionEngineering; }
function filters(req) { return { tenantId: req.body.tenantId || req.context.tenantId || '', status: req.body.status || '', severity: req.body.severity || '', sourceType: req.body.sourceType || '' }; }
function wrap(promise, res, status = 200) { Promise.resolve(promise).then(data => sendJson(res, status, { data })).catch(err => sendJson(res, err.status || 500, { error: { code: err.code || 'error', message: err.message, details: err.details || {} } })); }
module.exports = {
  createSource(req, res) { wrap(repo(req).createSource({ ...req.body, tenantId: req.body.tenantId || req.context.tenantId || '' }), res, 201); }, listSources(req, res) { wrap(repo(req).listSources(filters(req)), res); }, activateSource(req, res, id) { wrap(repo(req).activateSource(id), res); }, markSourceDegraded(req, res, id) { wrap(repo(req).markSourceDegraded(id), res); },
  createRule(req, res) { wrap(repo(req).createRule({ ...req.body, tenantId: req.body.tenantId || req.context.tenantId || '' }), res, 201); }, listRules(req, res) { wrap(repo(req).listRules(filters(req)), res); }, activateRule(req, res, id) { wrap(repo(req).activateRule(id), res); }, disableRule(req, res, id) { wrap(repo(req).disableRule(id), res); },
  createRuleTest(req, res, ruleId) { wrap(repo(req).createRuleTest({ ...req.body, ruleId, tenantId: req.body.tenantId || req.context.tenantId || '' }), res, 201); }, runRuleTest(req, res, id) { wrap(repo(req).runRuleTest(id, req.body.actualMatch === true), res); },
  createAlert(req, res) { wrap(repo(req).createAlert({ ...req.body, tenantId: req.body.tenantId || req.context.tenantId || '' }), res, 201); }, listAlerts(req, res) { wrap(repo(req).listAlerts(filters(req)), res); },
  triageAlert(req, res, id) { wrap(repo(req).triageAlert(id, req.body.assignee || req.context.userId || ''), res); }, investigateAlert(req, res, id) { wrap(repo(req).investigateAlert(id, req.body.assignee || req.context.userId || ''), res); }, escalateAlert(req, res, id) { wrap(repo(req).escalateAlert(id, req.body.incidentId || ''), res); }, closeAlert(req, res, id) { wrap(repo(req).closeAlert(id, req.body.reason || ''), res); }, markFalsePositive(req, res, id) { wrap(repo(req).markFalsePositive(id, req.body.reason || ''), res); },
  createSuppression(req, res) { wrap(repo(req).createSuppression({ ...req.body, tenantId: req.body.tenantId || req.context.tenantId || '' }), res, 201); }, createTuning(req, res) { wrap(repo(req).createTuning({ ...req.body, tenantId: req.body.tenantId || req.context.tenantId || '' }), res, 201); }, approveTuning(req, res, id) { wrap(repo(req).approveTuning(id, req.body.approvedBy || req.context.userId || ''), res); }, applyTuning(req, res, id) { wrap(repo(req).applyTuning(id), res); },
  metrics(req, res) { wrap(repo(req).metrics(req.body.tenantId || req.context.tenantId || ''), res); }
};
