const { sendJson }=require('../utils/http');
const { operationalTenant }=require('../services/tenantResolver');
const connect=require('../services/stripeConnectService');

function tenant(req){return operationalTenant(req);}
function publicAccount(row){return row?{accountId:row.stripeAccountId,status:row.status,chargesEnabled:Boolean(row.chargesEnabled),payoutsEnabled:Boolean(row.payoutsEnabled),detailsSubmitted:Boolean(row.detailsSubmitted),country:row.country||'',defaultCurrency:row.defaultCurrency||'usd'}:null;}
function handle(res,promise,status=200){return Promise.resolve(promise).then(data=>sendJson(res,status,{data})).catch(err=>sendJson(res,err.status||500,{error:{code:err.code||'stripe_connect_failed',message:err.message}}));}

function status(req,res){return handle(res,(async()=>publicAccount(await req.context.repositories.subscriberStripeAccounts.get(tenant(req))))());}
function onboard(req,res){return handle(res,(async()=>{const tenantId=tenant(req),repo=req.context.repositories.subscriberStripeAccounts;let row=await repo.get(tenantId);if(!row){const account=await connect.createExpressAccount(tenantId,req.context.user?.email||'');row=await repo.upsert(tenantId,connect.accountRecord(account));}const link=await connect.createAccountLink(row.stripeAccountId,req.body?.returnUrl,req.body?.refreshUrl);if(row.status==='pending')row=await repo.upsert(tenantId,{...row,status:'onboarding'});return{...publicAccount(row),accountLinkUrl:link.url};})(),201);}
function refreshLink(req,res){return handle(res,(async()=>{const row=await req.context.repositories.subscriberStripeAccounts.get(tenant(req));if(!row)throw Object.assign(new Error('No connected Stripe account exists.'),{code:'stripe_account_not_found',status:404});const link=await connect.createAccountLink(row.stripeAccountId,req.body?.returnUrl,req.body?.refreshUrl);return{accountLinkUrl:link.url};})());}
function dashboard(req,res){return handle(res,(async()=>{const row=await req.context.repositories.subscriberStripeAccounts.get(tenant(req));if(!row||!row.chargesEnabled)throw Object.assign(new Error('Stripe account management is not available.'),{code:'stripe_account_unavailable',status:409});const link=await connect.createDashboardLink(row.stripeAccountId);return{url:link.url};})());}
function disconnect(req,res){return handle(res,(async()=>{const tenantId=tenant(req);await req.context.repositories.subscriberPaymentSettings.upsert(tenantId,{acceptCustomerPayments:false});const row=await req.context.repositories.subscriberStripeAccounts.disconnect(tenantId);if(!row)throw Object.assign(new Error('No connected Stripe account exists.'),{code:'stripe_account_not_found',status:404});return{disconnected:true};})());}
function getSettings(req,res){return handle(res,(async()=>{const tenantId=tenant(req);const settings=await req.context.repositories.subscriberPaymentSettings.get(tenantId);const account=await req.context.repositories.subscriberStripeAccounts.get(tenantId);return{...settings,stripeAccount:publicAccount(account)};})());}
function updateSettings(req,res){return handle(res,(async()=>{const tenantId=tenant(req),input={...(req.body||{})};if(input.defaultCurrency!==undefined&&!/^[a-z]{3}$/i.test(input.defaultCurrency))throw Object.assign(new Error('defaultCurrency must be a three-letter code.'),{code:'validation_failed',status:400});if(input.acceptedMethods!==undefined&&(!Array.isArray(input.acceptedMethods)||input.acceptedMethods.length!==1||input.acceptedMethods[0]!=='card'))throw Object.assign(new Error('Card is the only payment method currently supported. Bank payments, wallets, and saved methods are unavailable.'),{code:'unsupported_payment_method',status:400});for(const key of ['savedPaymentMethods','tipsEnabled','convenienceFeeEnabled','progressPaymentsEnabled','paymentReminders'])if(input[key]===true)throw Object.assign(new Error(`${key} is not operational and cannot be enabled.`),{code:'feature_not_available',status:409});if(input.acceptCustomerPayments===true){const account=await req.context.repositories.subscriberStripeAccounts.get(tenantId);if(!account||account.status!=='active'||!account.chargesEnabled)throw Object.assign(new Error('Complete Stripe onboarding before accepting customer payments.'),{code:'stripe_account_not_active',status:409});}const updated=await req.context.repositories.subscriberPaymentSettings.upsert(tenantId,{...input,acceptedMethods:['card']});const account=await req.context.repositories.subscriberStripeAccounts.get(tenantId);return{...updated,stripeAccount:publicAccount(account)};})());}

module.exports={status,onboard,refreshLink,dashboard,disconnect,getSettings,updateSettings,publicAccount};
