import Link from 'next/link';
import { BrandMark } from '@/components/BrandMark';
import { ThemeToggle } from '@/components/ThemeToggle';
import { LogoutButton } from '@/components/LogoutButton';

export const metadata = { title: 'Operations dashboard' };
const nav = ['Overview', 'Work orders', 'Schedule', 'Customers', 'Assets', 'Reports'];
const kpis = [['Open work', '38', '+8%'], ['On-time arrival', '94%', '+3.2%'], ['First-time fix', '87%', '+1.4%'], ['Revenue today', '$18,420', '+12%']];

export default function DashboardPage() {
  return <main className="app-shell"><aside className="sidebar"><BrandMark /><nav aria-label="Application navigation">{nav.map((item, index) => <Link className={index === 0 ? 'active' : ''} href="/dashboard" key={item}><span>{['⌂','▤','◫','◎','◇','↗'][index]}</span>{item}</Link>)}</nav><div className="sidebar-bottom"><Link href="/dashboard"><span>⚙</span>Settings</Link><LogoutButton /><div className="user-chip"><b>AM</b><span><strong>Alex Morgan</strong><small>Operations admin</small></span></div></div></aside><section className="workspace">
    <header className="workspace-header"><div><small>Wednesday, July 15</small><strong>Good morning, Alex.</strong></div><div className="workspace-actions"><button className="search-button" type="button">⌕ <span>Search anything</span><kbd>⌘ K</kbd></button><ThemeToggle /><button className="icon-button" type="button" aria-label="Notifications">♢<i /></button><button className="button button-small" type="button">+ New work order</button></div></header>
    <div className="dashboard-content"><div className="dashboard-intro"><div><p className="eyebrow"><span /> Operations overview</p><h1>Everything is moving.</h1><p>Here’s what needs your attention across the business today.</p></div><button className="date-button" type="button">Today · Jul 15⌄</button></div>
      <section className="kpi-grid" aria-label="Key performance indicators">{kpis.map(([label, value, trend]) => <article key={label}><span>{label}</span><strong>{value}</strong><small>{trend} <i>vs last period</i></small></article>)}</section>
      <div className="dashboard-grid"><section className="panel attention-panel"><div className="panel-heading"><div><h2>Needs attention</h2><p>Items that may affect today’s commitments.</p></div><Link href="/dashboard">View all →</Link></div>{[['Urgent', 'WO-4821 · Main line leak', 'Riverside Medical Center', 'Unassigned · Due 10:30 AM'], ['At risk', 'WO-4817 · Boiler pressure', 'Northgate Apartments', 'Parts delayed · Due 1:00 PM'], ['Approval', 'Estimate #E-1934', 'Harrison Manufacturing', '$8,420 · Waiting 2 days']].map(([tag,title,site,meta], i) => <article className="attention-row" key={title}><span className={`priority p${i}`}>{tag}</span><div><strong>{title}</strong><p>{site}</p></div><small>{meta}</small><button type="button" aria-label={`Open ${title}`}>→</button></article>)}</section>
      <section className="panel team-panel"><div className="panel-heading"><div><h2>Team in the field</h2><p>8 active · 2 available</p></div><Link href="/dashboard">Dispatch →</Link></div><div className="team-map">{[['MC','p1'],['JR','p2'],['AB','p3'],['SK','p4']].map(([name, pos]) => <i className={pos} key={name}>{name}</i>)}</div><div className="team-status"><span><i className="green" /> 5 on site</span><span><i className="blue" /> 3 en route</span><span><i /> 2 available</span></div></section></div>
      <section className="panel schedule-panel"><div className="panel-heading"><div><h2>Today’s schedule</h2><p>24 appointments · 92% on track</p></div><Link href="/dashboard">Full schedule →</Link></div><div className="schedule-track"><span>8 AM</span><span>10 AM</span><span>12 PM</span><span>2 PM</span><span>4 PM</span></div><div className="schedule-jobs"><span style={{left:'5%',width:'21%'}}>Inspection · M. Carter</span><span style={{left:'29%',width:'27%'}}>Backflow service · J. Rivera</span><span style={{left:'60%',width:'17%'}}>Boiler PM · A. Brooks</span><span style={{left:'81%',width:'14%'}}>Open</span></div></section>
    </div></section></main>;
}
