'use client';
import {useEffect,useMemo,useState} from 'react';
import {Elements,PaymentElement,useElements,useStripe} from '@stripe/react-stripe-js';
import {loadStripe} from '@stripe/stripe-js';

const apiBase=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type LinkInfo={invoiceId:string;invoiceNumber:string;balanceDue:number;currency:string;acceptedMethods:string[];stripeConnectedAccountId:string};
function PaymentForm(){const stripe=useStripe(),elements=useElements(),[message,setMessage]=useState('');return <form onSubmit={async e=>{e.preventDefault();if(!stripe||!elements)return;setMessage('Processing…');const result=await stripe.confirmPayment({elements,confirmParams:{return_url:window.location.href},redirect:'if_required'});setMessage(result.error?.message||'Payment submitted. Your receipt and invoice status will update after verification.');}}><PaymentElement/><button className="btn btn-primary" disabled={!stripe}>Pay securely</button><p role="status">{message}</p></form>}
export default function PaymentLinkPage(){const[token,setToken]=useState<string|null>(null),[info,setInfo]=useState<LinkInfo|null>(null),[secret,setSecret]=useState(''),[message,setMessage]=useState('Loading payment link…');const publishable=process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY||'',stripePromise=useMemo(()=>publishable&&info?.stripeConnectedAccountId?loadStripe(publishable,{stripeAccount:info.stripeConnectedAccountId}):null,[publishable,info?.stripeConnectedAccountId]);
 useEffect(()=>setToken(new URLSearchParams(window.location.search).get('token')||''),[]);
 useEffect(()=>{if(token===null)return;if(!token){setMessage('Payment link is invalid.');return;}fetch(`${apiBase}/api/public/payment-links/${encodeURIComponent(token)}`).then(async r=>({ok:r.ok,body:await r.json()})).then(async({ok,body})=>{if(!ok)throw new Error(body.error?.message||'Payment link is unavailable.');setInfo(body.data);const key=crypto.randomUUID(),pay=await fetch(`${apiBase}/api/public/payment-links/${encodeURIComponent(token)}/pay`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idempotencyKey:`payment-link-${key}`})}),payment=await pay.json();if(!pay.ok)throw new Error(payment.error?.message||'Unable to prepare payment.');setSecret(payment.data.clientSecret);setMessage('');}).catch(e=>setMessage(e.message));},[token]);
 return <main style={{maxWidth:720,margin:'3rem auto',padding:'1rem'}}><h1>Pay invoice</h1>{message&&<p role="status">{message}</p>}{info&&<section className="card"><h2>Invoice {info.invoiceNumber}</h2><p>Balance due: {new Intl.NumberFormat('en-US',{style:'currency',currency:info.currency.toUpperCase()}).format(info.balanceDue)}</p>{secret&&stripePromise&&<Elements stripe={stripePromise} options={{clientSecret:secret}}><PaymentForm/></Elements>}</section>}</main>}
