import Link from 'next/link';
export const metadata={title:'Settings'};
const sections=[
 ['Customer Experience',[['Customer Portal','Branding, invoice, estimate, payment, and profile visibility.','/settings/customer-portal'],['Express Service','Eligible services, service areas, deposits, and request behavior.','/settings/express-service'],['Profile and security','Personal details, password, MFA, sessions, and API tokens.','/profile']]],
 ['Sales',[['Estimates and approvals','Create estimates and manage supported customer approvals.','/estimates'],['Deposits','Configure deposit collection with customer payments.','/settings/customer-payments']]],
 ['Billing',[['Invoices and refunds','Invoices, payment links, customer payments, and authorized refunds.','/invoices'],['Customer Payments','Stripe Connect, cards, partial payments, deposits, and receipts.','/settings/customer-payments'],['Commerce readiness','Blocking and recommended onboarding checks.','/settings/commerce-readiness']]],
 ['Service Delivery',[['Scheduling and dispatch','Existing scheduling, assignment, and service delivery controls.','/dashboard'],['Express Service delivery','Areas, urgency, assignment, and customer request status.','/settings/express-service'],['Organization','Business units, departments, locations, teams, and reporting structure.','/organization']]],
 ['Communications',[['Notifications','Email and supported notification preferences.','/notifications'],['Automatic receipts','Verified-payment receipt delivery settings.','/settings/customer-payments'],['Marketplace','Service-industry packs, connectors, extensions, and workspace themes.','/marketplace'],['Documentation','Operating guides, tutorials, API reference, and release notes.','/docs'],['System status','Website connectivity, API health, runtime readiness, and deployment diagnostics.','/system-status']]]
] as const;
export default function SettingsPage(){return <div className="dashboard-content settings-page"><div className="dashboard-intro"><div><p className="eyebrow"><span/> Workspace administration</p><h1>Settings</h1><p>Configure the subscriber experience, sales, billing, service delivery, and communications.</p></div></div>{sections.map(([name,items])=><section className="panel" key={name}><h2>{name}</h2><div className="settings-grid">{items.map(([title,description,href])=><Link className="panel" href={href} key={href}><span aria-hidden="true">→</span><h3>{title}</h3><p>{description}</p><strong>Open settings</strong></Link>)}</div></section>)}</div>}
