const { makeId, now } = require('../services/id');
const { normalizeRecommendationRequestInput, normalizeRecommendationResult, rankDispatchCandidates } = require('../services/aiDispatchService');

function createAiDispatchRepository(store) { if (store.type === 'json') return createJsonAiDispatchRepository(store); if (store.type === 'postgres') return createPostgresAiDispatchRepository(store); throw new Error(`Unsupported store type: ${store.type}`); }
function ensureAiDispatch(data) { if (!data.aiDispatchRequests) data.aiDispatchRequests = []; if (!data.aiDispatchRecommendations) data.aiDispatchRecommendations = []; return data; }

function createJsonAiDispatchRepository(store) {
  return {
    listRequests(tenantId, filters = {}) { return ensureAiDispatch(store.read()).aiDispatchRequests.filter(x=>x.tenantId===tenantId).filter(x=>!filters.jobId||x.jobId===filters.jobId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))); },
    findRequestById(tenantId, id) { return ensureAiDispatch(store.read()).aiDispatchRequests.find(x=>x.tenantId===tenantId&&x.id===id)||null; },
    createRequest(tenantId, input) { const data=ensureAiDispatch(store.read()); const request={ id: makeId('aidreq'), tenantId, ...normalizeRecommendationRequestInput(input), createdAt: now(), updatedAt: now() }; data.aiDispatchRequests.push(request); store.write(data); return request; },
    generateRecommendation(tenantId, input) { const data=ensureAiDispatch(store.read()); const request=input.requestId ? data.aiDispatchRequests.find(x=>x.tenantId===tenantId&&x.id===input.requestId) : { id: makeId('aidreq'), tenantId, ...normalizeRecommendationRequestInput(input.request||input), createdAt: now(), updatedAt: now() }; if (!request) return null; if (!input.requestId) data.aiDispatchRequests.push(request); const candidates=rankDispatchCandidates(request,input.candidates||[]); const recommendation={ id: makeId('aidrec'), tenantId, ...normalizeRecommendationResult({ requestId: request.id, jobId: request.jobId, status: 'generated', candidates, generatedAt: now(), metadata: input.metadata||{} }), createdAt: now(), updatedAt: now() }; data.aiDispatchRecommendations.push(recommendation); store.write(data); return recommendation; },
    listRecommendations(tenantId, filters = {}) { return ensureAiDispatch(store.read()).aiDispatchRecommendations.filter(x=>x.tenantId===tenantId).filter(x=>!filters.jobId||x.jobId===filters.jobId).filter(x=>!filters.status||x.status===filters.status).sort((a,b)=>String(b.generatedAt).localeCompare(String(a.generatedAt))); },
    findRecommendationById(tenantId,id) { return ensureAiDispatch(store.read()).aiDispatchRecommendations.find(x=>x.tenantId===tenantId&&x.id===id)||null; },
    acceptRecommendation(tenantId,id,input={}) { const data=ensureAiDispatch(store.read()); const idx=data.aiDispatchRecommendations.findIndex(x=>x.tenantId===tenantId&&x.id===id); if (idx===-1) return null; data.aiDispatchRecommendations[idx]={ ...data.aiDispatchRecommendations[idx], status:'accepted', selectedTechnicianId: input.selectedTechnicianId || data.aiDispatchRecommendations[idx].selectedTechnicianId || (data.aiDispatchRecommendations[idx].candidates[0]||{}).technicianId || '', acceptedBy: input.acceptedBy||'', acceptedAt: input.acceptedAt||now(), updatedAt: now() }; store.write(data); return data.aiDispatchRecommendations[idx]; },
    rejectRecommendation(tenantId,id,input={}) { const data=ensureAiDispatch(store.read()); const idx=data.aiDispatchRecommendations.findIndex(x=>x.tenantId===tenantId&&x.id===id); if (idx===-1) return null; data.aiDispatchRecommendations[idx]={ ...data.aiDispatchRecommendations[idx], status:'rejected', rejectedReason: input.rejectedReason||'Rejected', updatedAt: now() }; store.write(data); return data.aiDispatchRecommendations[idx]; }
  };
}

function createPostgresAiDispatchRepository(store) {
  const requestSelect = `SELECT id::text, tenant_id as "tenantId", job_id::text as "jobId", customer_id::text as "customerId", appointment_id::text as "appointmentId", requested_for as "requestedFor", service_type as "serviceType", priority, territory_id::text as "territoryId", required_skills as "requiredSkills", preferred_technician_id::text as "preferredTechnicianId", excluded_technician_ids as "excludedTechnicianIds", candidate_limit as "candidateLimit", weights, metadata, created_at as "createdAt", updated_at as "updatedAt" FROM ai_dispatch_requests`;
  const recommendationSelect = `SELECT id::text, tenant_id as "tenantId", request_id::text as "requestId", job_id::text as "jobId", status, candidates, selected_technician_id::text as "selectedTechnicianId", accepted_by as "acceptedBy", accepted_at as "acceptedAt", rejected_reason as "rejectedReason", generated_at as "generatedAt", metadata, created_at as "createdAt", updated_at as "updatedAt" FROM ai_dispatch_recommendations`;
  return {
    async listRequests(tenantId, filters={}) { const params=[tenantId]; let where='WHERE tenant_id = $1'; if (filters.jobId) { params.push(filters.jobId); where += ` AND job_id = $${params.length}`; } const result=await store.query(`${requestSelect} ${where} ORDER BY created_at DESC`, params); return result.rows; },
    async findRequestById(tenantId,id) { const result=await store.query(`${requestSelect} WHERE tenant_id = $1 AND id = $2 LIMIT 1`, [tenantId,id]); return result.rows[0]||null; },
    async createRequest(tenantId,input) { const x=normalizeRecommendationRequestInput(input); const result=await store.query(`INSERT INTO ai_dispatch_requests (tenant_id, job_id, customer_id, appointment_id, requested_for, service_type, priority, territory_id, required_skills, preferred_technician_id, excluded_technician_ids, candidate_limit, weights, metadata) VALUES ($1,$2::uuid,NULLIF($3,'')::uuid,NULLIF($4,'')::uuid,$5::timestamptz,$6,$7,NULLIF($8,'')::uuid,$9::jsonb,NULLIF($10,'')::uuid,$11::jsonb,$12,$13::jsonb,$14::jsonb) RETURNING id::text, tenant_id as "tenantId", job_id::text as "jobId", customer_id::text as "customerId", appointment_id::text as "appointmentId", requested_for as "requestedFor", service_type as "serviceType", priority, territory_id::text as "territoryId", required_skills as "requiredSkills", preferred_technician_id::text as "preferredTechnicianId", excluded_technician_ids as "excludedTechnicianIds", candidate_limit as "candidateLimit", weights, metadata, created_at as "createdAt", updated_at as "updatedAt"`, [tenantId,x.jobId,x.customerId,x.appointmentId,x.requestedFor,x.serviceType,x.priority,x.territoryId,JSON.stringify(x.requiredSkills||[]),x.preferredTechnicianId,JSON.stringify(x.excludedTechnicianIds||[]),x.candidateLimit,JSON.stringify(x.weights||{}),JSON.stringify(x.metadata||{})]); return result.rows[0]; },
    async generateRecommendation(tenantId,input) { let request=input.requestId ? await this.findRequestById(tenantId,input.requestId) : await this.createRequest(tenantId,input.request||input); if (!request) return null; const candidates=rankDispatchCandidates(request,input.candidates||[]); const x=normalizeRecommendationResult({ requestId: request.id, jobId: request.jobId, status:'generated', candidates, generatedAt:new Date().toISOString(), metadata:input.metadata||{} }); const result=await store.query(`INSERT INTO ai_dispatch_recommendations (tenant_id, request_id, job_id, status, candidates, selected_technician_id, accepted_by, accepted_at, rejected_reason, generated_at, metadata) VALUES ($1,$2::uuid,$3::uuid,$4,$5::jsonb,NULLIF($6,'')::uuid,$7,NULLIF($8,'')::timestamptz,$9,$10::timestamptz,$11::jsonb) RETURNING id::text, tenant_id as "tenantId", request_id::text as "requestId", job_id::text as "jobId", status, candidates, selected_technician_id::text as "selectedTechnicianId", accepted_by as "acceptedBy", accepted_at as "acceptedAt", rejected_reason as "rejectedReason", generated_at as "generatedAt", metadata, created_at as "createdAt", updated_at as "updatedAt"`, [tenantId,x.requestId,x.jobId,x.status,JSON.stringify(x.candidates||[]),x.selectedTechnicianId,x.acceptedBy,x.acceptedAt,x.rejectedReason,x.generatedAt,JSON.stringify(x.metadata||{})]); return result.rows[0]; },
    async listRecommendations(tenantId, filters={}) { const params=[tenantId]; let where='WHERE tenant_id = $1'; if (filters.jobId) { params.push(filters.jobId); where += ` AND job_id = $${params.length}`; } if (filters.status) { params.push(filters.status); where += ` AND status = $${params.length}`; } const result=await store.query(`${recommendationSelect} ${where} ORDER BY generated_at DESC`, params); return result.rows; },
    async findRecommendationById(tenantId,id) { const result=await store.query(`${recommendationSelect} WHERE tenant_id = $1 AND id = $2 LIMIT 1`, [tenantId,id]); return result.rows[0]||null; },
    async acceptRecommendation(tenantId,id,input={}) { const existing=await this.findRecommendationById(tenantId,id); if (!existing) return null; const selected=input.selectedTechnicianId || existing.selectedTechnicianId || ((existing.candidates||[])[0]||{}).technicianId || ''; const result=await store.query(`UPDATE ai_dispatch_recommendations SET status='accepted', selected_technician_id=NULLIF($3,'')::uuid, accepted_by=$4, accepted_at=$5::timestamptz, updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id::text, tenant_id as "tenantId", request_id::text as "requestId", job_id::text as "jobId", status, candidates, selected_technician_id::text as "selectedTechnicianId", accepted_by as "acceptedBy", accepted_at as "acceptedAt", rejected_reason as "rejectedReason", generated_at as "generatedAt", metadata, created_at as "createdAt", updated_at as "updatedAt"`, [tenantId,id,selected,input.acceptedBy||'',input.acceptedAt||new Date().toISOString()]); return result.rows[0]||null; },
    async rejectRecommendation(tenantId,id,input={}) { const result=await store.query(`UPDATE ai_dispatch_recommendations SET status='rejected', rejected_reason=$3, updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id::text, tenant_id as "tenantId", request_id::text as "requestId", job_id::text as "jobId", status, candidates, selected_technician_id::text as "selectedTechnicianId", accepted_by as "acceptedBy", accepted_at as "acceptedAt", rejected_reason as "rejectedReason", generated_at as "generatedAt", metadata, created_at as "createdAt", updated_at as "updatedAt"`, [tenantId,id,input.rejectedReason||'Rejected']); return result.rows[0]||null; }
  };
}
module.exports = { createAiDispatchRepository };
