const{makeId,now}=require('../services/id');const s=require('../services/certificateLifecycleService');
const DS=`SELECT id::text,tenant_id AS "tenantId",name,owner,registrar,status,expires_at AS "expiresAt",auto_renew AS "autoRenew",dns_provider AS "dnsProvider",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM managed_domains`;
const CS=`SELECT id::text,tenant_id AS "tenantId",domain_id::text AS "domainId",common_name AS "commonName",sans,owner,issuer,serial_number AS "serialNumber",status,issued_at AS "issuedAt",expires_at AS "expiresAt",key_algorithm AS "keyAlgorithm",key_size AS "keySize",auto_renew AS "autoRenew",vault_ref AS "vaultRef",last_rotated_at AS "lastRotatedAt",next_rotation_at AS "nextRotationAt",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM managed_certificates`;
function e(d){d.managedDomains||=[];d.managedCertificates||=[];d.certificateEvents||=[];return d}function u(a,t,id,f){const i=a.findIndex(x=>x.id===id&&x.tenantId===t);if(i<0)return null;a[i]=f(a[i]);return a[i]}
function json(store){function event(d,r,type,data){if(r)d.certificateEvents.push({id:makeId('certevt'),tenantId:r.tenantId,certificateId:r.id,type,data,createdAt:now()})}return{createDomain(x){const d=e(store.read()),r={id:makeId('domain'),...s.normalizeDomain(x),createdAt:now(),updatedAt:now()};d.managedDomains.push(r);store.write(d);return r},createCertificate(x){const d=e(store.read());if(!d.managedDomains.some(v=>v.id===x.domainId&&v.tenantId===x.tenantId))return null;const r={id:makeId('cert'),...s.normalizeCertificate(x),createdAt:now(),updatedAt:now()};d.managedCertificates.push(r);store.write(d);return r},activate(t,id){const d=e(store.read()),r=u(d.managedCertificates,t,id,s.activateCertificate);event(d,r,'activated',{});store.write(d);return r},renew(t,id,x){const d=e(store.read()),r=u(d.managedCertificates,t,id,v=>s.renewCertificate(v,x));event(d,r,'renewed',x);store.write(d);return r},rotate(t,id,v){const d=e(store.read()),r=u(d.managedCertificates,t,id,x=>s.rotateKey(x,v));event(d,r,'rotated',{vaultRef:v});store.write(d);return r},revoke(t,id,v){const d=e(store.read()),r=u(d.managedCertificates,t,id,x=>s.revokeCertificate(x,v));event(d,r,'revoked',{reason:v});store.write(d);return r},metrics(t){const d=e(store.read()),f=a=>a.filter(x=>!t||x.tenantId===t);return s.metrics({domains:f(d.managedDomains),certificates:f(d.managedCertificates)})}}}
function pg(store){async function find(db,select,t,id){return(await db.query(`${select} WHERE tenant_id=$1 AND id=$2::uuid`,[t,id])).rows[0]||null}async function mutate(t,id,setSql,params,type,data){return store.transaction(async tx=>{const q=await tx.query(`UPDATE managed_certificates SET ${setSql},updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id,...params]);if(!q.rowCount)return null;await tx.query(`INSERT INTO certificate_events(certificate_id,type,data) VALUES($1::uuid,$2,$3::jsonb)`,[id,type,JSON.stringify(data)]);return find(tx,CS,t,id)})}return{
 async createDomain(input){const x=s.normalizeDomain(input),q=await store.query(`INSERT INTO managed_domains(tenant_id,name,owner,registrar,status,expires_at,auto_renew,dns_provider,metadata) VALUES($1,$2,$3,$4,$5,NULLIF($6,'')::timestamptz,$7,$8,$9::jsonb) RETURNING id::text`,[x.tenantId,x.name,x.owner,x.registrar,x.status,x.expiresAt,x.autoRenew,x.dnsProvider,JSON.stringify(x.metadata)]);return find(store,DS,x.tenantId,q.rows[0].id)},
 async createCertificate(input){const x=s.normalizeCertificate(input),q=await store.query(`INSERT INTO managed_certificates(tenant_id,domain_id,common_name,sans,owner,issuer,serial_number,status,issued_at,expires_at,key_algorithm,key_size,auto_renew,vault_ref,last_rotated_at,next_rotation_at,metadata) SELECT $1,d.id,$3,$4::jsonb,$5,$6,$7,$8,NULLIF($9,'')::timestamptz,$10::timestamptz,$11,$12,$13,$14,NULLIF($15,'')::timestamptz,NULLIF($16,'')::timestamptz,$17::jsonb FROM managed_domains d WHERE d.tenant_id=$1 AND d.id=$2::uuid RETURNING id::text`,[x.tenantId,x.domainId,x.commonName,JSON.stringify(x.sans),x.owner,x.issuer,x.serialNumber,x.status,x.issuedAt,x.expiresAt,x.keyAlgorithm,x.keySize,x.autoRenew,x.vaultRef,x.lastRotatedAt,x.nextRotationAt,JSON.stringify(x.metadata)]);return q.rowCount?find(store,CS,x.tenantId,q.rows[0].id):null},
 async activate(t,id){return mutate(t,id,`status='active'`,[],'activated',{})},
 async renew(t,id,x){if(!x.expiresAt||!x.serialNumber)s.renewCertificate({},x);return mutate(t,id,`status='active',expires_at=$3::timestamptz,serial_number=$4,issued_at=COALESCE(NULLIF($5,'')::timestamptz,now())`,[x.expiresAt,x.serialNumber,x.issuedAt||''],'renewed',{expiresAt:x.expiresAt,serialNumber:x.serialNumber})},
 async rotate(t,id,vaultRef){if(!vaultRef)s.rotateKey({},vaultRef);return mutate(t,id,`vault_ref=$3,last_rotated_at=now(),next_rotation_at=now()+interval '90 days'`,[vaultRef],'rotated',{vaultRef})},
 async revoke(t,id,reason){if(!reason)s.revokeCertificate({},reason);return mutate(t,id,`status='revoked'`,[],'revoked',{reason})},
 async metrics(t){const[d,c]=await Promise.all([store.query(`${DS} WHERE tenant_id=$1`,[t]),store.query(`${CS} WHERE tenant_id=$1`,[t])]);return s.metrics({domains:d.rows,certificates:c.rows})}
}}
function createCertificateLifecycleRepository(store){if(store.type==='json')return json(store);if(store.type==='postgres')return pg(store);throw new Error(`Unsupported store type: ${store.type}`)}module.exports={createCertificateLifecycleRepository};
