const { makeId, now } = require('../services/id');
const { normalizeClassificationPolicyInput, normalizeRetentionPolicyInput, normalizeLegalHoldInput, normalizePurgeJobInput, normalizeGovernanceDecisionInput, evaluateRetentionEligibility, planPurgeJob, approvePurgeJob, completePurgeJob } = require('../services/dataGovernanceService');
function createDataGovernanceRepository(store){ if(store.type==='json') return createJsonDataGovernanceRepository(store); if(store.type==='postgres') return createPostgresDataGovernanceRepository(store); throw new Error(`Unsupported store type: ${store.type}`); }
function ensureGovernance(data){ if(!data.dataClassificationPolicies)data.dataClassificationPolicies=[]; if(!data.dataRetentionPolicies)data.dataRetentionPolicies=[]; if(!data.legalHolds)data.legalHolds=[]; if(!data.purgeJobs)data.purgeJobs=[]; if(!data.governanceDecisions)data.governanceDecisions=[]; return data; }
function createJsonDataGovernanceRepository(store){ return {
 listClassificationPolicies(tenantId,filters={}){return ensureGovernance(store.read()).dataClassificationPolicies.filter(x=>x.tenantId===tenantId).filter(x=>!filters.entityType||x.entityType===filters.entityType).filter(x=>!filters.status||x.status===filters.status).sort((a,b)=>String(a.name).localeCompare(String(b.name)));},
 createClassificationPolicy(tenantId,input){const data=ensureGovernance(store.read()); const row={id:makeId('classpol'),tenantId,...normalizeClassificationPolicyInput(input),createdAt:now(),updatedAt:now()}; data.dataClassificationPolicies.push(row); store.write(data); return row;},
 listRetentionPolicies(tenantId,filters={}){return ensureGovernance(store.read()).dataRetentionPolicies.filter(x=>x.tenantId===tenantId).filter(x=>!filters.entityType||x.entityType===filters.entityType).filter(x=>!filters.status||x.status===filters.status).sort((a,b)=>String(a.name).localeCompare(String(b.name)));},
 createRetentionPolicy(tenantId,input){const data=ensureGovernance(store.read()); const row={id:makeId('retpol'),tenantId,...normalizeRetentionPolicyInput(input),createdAt:now(),updatedAt:now()}; data.dataRetentionPolicies.push(row); store.write(data); return row;},
 listLegalHolds(tenantId,filters={}){return ensureGovernance(store.read()).legalHolds.filter(x=>x.tenantId===tenantId).filter(x=>!filters.entityType||x.entityType===filters.entityType).filter(x=>!filters.entityId||x.entityId===filters.entityId).filter(x=>!filters.status||x.status===filters.status).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));},
 createLegalHold(tenantId,input){const data=ensureGovernance(store.read()); const row={id:makeId('hold'),tenantId,...normalizeLegalHoldInput(input),createdAt:now(),updatedAt:now()}; data.legalHolds.push(row); store.write(data); return row;},
 releaseLegalHold(tenantId,id,input={}){const data=ensureGovernance(store.read()); const idx=data.legalHolds.findIndex(x=>x.tenantId===tenantId&&x.id===id); if(idx===-1)return null; data.legalHolds[idx]={...data.legalHolds[idx],status:'released',releasedBy:input.releasedBy||'',releasedAt:now(),updatedAt:now()}; store.write(data); return data.legalHolds[idx];},
 evaluateRetention(tenantId,input={}){const data=ensureGovernance(store.read()); const policy=input.policyId?data.dataRetentionPolicies.find(x=>x.tenantId===tenantId&&x.id===input.policyId):data.dataRetentionPolicies.find(x=>x.tenantId===tenantId&&x.status==='active'&&x.entityType===input.entityType); const holds=data.legalHolds.filter(x=>x.tenantId===tenantId); return evaluateRetentionEligibility({record:input.record||{},policy,holds,asOfDate:input.asOfDate});},
 planPurgeJob(tenantId,input={}){const data=ensureGovernance(store.read()); const policy=data.dataRetentionPolicies.find(x=>x.tenantId===tenantId&&x.id===input.policyId); const holds=data.legalHolds.filter(x=>x.tenantId===tenantId); const planned=planPurgeJob({policy,records:input.records||[],holds,asOfDate:input.asOfDate,plannedBy:input.plannedBy||''}); const row={id:makeId('purge'),tenantId,...normalizePurgeJobInput(planned),createdAt:now(),updatedAt:now()}; data.purgeJobs.push(row); store.write(data); return {job:row,candidates:planned.candidates,blocked:planned.blocked};},
 listPurgeJobs(tenantId,filters={}){return ensureGovernance(store.read()).purgeJobs.filter(x=>x.tenantId===tenantId).filter(x=>!filters.entityType||x.entityType===filters.entityType).filter(x=>!filters.status||x.status===filters.status).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));},
 approvePurgeJob(tenantId,id,approvedBy){const data=ensureGovernance(store.read()); const idx=data.purgeJobs.findIndex(x=>x.tenantId===tenantId&&x.id===id); if(idx===-1)return null; data.purgeJobs[idx]=approvePurgeJob(data.purgeJobs[idx],approvedBy); store.write(data); return data.purgeJobs[idx];},
 completePurgeJob(tenantId,id,input={}){const data=ensureGovernance(store.read()); const idx=data.purgeJobs.findIndex(x=>x.tenantId===tenantId&&x.id===id); if(idx===-1)return null; data.purgeJobs[idx]=completePurgeJob(data.purgeJobs[idx],input.processedCount,input.failedCount||0); store.write(data); return data.purgeJobs[idx];},
 recordDecision(tenantId,input){const data=ensureGovernance(store.read()); const row={id:makeId('govdec'),tenantId,...normalizeGovernanceDecisionInput(input),createdAt:now(),updatedAt:now()}; data.governanceDecisions.push(row); store.write(data); return row;},
 listDecisions(tenantId,filters={}){return ensureGovernance(store.read()).governanceDecisions.filter(x=>x.tenantId===tenantId).filter(x=>!filters.entityType||x.entityType===filters.entityType).filter(x=>!filters.result||x.result===filters.result).sort((a,b)=>String(b.decidedAt).localeCompare(String(a.decidedAt)));}
};}
function createPostgresDataGovernanceRepository(store){ async function rows(sql,params){return (await store.query(sql,params)).rows;} return {
 async listClassificationPolicies(tenantId,filters={}){const params=[tenantId];let where='WHERE tenant_id=$1'; if(filters.entityType){params.push(filters.entityType);where+=` AND entity_type=$${params.length}`;} if(filters.status){params.push(filters.status);where+=` AND status=$${params.length}`;} return rows(`SELECT id::text, tenant_id as "tenantId", code, name, description, entity_type as "entityType", classification_level as "classificationLevel", pii, financial_data as "financialData", health_data as "healthData", status, metadata, created_at as "createdAt", updated_at as "updatedAt" FROM data_classification_policies ${where} ORDER BY name`,params);},
 async createClassificationPolicy(tenantId,input){const x=normalizeClassificationPolicyInput(input); return (await rows(`INSERT INTO data_classification_policies (tenant_id, code, name, description, entity_type, classification_level, pii, financial_data, health_data, status, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) RETURNING id::text, tenant_id as "tenantId", code, name, description, entity_type as "entityType", classification_level as "classificationLevel", pii, financial_data as "financialData", health_data as "healthData", status, metadata, created_at as "createdAt", updated_at as "updatedAt"`,[tenantId,x.code,x.name,x.description,x.entityType,x.classificationLevel,x.pii,x.financialData,x.healthData,x.status,JSON.stringify(x.metadata||{})]))[0];},
 async listRetentionPolicies(tenantId,filters={}){const params=[tenantId];let where='WHERE tenant_id=$1'; if(filters.entityType){params.push(filters.entityType);where+=` AND entity_type=$${params.length}`;} if(filters.status){params.push(filters.status);where+=` AND status=$${params.length}`;} return rows(`SELECT id::text, tenant_id as "tenantId", code, name, description, entity_type as "entityType", retention_days as "retentionDays", action, status, requires_approval as "requiresApproval", metadata, created_at as "createdAt", updated_at as "updatedAt" FROM data_retention_policies ${where} ORDER BY name`,params);},
 async createRetentionPolicy(tenantId,input){const x=normalizeRetentionPolicyInput(input); return (await rows(`INSERT INTO data_retention_policies (tenant_id, code, name, description, entity_type, retention_days, action, status, requires_approval, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) RETURNING id::text, tenant_id as "tenantId", code, name, description, entity_type as "entityType", retention_days as "retentionDays", action, status, requires_approval as "requiresApproval", metadata, created_at as "createdAt", updated_at as "updatedAt"`,[tenantId,x.code,x.name,x.description,x.entityType,x.retentionDays,x.action,x.status,x.requiresApproval,JSON.stringify(x.metadata||{})]))[0];},
 async listLegalHolds(tenantId,filters={}){const params=[tenantId];let where='WHERE tenant_id=$1'; if(filters.entityType){params.push(filters.entityType);where+=` AND entity_type=$${params.length}`;} if(filters.entityId){params.push(filters.entityId);where+=` AND entity_id=$${params.length}`;} if(filters.status){params.push(filters.status);where+=` AND status=$${params.length}`;} return rows(`SELECT id::text, tenant_id as "tenantId", name, description, entity_type as "entityType", entity_id as "entityId", status, reason, created_by as "createdBy", released_by as "releasedBy", released_at as "releasedAt", metadata, created_at as "createdAt", updated_at as "updatedAt" FROM legal_holds ${where} ORDER BY created_at DESC`,params);},
 async createLegalHold(tenantId,input){const x=normalizeLegalHoldInput(input); return (await rows(`INSERT INTO legal_holds (tenant_id, name, description, entity_type, entity_id, status, reason, created_by, released_by, released_at, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,NULLIF($10,'')::timestamptz,$11::jsonb) RETURNING id::text, tenant_id as "tenantId", name, description, entity_type as "entityType", entity_id as "entityId", status, reason, created_by as "createdBy", released_by as "releasedBy", released_at as "releasedAt", metadata, created_at as "createdAt", updated_at as "updatedAt"`,[tenantId,x.name,x.description,x.entityType,x.entityId,x.status,x.reason,x.createdBy,x.releasedBy,x.releasedAt,JSON.stringify(x.metadata||{})]))[0];},
 async releaseLegalHold(tenantId,id,input={}){return (await rows(`UPDATE legal_holds SET status='released', released_by=$3, released_at=now(), updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id::text, tenant_id as "tenantId", name, description, entity_type as "entityType", entity_id as "entityId", status, reason, created_by as "createdBy", released_by as "releasedBy", released_at as "releasedAt", metadata, created_at as "createdAt", updated_at as "updatedAt"`,[tenantId,id,input.releasedBy||'']))[0]||null;},
 async evaluateRetention(tenantId,input={}){const policies=await this.listRetentionPolicies(tenantId,{entityType:input.entityType,status:'active'}); const policy=input.policyId?policies.find(x=>x.id===input.policyId):policies[0]; const holds=await this.listLegalHolds(tenantId,{entityType:input.entityType,status:'active'}); return evaluateRetentionEligibility({record:input.record||{},policy,holds,asOfDate:input.asOfDate});},
 async planPurgeJob(tenantId,input={}){const policy=(await this.listRetentionPolicies(tenantId,{status:'active'})).find(x=>x.id===input.policyId); const holds=await this.listLegalHolds(tenantId,{status:'active'}); const planned=planPurgeJob({policy,records:input.records||[],holds,asOfDate:input.asOfDate,plannedBy:input.plannedBy||''}); const x=normalizePurgeJobInput(planned); const job=(await rows(`INSERT INTO purge_jobs (tenant_id, entity_type, retention_policy_id, action, status, planned_by, approved_by, approved_at, started_at, completed_at, candidate_count, processed_count, failed_count, cutoff_date, failure_reason, metadata) VALUES ($1,$2,$3::uuid,$4,$5,$6,$7,NULLIF($8,'')::timestamptz,NULLIF($9,'')::timestamptz,NULLIF($10,'')::timestamptz,$11,$12,$13,NULLIF($14,'')::date,$15,$16::jsonb) RETURNING id::text, tenant_id as "tenantId", entity_type as "entityType", retention_policy_id::text as "retentionPolicyId", action, status, planned_by as "plannedBy", approved_by as "approvedBy", approved_at as "approvedAt", started_at as "startedAt", completed_at as "completedAt", candidate_count as "candidateCount", processed_count as "processedCount", failed_count as "failedCount", cutoff_date as "cutoffDate", failure_reason as "failureReason", metadata, created_at as "createdAt", updated_at as "updatedAt"`,[tenantId,x.entityType,x.retentionPolicyId,x.action,x.status,x.plannedBy,x.approvedBy,x.approvedAt,x.startedAt,x.completedAt,x.candidateCount,x.processedCount,x.failedCount,x.cutoffDate,x.failureReason,JSON.stringify(x.metadata||{})]))[0]; return {job,candidates:planned.candidates,blocked:planned.blocked};},
 async listPurgeJobs(tenantId,filters={}){const params=[tenantId];let where='WHERE tenant_id=$1'; if(filters.entityType){params.push(filters.entityType);where+=` AND entity_type=$${params.length}`;} if(filters.status){params.push(filters.status);where+=` AND status=$${params.length}`;} return rows(`SELECT id::text, tenant_id as "tenantId", entity_type as "entityType", retention_policy_id::text as "retentionPolicyId", action, status, planned_by as "plannedBy", approved_by as "approvedBy", approved_at as "approvedAt", started_at as "startedAt", completed_at as "completedAt", candidate_count as "candidateCount", processed_count as "processedCount", failed_count as "failedCount", cutoff_date as "cutoffDate", failure_reason as "failureReason", metadata, created_at as "createdAt", updated_at as "updatedAt" FROM purge_jobs ${where} ORDER BY created_at DESC`,params);},
 async approvePurgeJob(tenantId,id,approvedBy){return (await rows(`UPDATE purge_jobs SET status='approved', approved_by=$3, approved_at=now(), updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id::text, tenant_id as "tenantId", entity_type as "entityType", retention_policy_id::text as "retentionPolicyId", action, status, planned_by as "plannedBy", approved_by as "approvedBy", approved_at as "approvedAt", started_at as "startedAt", completed_at as "completedAt", candidate_count as "candidateCount", processed_count as "processedCount", failed_count as "failedCount", cutoff_date as "cutoffDate", failure_reason as "failureReason", metadata, created_at as "createdAt", updated_at as "updatedAt"`,[tenantId,id,approvedBy]))[0]||null;},
 async completePurgeJob(tenantId,id,input={}){const status=Number(input.failedCount||0)>0?'failed':'completed'; return (await rows(`UPDATE purge_jobs SET status=$3, processed_count=$4, failed_count=$5, completed_at=now(), updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING id::text, tenant_id as "tenantId", entity_type as "entityType", retention_policy_id::text as "retentionPolicyId", action, status, planned_by as "plannedBy", approved_by as "approvedBy", approved_at as "approvedAt", started_at as "startedAt", completed_at as "completedAt", candidate_count as "candidateCount", processed_count as "processedCount", failed_count as "failedCount", cutoff_date as "cutoffDate", failure_reason as "failureReason", metadata, created_at as "createdAt", updated_at as "updatedAt"`,[tenantId,id,status,Number(input.processedCount||0),Number(input.failedCount||0)]))[0]||null;},
 async recordDecision(tenantId,input){const x=normalizeGovernanceDecisionInput(input); return (await rows(`INSERT INTO governance_decisions (tenant_id, entity_type, entity_id, action, result, reason, policy_id, decided_by, decided_at, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::timestamptz,$10::jsonb) RETURNING id::text, tenant_id as "tenantId", entity_type as "entityType", entity_id as "entityId", action, result, reason, policy_id as "policyId", decided_by as "decidedBy", decided_at as "decidedAt", metadata, created_at as "createdAt", updated_at as "updatedAt"`,[tenantId,x.entityType,x.entityId,x.action,x.result,x.reason,x.policyId,x.decidedBy,x.decidedAt,JSON.stringify(x.metadata||{})]))[0];},
 async listDecisions(tenantId,filters={}){const params=[tenantId];let where='WHERE tenant_id=$1'; if(filters.entityType){params.push(filters.entityType);where+=` AND entity_type=$${params.length}`;} if(filters.result){params.push(filters.result);where+=` AND result=$${params.length}`;} return rows(`SELECT id::text, tenant_id as "tenantId", entity_type as "entityType", entity_id as "entityId", action, result, reason, policy_id as "policyId", decided_by as "decidedBy", decided_at as "decidedAt", metadata, created_at as "createdAt", updated_at as "updatedAt" FROM governance_decisions ${where} ORDER BY decided_at DESC`,params);}
};}
module.exports={ createDataGovernanceRepository };
