const{makeId,now}=require('../services/id');const s=require('../services/enterpriseSecretsService');
const SS=`SELECT id::text,tenant_id AS "tenantId",name,type,owner,application,environment,vault_provider AS "vaultProvider",vault_ref AS "vaultRef",status,rotation_days AS "rotationDays",last_rotated_at AS "lastRotatedAt",next_rotation_at AS "nextRotationAt",expires_at AS "expiresAt",key_algorithm AS "keyAlgorithm",key_purpose AS "keyPurpose",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM enterprise_secrets`;
function e(d){d.enterpriseSecrets||=[];d.secretAuditEvents||=[];return d}function u(a,t,id,f){const i=a.findIndex(x=>x.id===id&&x.tenantId===t);if(i<0)return null;a[i]=f(a[i]);return a[i]}
function json(store){function event(d,r,type,actor,data={}){if(r)d.secretAuditEvents.push({id:makeId('secaudit'),tenantId:r.tenantId,secretId:r.id,type,actor,data,createdAt:now()})}return{createSecret(x){const d=e(store.read()),r={id:makeId('secret'),...s.normalizeSecret(x),createdAt:now(),updatedAt:now()};d.enterpriseSecrets.push(r);event(d,r,'created',x.actor||'system');store.write(d);return r},schedule(t,id,date,actor){const d=e(store.read()),r=u(d.enterpriseSecrets,t,id,x=>s.scheduleRotation(x,date));event(d,r,'scheduled',actor,{date});store.write(d);return r},begin(t,id,actor){const d=e(store.read()),r=u(d.enterpriseSecrets,t,id,x=>s.beginRotation(x,actor));event(d,r,'rotation_started',actor);store.write(d);return r},complete(t,id,ref,actor){const d=e(store.read()),r=u(d.enterpriseSecrets,t,id,x=>s.completeRotation(x,ref,actor));event(d,r,'rotation_completed',actor,{vaultRef:ref});store.write(d);return r},revoke(t,id,reason,actor){const d=e(store.read()),r=u(d.enterpriseSecrets,t,id,x=>s.revokeSecret(x,reason,actor));event(d,r,'revoked',actor,{reason});store.write(d);return r},metrics(t){const d=e(store.read());return s.metrics(d.enterpriseSecrets.filter(x=>!t||x.tenantId===t))}}}
function pg(store){async function find(db,t,id){return(await db.query(`${SS} WHERE tenant_id=$1 AND id=$2::uuid`,[t,id])).rows[0]||null}async function mutate(t,id,setSql,params,type,actor,data){if(!actor)throw require('../errors/domainError').validationError('actor is required');return store.transaction(async tx=>{const q=await tx.query(`UPDATE enterprise_secrets SET ${setSql},updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id,...params]);if(!q.rowCount)return null;await tx.query(`INSERT INTO secret_audit_events(secret_id,type,actor,data) VALUES($1::uuid,$2,$3,$4::jsonb)`,[id,type,actor,JSON.stringify(data||{})]);return find(tx,t,id)})}return{
 async createSecret(input){const x=s.normalizeSecret(input),actor=input.actor||'system';return store.transaction(async tx=>{const q=await tx.query(`INSERT INTO enterprise_secrets(tenant_id,name,type,owner,application,environment,vault_provider,vault_ref,status,rotation_days,last_rotated_at,next_rotation_at,expires_at,key_algorithm,key_purpose,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,NULLIF($11,'')::timestamptz,NULLIF($12,'')::timestamptz,NULLIF($13,'')::timestamptz,$14,$15,$16::jsonb) RETURNING id::text`,[x.tenantId,x.name,x.type,x.owner,x.application,x.environment,x.vaultProvider,x.vaultRef,x.status,x.rotationDays,x.lastRotatedAt,x.nextRotationAt,x.expiresAt,x.keyAlgorithm,x.keyPurpose,JSON.stringify(x.metadata)]);const id=q.rows[0].id;await tx.query(`INSERT INTO secret_audit_events(secret_id,type,actor,data) VALUES($1::uuid,'created',$2,'{}'::jsonb)`,[id,actor]);return find(tx,x.tenantId,id)})},
 async schedule(t,id,date,actor){if(!date)s.scheduleRotation({},date);return mutate(t,id,`next_rotation_at=$3::timestamptz,status='active'`,[date],'scheduled',actor,{date})},
 async begin(t,id,actor){return mutate(t,id,`status='rotating'`,[],'rotation_started',actor,{})},
 async complete(t,id,ref,actor){if(!ref||!actor)s.completeRotation({rotationDays:90},ref,actor);return mutate(t,id,`status='active',vault_ref=$3,last_rotated_at=now(),next_rotation_at=now()+(rotation_days*interval '1 day')`,[ref],'rotation_completed',actor,{vaultRef:ref})},
 async revoke(t,id,reason,actor){if(!reason||!actor)s.revokeSecret({},reason,actor);return mutate(t,id,`status='revoked'`,[],'revoked',actor,{reason})},
 async metrics(t){return s.metrics((await store.query(`${SS} WHERE tenant_id=$1`,[t])).rows)}
}}
function createEnterpriseSecretsRepository(store){if(store.type==='json')return json(store);if(store.type==='postgres')return pg(store);throw new Error(`Unsupported store type: ${store.type}`)}module.exports={createEnterpriseSecretsRepository};
