const{makeId,now}=require('../services/id');const s=require('../services/enterpriseAssetInventoryService');
const AS=`SELECT id::text,tenant_id AS "tenantId",asset_tag AS "assetTag",name,type,owner,custodian,department,status,manufacturer,model,serial_number AS "serialNumber",location,purchased_at AS "purchasedAt",warranty_expires_at AS "warrantyExpiresAt",end_of_life_at AS "endOfLifeAt",retired_at AS "retiredAt",disposed_at AS "disposedAt",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM enterprise_assets`;
const SS=`SELECT id::text,tenant_id AS "tenantId",asset_id::text AS "assetId",product,version,publisher,license_key_ref AS "licenseKeyRef",installed_at AS "installedAt",end_of_support_at AS "endOfSupportAt",status,created_at AS "createdAt",updated_at AS "updatedAt" FROM asset_software`;
const SUB=`SELECT id::text,tenant_id AS "tenantId",provider,product,owner,seats,annual_cost::float8 AS "annualCost",renewal_at AS "renewalAt",status,data_classification AS "dataClassification",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM saas_subscriptions`;
function e(d){d.enterpriseAssets||=[];d.assetSoftware||=[];d.saasSubscriptions||=[];return d}function u(a,t,id,f){const i=a.findIndex(x=>x.id===id&&x.tenantId===t);if(i<0)return null;a[i]=f(a[i]);return a[i]}
function json(store){return{createAsset(x){const d=e(store.read()),r={id:makeId('asset'),...s.normalizeAsset(x),createdAt:now(),updatedAt:now()};d.enterpriseAssets.push(r);store.write(d);return r},transferOwnership(t,id,o,c){const d=e(store.read()),r=u(d.enterpriseAssets,t,id,x=>s.transferOwnership(x,o,c));store.write(d);return r},transitionLifecycle(t,id,v){const d=e(store.read()),r=u(d.enterpriseAssets,t,id,x=>s.transitionLifecycle(x,v));store.write(d);return r},createSoftware(x){const d=e(store.read());if(!d.enterpriseAssets.some(a=>a.id===x.assetId&&a.tenantId===x.tenantId))return null;const r={id:makeId('soft'),...s.normalizeSoftware(x),createdAt:now(),updatedAt:now()};d.assetSoftware.push(r);store.write(d);return r},createSubscription(x){const d=e(store.read()),r={id:makeId('saas'),...s.normalizeSubscription(x),createdAt:now(),updatedAt:now()};d.saasSubscriptions.push(r);store.write(d);return r},metrics(t){const d=e(store.read()),f=a=>a.filter(x=>!t||x.tenantId===t);return s.metrics({assets:f(d.enterpriseAssets),software:f(d.assetSoftware),subscriptions:f(d.saasSubscriptions)})}}}
function pg(store){async function find(select,t,id){return(await store.query(`${select} WHERE tenant_id=$1 AND id=$2::uuid`,[t,id])).rows[0]||null}return{
 async createAsset(input){const x=s.normalizeAsset(input),q=await store.query(`INSERT INTO enterprise_assets(tenant_id,asset_tag,name,type,owner,custodian,department,status,manufacturer,model,serial_number,location,purchased_at,warranty_expires_at,end_of_life_at,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NULLIF($13,'')::timestamptz,NULLIF($14,'')::timestamptz,NULLIF($15,'')::timestamptz,$16::jsonb) RETURNING id::text`,[x.tenantId,x.assetTag,x.name,x.type,x.owner,x.custodian,x.department,x.status,x.manufacturer,x.model,x.serialNumber,x.location,x.purchasedAt,x.warrantyExpiresAt,x.endOfLifeAt,JSON.stringify(x.metadata)]);return find(AS,x.tenantId,q.rows[0].id)},
 async transferOwnership(t,id,owner,custodian=''){if(!owner)s.transferOwnership({},owner,custodian);const q=await store.query(`UPDATE enterprise_assets SET owner=$3,custodian=$4,updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id,owner,custodian]);return q.rowCount?find(AS,t,id):null},
 async transitionLifecycle(t,id,status){if(!s.STATES.includes(status))s.transitionLifecycle({},status);const q=await store.query(`UPDATE enterprise_assets SET status=$3,retired_at=CASE WHEN $3='retired' THEN now() ELSE retired_at END,disposed_at=CASE WHEN $3='disposed' THEN now() ELSE disposed_at END,updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id,status]);return q.rowCount?find(AS,t,id):null},
 async createSoftware(input){const x=s.normalizeSoftware(input),q=await store.query(`INSERT INTO asset_software(tenant_id,asset_id,product,version,publisher,license_key_ref,installed_at,end_of_support_at,status) SELECT $1,a.id,$3,$4,$5,$6,NULLIF($7,'')::timestamptz,NULLIF($8,'')::timestamptz,$9 FROM enterprise_assets a WHERE a.tenant_id=$1 AND a.id=$2::uuid RETURNING id::text`,[x.tenantId,x.assetId,x.product,x.version,x.publisher,x.licenseKeyRef,x.installedAt,x.endOfSupportAt,x.status]);return q.rowCount?find(SS,x.tenantId,q.rows[0].id):null},
 async createSubscription(input){const x=s.normalizeSubscription(input),q=await store.query(`INSERT INTO saas_subscriptions(tenant_id,provider,product,owner,seats,annual_cost,renewal_at,status,data_classification,metadata) VALUES($1,$2,$3,$4,$5,$6,NULLIF($7,'')::timestamptz,$8,$9,$10::jsonb) RETURNING id::text`,[x.tenantId,x.provider,x.product,x.owner,x.seats,x.annualCost,x.renewalAt,x.status,x.dataClassification,JSON.stringify(x.metadata)]);return find(SUB,x.tenantId,q.rows[0].id)},
 async metrics(t){const[a,sw,sub]=await Promise.all([store.query(`${AS} WHERE tenant_id=$1`,[t]),store.query(`${SS} WHERE tenant_id=$1`,[t]),store.query(`${SUB} WHERE tenant_id=$1`,[t])]);return s.metrics({assets:a.rows,software:sw.rows,subscriptions:sub.rows})}
}}
function createEnterpriseAssetInventoryRepository(store){if(store.type==='json')return json(store);if(store.type==='postgres')return pg(store);throw new Error(`Unsupported store type: ${store.type}`)}module.exports={createEnterpriseAssetInventoryRepository};
