const s=require('../services/policyManagementService');
const P=`SELECT id::text,tenant_id AS "tenantId",code,title,category,owner,status,current_version_id::text AS "currentVersionId",published_at AS "publishedAt",expires_at AS "expiresAt",review_at AS "reviewAt",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM governance_policies`;
const V=`SELECT id::text,tenant_id AS "tenantId",policy_id::text AS "policyId",version,content,summary,status,created_by AS "createdBy",submitted_at AS "submittedAt",approver,approval_comments AS "approvalComments",approved_at AS "approvedAt",published_at AS "publishedAt",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM governance_policy_versions`;
const A=`SELECT id::text,tenant_id AS "tenantId",policy_id::text AS "policyId",version_id::text AS "versionId",subject_id AS "subjectId",status,due_at AS "dueAt",acknowledged_at AS "acknowledgedAt",attestation,metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM governance_policy_acknowledgements`;
const E=`SELECT id::text,tenant_id AS "tenantId",policy_id::text AS "policyId",requestor,reason,status,expires_at AS "expiresAt",decided_by AS "decidedBy",decided_at AS "decidedAt",comments,metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM governance_policy_exceptions`;
function createPostgresPolicyManagementRepository(store){async function find(db,q,t,id){return(await db.query(`${q} WHERE tenant_id=$1 AND id=$2::uuid`,[t,id])).rows[0]||null}return{
async createPolicy(i){const x=s.normalizePolicy(i),r=await store.query(`INSERT INTO governance_policies(tenant_id,code,title,category,owner,status,expires_at,review_at,metadata) VALUES($1,$2,$3,$4,$5,$6,NULLIF($7,'')::timestamptz,NULLIF($8,'')::timestamptz,$9::jsonb) RETURNING id::text`,[x.tenantId,x.code,x.title,x.category,x.owner,x.status,x.expiresAt,x.reviewAt,JSON.stringify(x.metadata)]);return find(store,P,x.tenantId,r.rows[0].id)},
async createVersion(i){const x=s.normalizeVersion(i),r=await store.query(`INSERT INTO governance_policy_versions(tenant_id,policy_id,version,content,summary,status,created_by,metadata) SELECT $1,p.id,$3,$4,$5,$6,$7,$8::jsonb FROM governance_policies p WHERE p.tenant_id=$1 AND p.id=$2::uuid RETURNING id::text`,[x.tenantId,x.policyId,x.version,x.content,x.summary,x.status,x.createdBy,JSON.stringify(x.metadata)]);return r.rowCount?find(store,V,x.tenantId,r.rows[0].id):null},
async submitVersion(t,id){const r=await store.query(`UPDATE governance_policy_versions SET status='in_review',submitted_at=now(),updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id]);return r.rowCount?find(store,V,t,id):null},
async decideVersion(t,id,d,by,c=''){s.decideVersion({},d,by,c);const r=await store.query(`UPDATE governance_policy_versions SET status=$3,approver=$4,approval_comments=$5,approved_at=CASE WHEN $3='approved' THEN now() ELSE NULL END,updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id,d,by,c]);return r.rowCount?find(store,V,t,id):null},
async publishVersion(t,id){return store.transaction(async tx=>{const v=await tx.query(`UPDATE governance_policy_versions SET status='published',published_at=now(),updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid AND status='approved' RETURNING policy_id::text`,[t,id]);if(!v.rowCount)return null;const p=await tx.query(`UPDATE governance_policies SET status='published',current_version_id=$2::uuid,published_at=now(),updated_at=now() WHERE tenant_id=$1 AND id=$3::uuid RETURNING id::text`,[t,id,v.rows[0].policy_id]);if(!p.rowCount)throw new Error('Policy parent not found for tenant');return{version:await find(tx,V,t,id),policy:await find(tx,P,t,p.rows[0].id)}})},
async createAcknowledgement(i){const x=s.normalizeAcknowledgement(i),r=await store.query(`INSERT INTO governance_policy_acknowledgements(tenant_id,policy_id,version_id,subject_id,status,due_at,attestation,metadata) SELECT $1,p.id,v.id,$4,$5,$6::timestamptz,$7,$8::jsonb FROM governance_policies p JOIN governance_policy_versions v ON v.policy_id=p.id AND v.tenant_id=p.tenant_id WHERE p.tenant_id=$1 AND p.id=$2::uuid AND v.id=$3::uuid RETURNING id::text`,[x.tenantId,x.policyId,x.versionId,x.subjectId,x.status,x.dueAt,x.attestation,JSON.stringify(x.metadata)]);return r.rowCount?find(store,A,x.tenantId,r.rows[0].id):null},
async acknowledge(t,id,a){const r=await store.query(`UPDATE governance_policy_acknowledgements SET status='acknowledged',attestation=$3,acknowledged_at=now(),updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id,a||'']);return r.rowCount?find(store,A,t,id):null},
async createException(i){const x=s.normalizeException(i),r=await store.query(`INSERT INTO governance_policy_exceptions(tenant_id,policy_id,requestor,reason,status,expires_at,metadata) SELECT $1,p.id,$3,$4,$5,$6::timestamptz,$7::jsonb FROM governance_policies p WHERE p.tenant_id=$1 AND p.id=$2::uuid RETURNING id::text`,[x.tenantId,x.policyId,x.requestor,x.reason,x.status,x.expiresAt,JSON.stringify(x.metadata)]);return r.rowCount?find(store,E,x.tenantId,r.rows[0].id):null},
async decideException(t,id,d,by,c=''){s.decideException({},d,by,c);const r=await store.query(`UPDATE governance_policy_exceptions SET status=$3,decided_by=$4,comments=$5,decided_at=now(),updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id,d,by,c]);return r.rowCount?find(store,E,t,id):null},
async metrics(t){const[p,a,e]=await Promise.all([store.query(`${P} WHERE tenant_id=$1`,[t]),store.query(`${A} WHERE tenant_id=$1`,[t]),store.query(`${E} WHERE tenant_id=$1`,[t])]);return s.metrics({policies:p.rows,acknowledgements:a.rows,exceptions:e.rows})}
}}
module.exports={createPostgresPolicyManagementRepository};
