const {makeId,now}=require('../services/id');const {validationError}=require('../errors/domainError');
function createServiceMarketplaceRepository(store){if(store.type==='json')return createJson(store);if(store.type==='postgres')return createPostgres(store);throw new Error(`Unsupported store type: ${store.type}`);}
function ensure(data){if(!data.serviceMarketplaceItems)data.serviceMarketplaceItems=[];if(!data.serviceMarketplaceInstallations)data.serviceMarketplaceInstallations=[];return data;}
function createJson(store){return{
 listCatalog(){return ensure(store.read()).serviceMarketplaceItems.filter(row=>row.status!=='hidden').sort((a,b)=>a.name.localeCompare(b.name));},listInstallations(tenantId){return ensure(store.read()).serviceMarketplaceInstallations.filter(row=>row.tenantId===tenantId).sort((a,b)=>String(b.installedAt).localeCompare(String(a.installedAt)));},
 install(tenantId,input){const data=ensure(store.read());const item=data.serviceMarketplaceItems.find(row=>row.id===input.itemId&&row.status!=='hidden');if(!item)throw validationError('Marketplace item not found');const existing=data.serviceMarketplaceInstallations.find(row=>row.tenantId===tenantId&&row.itemId===item.id);if(existing){existing.status='active';existing.updatedAt=now();store.write(data);return existing;}const stamp=now();const row={id:makeId('marketinstall'),tenantId,itemId:item.id,status:'active',configuration:{},installedBy:input.installedBy||'',installedAt:stamp,updatedAt:stamp};data.serviceMarketplaceInstallations.push(row);store.write(data);return row;},
 uninstall(tenantId,id){const data=ensure(store.read());const before=data.serviceMarketplaceInstallations.length;data.serviceMarketplaceInstallations=data.serviceMarketplaceInstallations.filter(row=>!(row.tenantId===tenantId&&row.id===id));if(before===data.serviceMarketplaceInstallations.length)return false;store.write(data);return true;}
};}
const itemSelect=`SELECT id::text,code,name,item_type AS "itemType",category,description,provider,industries,features,accent_color AS "accentColor",status,created_at AS "createdAt",updated_at AS "updatedAt" FROM service_marketplace_items`;const installSelect=`SELECT id::text,tenant_id AS "tenantId",item_id::text AS "itemId",status,configuration,installed_by AS "installedBy",installed_at AS "installedAt",updated_at AS "updatedAt" FROM service_marketplace_installations`;
function createPostgres(store){return{
 async listCatalog(){return(await store.query(`${itemSelect} WHERE status<>'hidden' ORDER BY name`)).rows;},async listInstallations(tenantId){return(await store.query(`${installSelect} WHERE tenant_id=$1 ORDER BY installed_at DESC`,[tenantId])).rows;},
 async install(tenantId,input){const item=(await store.query(`${itemSelect} WHERE id=$1 AND status<>'hidden' LIMIT 1`,[input.itemId])).rows[0];if(!item)throw validationError('Marketplace item not found');return(await store.query(`INSERT INTO service_marketplace_installations(tenant_id,item_id,status,installed_by) VALUES($1,$2,'active',$3) ON CONFLICT(tenant_id,item_id) DO UPDATE SET status='active',updated_at=now() RETURNING id::text,tenant_id AS "tenantId",item_id::text AS "itemId",status,configuration,installed_by AS "installedBy",installed_at AS "installedAt",updated_at AS "updatedAt"`,[tenantId,input.itemId,input.installedBy||''])).rows[0];},async uninstall(tenantId,id){return(await store.query('DELETE FROM service_marketplace_installations WHERE tenant_id=$1 AND id=$2',[tenantId,id])).rowCount>0;}
};}
module.exports={createServiceMarketplaceRepository};
