const { makeId, now } = require('../services/id');
const svc = require('../services/soarAutomationService');
function createSoarAutomationRepository(store){if(store.type==='json')return createJsonSoarAutomationRepository(store);if(store.type==='postgres')return createPostgresSoarAutomationRepository();throw new Error(`Unsupported store type: ${store.type}`)}
function ensure(d){d.soarPlaybooks||=[];d.soarSteps||=[];d.soarConnectors||=[];d.soarCases||=[];d.soarRuns||=[];d.soarApprovals||=[];d.soarLogs||=[];return d}
function upd(rows,id,fn){const i=rows.findIndex(x=>x.id===id);if(i===-1)return null;rows[i]=fn(rows[i]);return rows[i]}
function createJsonSoarAutomationRepository(store){return{
createPlaybook(i){const d=ensure(store.read());const r={id:makeId('pb'),...svc.normalizePlaybookInput(i),createdAt:now(),updatedAt:now()};d.soarPlaybooks.push(r);store.write(d);return r},listPlaybooks(f={}){return ensure(store.read()).soarPlaybooks.filter(x=>!f.tenantId||x.tenantId===f.tenantId).filter(x=>!f.status||x.status===f.status)},activatePlaybook(id){const d=ensure(store.read());const r=upd(d.soarPlaybooks,id,svc.activatePlaybook);store.write(d);return r},disablePlaybook(id){const d=ensure(store.read());const r=upd(d.soarPlaybooks,id,svc.disablePlaybook);store.write(d);return r},
createStep(i){const d=ensure(store.read());const r={id:makeId('pbstep'),...svc.normalizeStepInput(i),createdAt:now(),updatedAt:now()};d.soarSteps.push(r);store.write(d);return r},listSteps(pid){return ensure(store.read()).soarSteps.filter(x=>x.playbookId===pid).sort(svc.stepSort)},
createConnector(i){const d=ensure(store.read());const r={id:makeId('soarconn'),...svc.normalizeConnectorInput(i),createdAt:now(),updatedAt:now()};d.soarConnectors.push(r);store.write(d);return r},listConnectors(f={}){return ensure(store.read()).soarConnectors.filter(x=>!f.tenantId||x.tenantId===f.tenantId).filter(x=>!f.status||x.status===f.status)},
createCase(i){const d=ensure(store.read());const r={id:makeId('soarcase'),...svc.normalizeCaseInput(i),createdAt:now(),updatedAt:now()};r.caseNumber=r.caseNumber||`SOAR-${String(d.soarCases.length+1).padStart(6,'0')}`;d.soarCases.push(r);store.write(d);return r},closeCase(id){const d=ensure(store.read());const r=upd(d.soarCases,id,svc.closeCase);store.write(d);return r},
createRun(i){const d=ensure(store.read());const r={id:makeId('soarrun'),...svc.normalizeRunInput(i),createdAt:now(),updatedAt:now()};d.soarRuns.push(r);store.write(d);return r},startRun(id){const d=ensure(store.read());const run=d.soarRuns.find(x=>x.id===id);if(!run)return null;const first=d.soarSteps.filter(x=>x.playbookId===run.playbookId).sort(svc.stepSort)[0];const r=upd(d.soarRuns,id,x=>svc.startRun(x,first?first.id:''));store.write(d);return r},waitApproval(id,stepId=''){const d=ensure(store.read());const r=upd(d.soarRuns,id,x=>svc.waitApproval(x,stepId));store.write(d);return r},completeRun(id,out={}){const d=ensure(store.read());const r=upd(d.soarRuns,id,x=>svc.completeRun(x,out));store.write(d);return r},failRun(id,reason){const d=ensure(store.read());const r=upd(d.soarRuns,id,x=>svc.failRun(x,reason));store.write(d);return r},rollbackRun(id,reason=''){const d=ensure(store.read());const r=upd(d.soarRuns,id,x=>svc.rollbackRun(x,reason));store.write(d);return r},
createApproval(i){const d=ensure(store.read());const r={id:makeId('soarapp'),...svc.normalizeApprovalInput(i),createdAt:now(),updatedAt:now()};d.soarApprovals.push(r);store.write(d);return r},approveApproval(id,c=''){const d=ensure(store.read());const r=upd(d.soarApprovals,id,x=>svc.approveRunApproval(x,c));if(r)upd(d.soarRuns,r.runId,x=>svc.startRun(x,r.stepId));store.write(d);return r},rejectApproval(id,c=''){const d=ensure(store.read());const r=upd(d.soarApprovals,id,x=>svc.rejectRunApproval(x,c));if(r)upd(d.soarRuns,r.runId,x=>svc.failRun(x,'Approval rejected'));store.write(d);return r},
createLog(i){const d=ensure(store.read());const r={id:makeId('soarlog'),...svc.normalizeLogInput(i)};d.soarLogs.push(r);store.write(d);return r},listLogs(runId){return ensure(store.read()).soarLogs.filter(x=>x.runId===runId).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))},metrics(t){const d=ensure(store.read());return svc.soarMetrics({playbooks:d.soarPlaybooks.filter(x=>!t||x.tenantId===t),connectors:d.soarConnectors.filter(x=>!t||x.tenantId===t),cases:d.soarCases.filter(x=>!t||x.tenantId===t),runs:d.soarRuns.filter(x=>!t||x.tenantId===t),approvals:d.soarApprovals.filter(x=>!t||x.tenantId===t),logs:d.soarLogs.filter(x=>!t||x.tenantId===t)})}}}
function createPostgresSoarAutomationRepository(){return{async createPlaybook(i){return{id:'postgres-playbook-placeholder',...svc.normalizePlaybookInput(i)}},async listPlaybooks(){return[]},async activatePlaybook(){return null},async disablePlaybook(){return null},async createStep(i){return{id:'postgres-step-placeholder',...svc.normalizeStepInput(i)}},async listSteps(){return[]},async createConnector(i){return{id:'postgres-connector-placeholder',...svc.normalizeConnectorInput(i)}},async listConnectors(){return[]},async createCase(i){return{id:'postgres-case-placeholder',...svc.normalizeCaseInput(i)}},async closeCase(){return null},async createRun(i){return{id:'postgres-run-placeholder',...svc.normalizeRunInput(i)}},async startRun(){return null},async waitApproval(){return null},async completeRun(){return null},async failRun(){return null},async rollbackRun(){return null},async createApproval(i){return{id:'postgres-approval-placeholder',...svc.normalizeApprovalInput(i)}},async approveApproval(){return null},async rejectApproval(){return null},async createLog(i){return{id:'postgres-log-placeholder',...svc.normalizeLogInput(i)}},async listLogs(){return[]},async metrics(){return svc.soarMetrics({})}}}
module.exports={createSoarAutomationRepository};
