const { makeId, now } = require('../services/id');

function ensure(data) { if (!data.subscriberStripeAccounts) data.subscriberStripeAccounts = []; return data; }
function createSubscriberStripeAccountRepository(store) {
  if (store.type === 'json') return {
    get(tenantId) { return ensure(store.read()).subscriberStripeAccounts.find(x => x.tenantId === tenantId && x.status !== 'disconnected') || null; },
    findByStripeAccountId(accountId) { return ensure(store.read()).subscriberStripeAccounts.find(x => x.stripeAccountId === accountId && x.status !== 'disconnected') || null; },
    upsert(tenantId, input) { const data=ensure(store.read()); let row=data.subscriberStripeAccounts.find(x=>x.tenantId===tenantId); const stamp=now(); if(!row){row={id:makeId('sca'),tenantId,accountType:'express',status:'pending',chargesEnabled:false,payoutsEnabled:false,detailsSubmitted:false,country:'',defaultCurrency:'usd',businessType:'',metadata:{},createdAt:stamp};data.subscriberStripeAccounts.push(row);} Object.assign(row,input,{tenantId,updatedAt:stamp}); store.write(data); return row; },
    disconnect(tenantId) { return this.upsert(tenantId,{status:'disconnected',chargesEnabled:false,payoutsEnabled:false,disconnectedAt:now()}); }
  };
  return {
    async get(tenantId) { const r=await store.query(`SELECT tenant_id AS "tenantId",stripe_account_id AS "stripeAccountId",account_type AS "accountType",status,charges_enabled AS "chargesEnabled",payouts_enabled AS "payoutsEnabled",details_submitted AS "detailsSubmitted",country,default_currency AS "defaultCurrency",business_type AS "businessType",disconnected_at AS "disconnectedAt",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM subscriber_stripe_accounts WHERE tenant_id=$1 AND status<>'disconnected' LIMIT 1`,[tenantId]); return r.rows[0]||null; },
    async findByStripeAccountId(accountId) { const r=await store.query(`SELECT tenant_id AS "tenantId",stripe_account_id AS "stripeAccountId",status,charges_enabled AS "chargesEnabled",payouts_enabled AS "payoutsEnabled",details_submitted AS "detailsSubmitted" FROM subscriber_stripe_accounts WHERE stripe_account_id=$1 AND status<>'disconnected' LIMIT 1`,[accountId]); return r.rows[0]||null; },
    async upsert(tenantId,input) { const r=await store.query(`INSERT INTO subscriber_stripe_accounts(tenant_id,stripe_account_id,status,charges_enabled,payouts_enabled,details_submitted,country,default_currency,business_type,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) ON CONFLICT(tenant_id) DO UPDATE SET stripe_account_id=EXCLUDED.stripe_account_id,status=EXCLUDED.status,charges_enabled=EXCLUDED.charges_enabled,payouts_enabled=EXCLUDED.payouts_enabled,details_submitted=EXCLUDED.details_submitted,country=EXCLUDED.country,default_currency=EXCLUDED.default_currency,business_type=EXCLUDED.business_type,metadata=EXCLUDED.metadata,disconnected_at=NULL,updated_at=now() RETURNING tenant_id AS "tenantId",stripe_account_id AS "stripeAccountId",status,charges_enabled AS "chargesEnabled",payouts_enabled AS "payoutsEnabled",details_submitted AS "detailsSubmitted",country,default_currency AS "defaultCurrency",business_type AS "businessType",metadata`,[tenantId,input.stripeAccountId,input.status||'pending',Boolean(input.chargesEnabled),Boolean(input.payoutsEnabled),Boolean(input.detailsSubmitted),input.country||'',input.defaultCurrency||'usd',input.businessType||'',JSON.stringify(input.metadata||{})]); return r.rows[0]; },
    async disconnect(tenantId) { const r=await store.query(`UPDATE subscriber_stripe_accounts SET status='disconnected',charges_enabled=false,payouts_enabled=false,disconnected_at=now(),updated_at=now() WHERE tenant_id=$1 RETURNING tenant_id AS "tenantId",stripe_account_id AS "stripeAccountId",status,disconnected_at AS "disconnectedAt"`,[tenantId]); return r.rows[0]||null; }
  };
}
module.exports={createSubscriberStripeAccountRepository};
