const{makeId,now}=require('../services/id');const s=require('../services/vendorRiskManagementService');
const VS=`SELECT id::text,tenant_id AS "tenantId",name,owner,criticality,status,services,data_access AS "dataAccess",renewal_at AS "renewalAt",risk_score::float8 AS "riskScore",risk_band AS "riskBand",next_review_at AS "nextReviewAt",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM risk_vendors`;
const QS=`SELECT id::text,tenant_id AS "tenantId",vendor_id::text AS "vendorId",name,status,questions,answers,score::float8,submitted_at AS "submittedAt",reviewed_at AS "reviewedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM vendor_questionnaires`;
const DS=`SELECT id::text,tenant_id AS "tenantId",vendor_id::text AS "vendorId",type,reference,period_end AS "periodEnd",expires_at AS "expiresAt",status,exceptions,created_at AS "createdAt",updated_at AS "updatedAt" FROM vendor_assurance_documents`;
const RS=`SELECT id::text,tenant_id AS "tenantId",vendor_id::text AS "vendorId",reviewer,score::float8,risk_band AS "riskBand",findings,status,reviewed_at AS "reviewedAt",next_review_at AS "nextReviewAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM vendor_risk_reviews`;
function e(d){d.riskVendors||=[];d.vendorQuestionnaires||=[];d.vendorAssuranceDocuments||=[];d.vendorRiskReviews||=[];return d}function u(a,t,id,f){const i=a.findIndex(x=>x.id===id&&x.tenantId===t);if(i<0)return null;a[i]=f(a[i]);return a[i]}function v(d,t,id){return d.riskVendors.some(x=>x.id===id&&x.tenantId===t)}
function json(store){return{createVendor(x){const d=e(store.read()),r={id:makeId('vendor'),...s.normalizeVendor(x),createdAt:now(),updatedAt:now()};d.riskVendors.push(r);store.write(d);return r},createQuestionnaire(x){const d=e(store.read());if(!v(d,x.tenantId,x.vendorId))return null;const r={id:makeId('vq'),...s.normalizeQuestionnaire(x),createdAt:now(),updatedAt:now()};d.vendorQuestionnaires.push(r);store.write(d);return r},submitQuestionnaire(t,id,a){const d=e(store.read()),r=u(d.vendorQuestionnaires,t,id,x=>s.submitQuestionnaire(x,a));store.write(d);return r},reviewQuestionnaire(t,id,n){const d=e(store.read()),r=u(d.vendorQuestionnaires,t,id,x=>s.reviewQuestionnaire(x,n));store.write(d);return r},createDocument(x){const d=e(store.read());if(!v(d,x.tenantId,x.vendorId))return null;const r={id:makeId('vdoc'),...s.normalizeDocument(x),createdAt:now(),updatedAt:now()};d.vendorAssuranceDocuments.push(r);store.write(d);return r},createReview(x){const d=e(store.read());if(!v(d,x.tenantId,x.vendorId))return null;const r={id:makeId('vrev'),...s.normalizeReview(x),createdAt:now(),updatedAt:now()};d.vendorRiskReviews.push(r);store.write(d);return r},metrics(t){const d=e(store.read()),f=a=>a.filter(x=>!t||x.tenantId===t);return s.metrics({vendors:f(d.riskVendors),questionnaires:f(d.vendorQuestionnaires),documents:f(d.vendorAssuranceDocuments),reviews:f(d.vendorRiskReviews)})}}}
function pg(store){async function find(select,t,id){return(await store.query(`${select} WHERE tenant_id=$1 AND id=$2::uuid`,[t,id])).rows[0]||null}return{
 async createVendor(input){const x=s.normalizeVendor(input),q=await store.query(`INSERT INTO risk_vendors(tenant_id,name,owner,criticality,status,services,data_access,renewal_at,risk_score,risk_band,next_review_at,metadata) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,NULLIF($8,'')::timestamptz,$9,$10,NULLIF($11,'')::timestamptz,$12::jsonb) RETURNING id::text`,[x.tenantId,x.name,x.owner,x.criticality,x.status,JSON.stringify(x.services),JSON.stringify(x.dataAccess),x.renewalAt,x.riskScore,x.riskBand,x.nextReviewAt,JSON.stringify(x.metadata)]);return find(VS,x.tenantId,q.rows[0].id)},
 async createQuestionnaire(input){const x=s.normalizeQuestionnaire(input),q=await store.query(`INSERT INTO vendor_questionnaires(tenant_id,vendor_id,name,status,questions,answers,score) SELECT $1,v.id,$3,$4,$5::jsonb,$6::jsonb,$7 FROM risk_vendors v WHERE v.tenant_id=$1 AND v.id=$2::uuid RETURNING id::text`,[x.tenantId,x.vendorId,x.name,x.status,JSON.stringify(x.questions),JSON.stringify(x.answers),x.score]);return q.rowCount?find(QS,x.tenantId,q.rows[0].id):null},
 async submitQuestionnaire(t,id,answers){const q=await store.query(`UPDATE vendor_questionnaires SET status='submitted',answers=$3::jsonb,submitted_at=now(),updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id,JSON.stringify(answers||{})]);return q.rowCount?find(QS,t,id):null},
 async reviewQuestionnaire(t,id,score){const n=Number(score);if(n<0||n>100)s.reviewQuestionnaire({},n);const q=await store.query(`UPDATE vendor_questionnaires SET status='reviewed',score=$3,reviewed_at=now(),updated_at=now() WHERE tenant_id=$1 AND id=$2::uuid RETURNING id::text`,[t,id,n]);return q.rowCount?find(QS,t,id):null},
 async createDocument(input){const x=s.normalizeDocument(input),q=await store.query(`INSERT INTO vendor_assurance_documents(tenant_id,vendor_id,type,reference,period_end,expires_at,status,exceptions) SELECT $1,v.id,$3,$4,NULLIF($5,'')::timestamptz,NULLIF($6,'')::timestamptz,$7,$8::jsonb FROM risk_vendors v WHERE v.tenant_id=$1 AND v.id=$2::uuid RETURNING id::text`,[x.tenantId,x.vendorId,x.type,x.reference,x.periodEnd,x.expiresAt,x.status,JSON.stringify(x.exceptions)]);return q.rowCount?find(DS,x.tenantId,q.rows[0].id):null},
 async createReview(input){const x=s.normalizeReview(input),q=await store.query(`INSERT INTO vendor_risk_reviews(tenant_id,vendor_id,reviewer,score,risk_band,findings,status,reviewed_at,next_review_at) SELECT $1,v.id,$3,$4,$5,$6::jsonb,$7,$8::timestamptz,NULLIF($9,'')::timestamptz FROM risk_vendors v WHERE v.tenant_id=$1 AND v.id=$2::uuid RETURNING id::text`,[x.tenantId,x.vendorId,x.reviewer,x.score,x.riskBand,JSON.stringify(x.findings),x.status,x.reviewedAt,x.nextReviewAt]);return q.rowCount?find(RS,x.tenantId,q.rows[0].id):null},
 async metrics(t){const[v,q,d,r]=await Promise.all([store.query(`${VS} WHERE tenant_id=$1`,[t]),store.query(`${QS} WHERE tenant_id=$1`,[t]),store.query(`${DS} WHERE tenant_id=$1`,[t]),store.query(`${RS} WHERE tenant_id=$1`,[t])]);return s.metrics({vendors:v.rows,questionnaires:q.rows,documents:d.rows,reviews:r.rows})}
}}
function createVendorRiskManagementRepository(store){if(store.type==='json')return json(store);if(store.type==='postgres')return pg(store);throw new Error(`Unsupported store type: ${store.type}`)}module.exports={createVendorRiskManagementRepository};
